### PR TITLE
i348: added halt at end in ccs1 sample and unit test

### LINKED ISSUE #348: No key in yaml for stop contest automatically
**Describe the issue**: 

There is a missing key for stop contest automatically in contest.yaml
During the PacNW that settings was not set manually, it should be
in the contest.yaml.
That settings can only be set using the Admin UI Edit Contest Time

**Correction**

After analysis there is an existing key that sets the auto stop clock setting.
auto-stop-clock-at-end: true

That key is also present with reports: Export Contest YAML files and Export -> Export contest.yaml

**To Reproduce**: 

As part of this fix/push ccs1 now has auto-stop-clock-at-end: true

start server, --load ccs1
start admin
goto Time tab, Edit Contest Time for site 1

**Expected behavior**: 

The checkbox stop contest automatically should be checked

**Actual behavior**: 

The checkbox stop contest automatically is not checked

**Environment**: 

All.

**Log Info**:  

**Screenshots**:  

**Additional context**:

### PR DESCRIPTION
**Pull request by lane55**
Code was already in place to load key: auto-stop-clock-at-end
Added key into sample contest ccs1 (also for data for unit test)

### Description of what the PR does

Adds test data for auto-stop-clock-at-end in ccs1 sample contest

### Issue which the PR fixes

#348 
Key is present, missing test data and unit tests.

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Microsoft Windows [Version 10.0.19044.1586]

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Either use ccs1 sample or add auto-stop-clock-at-end: true   (to contest.yaml)

start server, --load ccs1
start admin
navigate to Time tab, Edit Contest Time for site 1

Expected: 

The checkbox stop contest automatically should be checked

### CODE REVIEW

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java [hunk 1]
```diff
@@ -3674,5 +3674,34 @@ private IInternalContest fullLoadSampleContest(String sampleName) throws Excepti
...
+     * 
+     * @throws Exception
+     */
+    public void testisHaltContestAtTimeZero() throws Exception {
+        String sampleContestDirName = "ccs1";
+        String dirname = getContestSampleCDPConfigDirname(sampleContestDirName);
+        
+        IInternalContest contest = snake.fromYaml(null, dirname, false);
+        assertNotNull("Expecting to load ccs1 contest",contest);
+        assertTrue("Expected halt at end of contest ", contest.getContestInformation().isAutoStartContest());
```
Comment (clevengr) [inline test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3689]: This line is checking `isAutoStartContest()`.  I don't see how "auto START contest" is related to what the method claims to be testing -- which is that autoSTOP is correctly set.

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java [hunk 2]
```diff
@@ -3674,5 +3674,34 @@ private IInternalContest fullLoadSampleContest(String sampleName) throws Excepti
...
+     * Test halt-contest-clock-at-end value, for when missing key/value
+     * @throws Exception
+     */
+    public void testisHaltContestAtTimeZeroNegative() throws Exception {
+        String sampleContestDirName = "ccs2";
+        String dirname = getContestSampleCDPConfigDirname(sampleContestDirName);
+        
+        IInternalContest contest = snake.fromYaml(null, dirname, false);
+        assertNotNull("Expecting to load ccs2 contest",contest);
+        assertFalse("Expected NO halt at end of contest ", contest.getContestInformation().isAutoStartContest());
```
Comment (clevengr) [inline test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3702]: Same issue as above:  it appears to me that this is calling the wrong method.

**Review by clevengr — CHANGES_REQUESTED** [review]
Either change the two lines I've flagged, or provide a PR comment explaining why they are correct as written (I don't think they are...)

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java (hunk 1 above)
Comment (lane55) [reply test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3689]: typo - fixing.

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java (hunk 2 above)
Comment (lane55) [reply test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3702]: same typo - fixing.

**Review by clevengr — APPROVED** [review]
