### PR TITLE
i_1058 Extra submission notification on event feed

### LINKED ISSUE #1058: Duplicate submission notifications on CLICS Event Feed
**Describe the issue**:
If a judge is actively accepting runs to judge, when a new run is submitted by a contestant, 2 identical "**submissions**" notifications appear on the event feed.  This is because of the following lines in `API202306.EventFeedStreamer.java` in the `runChanged() RunListener` implementation:

```
     } else {
        log.info("runChanged: (not adding) " + run.toString());
        String json = getJSONEvent(SUBMISSION_KEY, getNextEventId(), IJSONTool.getSubmissionId(run), jsonTool.convertToJSON(run, servletRequest, null).toString());
        sendJSON(json + NL);
    }

```

When a judge checks out a run for judging, it causes a `RunChanged  `listener to be triggered in `EventFeedStreamer`, which triggers the "add submission" to the event feed code (for some reason).  I think "nothing" should be done in this "else" case.  Commenting out  that code works.  This was carried over from the previous API code, so the original code must be wrong(?) 

Sending the same event twice on the feed should theoretically be idempotent, but... it's wrong.  

**To Reproduce**: 

1. Configure a contest and start the following clients: Server, Feeder, Team, Autojudge
2. Start the feeder feeding a 2023-06 API feed.
3. Start the autojudge.
4. Start the contest.
5. Start a "`curl`" to read the event feed, eg:  `curl -k https://administrator1:administrator1@localhost:50443/contests/sumithello/event-feed`
6. On the team client, submit a run to a problem being autojudged.
7. Observe the curl reader and notice the event feed has 2 submission notifications for the team submission.

**Expected behavior**:
There should be one submission notification.

**Actual behavior**: 
Two notifications are seen on the event feed.

**Environment**: 
All.

**Log Info**:  

**Screenshots**:

**Additional context**:
When the run is submitted by the team, it is added and causes the first submission notification.
When the autojudge claims the run (checks it out) it causes a `runChanged `event, which causes the `EventFeedStreamer `to send an additional submission added notification, which is not right.

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
Do not send an added submission notification if a run changes, only if the run is added.  If a run changes, it implies that was already added at some point, so why add it again.  Appropriate log messages are now provided in the feeder log when runs are added, and, in the case of a change where a run WOULD have been added.

### Issue which the PR addresses
Fixes #1058 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 11
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
1. Configure a contest and start the following clients: Server, Feeder, Team, Autojudge
2. Start the feeder feeding a 2023-06 API feed.
3. Start the autojudge.
4. Start the contest.
5. Start a "`curl`" to read the event feed, eg:  `curl -k https://administrator1:administrator1@localhost:50443/contests/sumithello/event-feed`
6. On the team client, submit a run to a problem being autojudged.
7. Observe the curl reader and notice the event feed has 1 submission notifications for the team submission.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java [hunk 1]
```diff
@@ -485,8 +485,9 @@ public void runChanged(RunEvent event) {
                         }
 
                     } else {
-                        String json = getJSONEvent(SUBMISSION_KEY, getNextEventId(), IJSONTool.getSubmissionId(run), jsonTool.convertToJSON(run, servletRequest, null).toString());
-                        sendJSON(json + NL);
+                        log.info("runChanged: (not adding) " + run.toString());
+//                        String json = getJSONEvent(SUBMISSION_KEY, getNextEventId(), IJSONTool.getSubmissionId(run), jsonTool.convertToJSON(run, servletRequest, null).toString());
```
Comment (SamanwaySadhu) [inline src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java:496]: Are there plans to use these commented out code in future? If not, then I would prefer to remove the comments.

**Review by SamanwaySadhu — APPROVED** [review]
Runs as described.

**Review by kkarakas — APPROVED** [review]
LGTM!
