### PR TITLE
i298: added fix to ensure only one set of judgements presented

### LINKED ISSUE #298: In multi site contest judge should only display one list of judgements
The fix in #292 there was a side effect.   "duplicate" judgements are in the judgement pull down.
Each server by default creates 8 judgements.  If there are 3 sites then the judge would see 24 judgments
(seemingly duplicates, but each judgement has its own site and elementId).

The change is to only show site 1's judgements on all judges on all sites for a multi-site contest.

This bug only appears when Bug #292 is implemented/added.

### PR DESCRIPTION
**Pull request by lane55**
### Description of what the PR does

When judging in multi site contest, only shows one set of judgements
(from site 1)

### Issue which the PR fixes

#298

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

works in all env.

Java version 1.8.0_121
OS: Windows 10 10.0 (amd64)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Test 1 - prove all judgements are on all sites.
Start 3 sites (non-GUI).
Start site 1 with samps\contests\problemflagtest CDP (creates 5 sites)
Start site 2
Start site 3 

- submit and judge a run 
Create 12 teams on site 3
Create 12 judges on site 3

Site 3 team 3 submit run for Sumit 2 problem
Site 3 judge 2 
  request run
  On Select Judgement
  Use Select Judgement pulldown
  Select the last judgement in the list
  test: ensure that there are only one set of judgements
  Judge the run

Run the Runs report
     test: for the judgement there should be a 'site=1', similar to below
     'No - Wrong Answer' site=1 by judge3/s3 at 1

Expected Results

One set of eight judgements shown to judge in Select Judgement pulldown (not 24 Judgements)

On Runs report for judged run show judgement is from site 1.

Actual Results

24 judgements judgements shown to judge in Select Judgement pulldown 

On Runs report for judged run may wil be from site 3

### CODE REVIEW

File: src/edu/csus/ecs/pc2/core/execute/JudgementUtilites.java [hunk 1]
```diff
@@ -312,6 +314,49 @@ public static String getExecuteDirectoryName(ClientId id) {
...
+                }
+            } else {
+                // add judgements from model (if not a multiSiteContest
+                list.add(judgement);
+            }
+        }
+
+        if (list.size() == 0) {
+            /**
+             * A catch all condition. If a rare condition occurs where there are no judgements added to the list, all all model's judgements.
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/execute/JudgementUtilites.java:350]: The end of this comment doesn't make sense; please fix typo.

**Review by clevengr — APPROVED** [review]
There was one minor typo in a comment, which I noted; otherwise, this PR looks good to me.

**Review by clevengr — COMMENTED** [review]
I'm revoking my original approval of this PR.  I gave that approval after having reviewed all the source code.  I forgot that I should also run the "How to show that this PR _works_" tests.  When I followed up and ran the tests, as closely as I could to the way they are listed in the PR, the test failed.

Specifically, I did the following:
- Opened Eclipse pointing to Doug's pc2v9 fork.
- Did a "Pull" to get the latest code.
- Ran `package.xml` to generate a new distribution.
- Copied the resulting pc2v9buildxxx.zip file to a clean directory and unzipped it.
- Made three subfolders, "Site1", "Site2", and "Site3".  
- Copied the default pc2v9.ini into each site subfolder.
- Edited the pc2v9.ini in Site2 and Site3 to reference the proper localhost port number in the [client] section and the proper remoteserver (site 1) in the [server] section. (Specifically, the Site2 **[client]** section specifies `server=localhost:51002` and the **[server]** section specifies `remoteServer=localhost:50002`, while the Site 3 **[client]** section specifies `server=localhost:52002` and the Site 3 **[server]** section specifies `remoteServer=localhost:50002`.)
- Started a server from the Site1 folder, using --load problemflags
- Started servers from the Site2 and Site3 folders respectively.
- Verified that the Server "Sites" tabs on all three servers shows all three sites connected and using the expected port numbers.
- Started Admins on Site 1 and Site 3.
- Used the Site 3 Admin to create 12 teams and 12 judges on Site 3.
- Selected "Start All" on one of the Admins, to start the contest.
- Logged in as Team 3 on Site 3, then submitted a run for the Sumit 2 problem.
- Logged in as Judge 2 on Site 3, then requested the submitted run.

At this point I believe I have done everything as stated in the PR.  And at this point I have:

Expected:  when I look at the "Select Judgement" dropdown list I should only see ONE set of Judgements (a total of 8 selectable judgements).

Actual:  I can see 25 judgements in the dropdown list:  two sets of 8, plus one set of 9.

So the Issue is not resolved.

**Comment by clevengr** [comment]
Additional info:  upon following the steps in the PR (select the last judgement in the list -- there should have been only 8 but there were 25), looking at the Runs report I see the following:
```
CSUS Programming Contest Control System
Version 9.8build 20220205 (Saturday, February 5th 2022 19:06 UTC) Java ver 1.8.0_201 build 5959 Windows 10 10.0 (amd64) 
Contest Title: Problem Flag Test Contest
On: Saturday, February 5, 2022 12:24:41 PM PST  Contest date/time: Sat Feb 05 11:42:23 PST 2022 on site 2
Profile: Default (Default Contest)

** Runs Report

-- 1 runs --
run 1 JUDGED s3 at 1 (Sat Feb 05 11:43:55 PST 2022) team3 (team3) Sumit 2 Java 
    Judgement was sent to team.
    No submitted files found.
      'No - Other - Contact Staff' site=2 by judge2/s3 at 41
     There are 7 test cases.
     There are 0 test case results.

end report
```
Notice that there IS a "site=x" line in the report (which I believe demonstrates that I'm running the updated code, because my impression is that this field didn't used to exist in the Runs report).  Note however that the field value is "site=2".   If the code fix in the PR was working I would expect that to say "site=1", since in a multisite contest all judgements are supposed to be from Site 1.

**Review by clevengr — APPROVED** [review]
I had a mistake in my testing procedure; after fixing that mistake I was able to successfully perform the test steps.  I'm approving this PR (again :)

**Comment by clevengr** [comment]
Reviewed code changes and performed recommended PR tests, which all passed.  Merging this PR into Develop.
