### PR TITLE
i586: for shadow compare, use judgement acronym if Big 5 judgement missing 

### LINKED ISSUE #586: Shadow Run Compare, sometimes incorrect judgement acronym assigned
**Describe the issue**: please provide a clear and concise description of what the bug is.  

**To Reproduce**: please describe, in order, the steps to reproduce the behavior:

**Expected behavior**: please provide a description of what you *expected* to happen when you took the above steps:  

**Actual behavior**: please describe what _actually_ happened when you took the above steps:

**Environment**: please complete the following information:
 - OS name and version under which the issue was detected (e.g. Windows 10 or Ubuntu 18.04):
 - PC2 Version (e.g. 9.7.0):   
 - Browser (if the bug is related to web-based team clients) (e.g. _Chrome Version 75.0.3770.142_ or _Safari Version 11.1.2_):

**Log Info**:  PC^2 generates logs (in the **logs** folder for client modules; under the **profiles** folder for the PC2 Server).  Please review the relevant logs and provide copies of them as attachments -- particularly if the logs show Exceptions being thrown.  

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.

**Additional context**: please add any other context about the issue here.

### PR DESCRIPTION
**Pull request by lane55**
Before would not add all rows into shadow run compare because if validator judgement string was not a Big 5 judgement would
not add row for run.   Now will add all run rows and if
validator judgement string not in Big five will use existing
judgement acronym

Before submitting your Pull Request, please make sure you have read the [Guidelines for Submitting Pull Requests](https://github.com/pc2ccs/pc2v9/wiki/Guidelines-for-Submitting-Pull-Requests).  Then please provide the following information:

### Description of what the PR does

Adds all submissions into Shadow Run Compare.  Before only added submission rows if validator judgement string
matched Big 5 judgements.

### Issue which the PR fixes

#586

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

### CODE REVIEW

File: src/edu/csus/ecs/pc2/shadow/ShadowController.java [hunk 1]
```diff
@@ -690,11 +692,33 @@ private Map<String, ShadowJudgementInfo> getJudgementsMap(Run[] pc2Runs) {
                         } else {
                             // we've exhausted methods of obtaining an acronym
                             log.warning("Null judgement acronym for run " + run.getNumber() + ", judgement string " + judgementString + "; skipping");
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/shadow/ShadowController.java:694]: Are we leaving the old message here indicating the entry is being "skipped", even though it might not be if the acronym replacement works?

File: src/edu/csus/ecs/pc2/shadow/ShadowController.java [hunk 2]
```diff
@@ -690,11 +692,33 @@ private Map<String, ShadowJudgementInfo> getJudgementsMap(Run[] pc2Runs) {
...
+
+                            Judgement judgement = localContest.getJudgement(jr.getJudgementId());
+                            if (judgement == null) {
+                                log.warning("Null judgement acronym for run " + run.getNumber() + ", Judgement not found in model for run");
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/shadow/ShadowController.java:698]: s/judgement acronym/judgment/

**Review by johnbrvc — APPROVED** [review]
Looks fine to me.  Could not test easily on my PC (lacking resources). But worse case, this should be benign, at best case it solves the problem.

File: src/edu/csus/ecs/pc2/shadow/ShadowController.java [hunk 3]
```diff
@@ -605,9 +605,11 @@ private Map<String, String> getRemoteSubmissionsToJudgementsMap() {
      * Returns a Map which maps submissionIds to {@link ShadowJudgementInfo} objects for every submission (run) in the
      * specified array of PC2 Runs.
      */
-    private Map<String, ShadowJudgementInfo> getJudgementsMap(Run[] pc2Runs) {
+    protected Map<String, ShadowJudgementInfo> getJudgementsMap(Run[] pc2Runs) {
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/shadow/ShadowController.java:608]: What's the justification for expanding the access?

File: src/edu/csus/ecs/pc2/shadow/ShadowController.java [hunk 4]
```diff
@@ -605,9 +605,11 @@ private Map<String, String> getRemoteSubmissionsToJudgementsMap() {
...
 
         Map<String, ShadowJudgementInfo> pc2JudgementInfoMap = new HashMap<String, ShadowJudgementInfo>();
+        
+        log = getLog();
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/shadow/ShadowController.java:612]: This call is already made in method `start()`.    It doesn't seem like a good idea to have multiple places throughout the code doing assignments to `log`.    (What probably should instead be done is to replace every reference to variable `log` with a call to `getLog()`...)

File: src/edu/csus/ecs/pc2/shadow/ShadowController.java (hunk 1 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/shadow/ShadowController.java:694]: I agree with @johnbrvc :  I think the word "skipping" should be removed from this log message since we're no longer actually skipping the run (I think the log message should be retained; it just shouldn't say "skipping"...)

File: src/edu/csus/ecs/pc2/shadow/ShadowController.java (hunk 2 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/shadow/ShadowController.java:698]: This added code block is inside the `else` for the condition  `(jr != null)`.  Therefore, this code will get executed when (and only when) `jr == null`.  But this added code calls `jr.getJudgementId()`.  I believe this code won't do what is intended; it will throw an NPE.

Cannot approve this change.

Comment (clevengr) [reply src/edu/csus/ecs/pc2/shadow/ShadowController.java:698]: I agree; it's misleading to say the judgement ACRONYM is null; it's the Judgement that's null at this point.

File: src/edu/csus/ecs/pc2/shadow/ShadowController.java [hunk 5]
```diff
@@ -690,11 +692,33 @@ private Map<String, ShadowJudgementInfo> getJudgementsMap(Run[] pc2Runs) {
...
+                                 */
+                                String acronymnName = judgement.getAcronym().toString();
+
+                                // Add ShadowJudgementInfo for run into pc2JudgementInfoMap 
+                                ClientId judgerClientID = jr.getJudgerClientId();
+                                ShadowJudgementPair pair = new ShadowJudgementPair(submissionId, acronymnName, "<pending>");
+                                ShadowJudgementInfo info = new ShadowJudgementInfo(submissionId, teamID, problemID, languageID, judgerClientID, pair);
+                                pc2JudgementInfoMap.put(submissionId, info);
+
+                                log.info("Null judgement acronym for run " + run.getNumber() + ", cjudgement string " + judgementString + "; not skipped assigned acronym = " + acronymnName);
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/shadow/ShadowController.java:712]: What does `cjudgement string` mean?  Log messages should make sense to human readers...   Is this just a typo and `cjudgement` was intended to be just `judgement`??

**Review by clevengr — APPROVED** [review]
It would be nice if some of the issues which have been commented on could be cleaned up, but overall the changes seem benign at worst and helpful at best.

**Review by clevengr — APPROVED** [review]

**Review by johnbrvc — APPROVED** [review]
Log messages look OK.
