### PR TITLE
i778 Add problem fails due to NPE in sandbox pane, fixes #778

### LINKED ISSUE #778: Adding a new problem from the GUI causes an NPE preventing the addition of the problem
**Describe the issue**:
New problems can not be added using the GUI.  An **NPE** occurs during the initialization of the new problem.

**To Reproduce**:
Try to add a new problem from the "`Problems`" tab on an administrator account by pressing the "`Add`" button.
Nothing happens.

**Expected behavior**: 
A dialog should appear that allows the user to fill in the information for the new problem.  

**Actual behavior**:
Nothing happens when the `Add `button is pressed; an NPE is generated and the dialog to add the problem never appears.

**Environment**: 
```
Version         : 9.9build 20230523
Build Date      : Tuesday, May 23rd 2023 03:28 UTC
Build Number    : 6607~develop
OS              : Linux 5.15.0-56-generic (amd64)
Java Version    : 17.0.5


```
**Log Info**:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "edu.csus.ecs.pc2.core.model.Problem.getSandboxType()" because "this.problem" is null
        at edu.csus.ecs.pc2.ui.EditProblemSandboxPane.setProblem(EditProblemSandboxPane.java:138)
        at edu.csus.ecs.pc2.ui.EditProblemPane.setProblem(EditProblemPane.java:2275)
        at edu.csus.ecs.pc2.ui.EditProblemFrame.setProblem(EditProblemFrame.java:77)
        at edu.csus.ecs.pc2.ui.ProblemsPane.addProblem(ProblemsPane.java:562)
        at edu.csus.ecs.pc2.ui.ProblemsPane$4.actionPerformed(ProblemsPane.java:553)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Screenshots**: 

**Additional context**: 
The `EditProblemSandboxPane `expects the problem object passed in to be non-null.  When a new problem is added, null is passed since the problem does not yet exist.

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
Fixes the bug where new problem could not be added by the GUI.
CI for incorrectly displayed max output size and not copying max output K bytes when copying a problem.

### Issue which the PR addresses
Fixes #778 
### Environment in which the PR was developed (OS,IDE, Java version, etc.)
```
Application     : CSUS Programming Contest Control System
Version         : 9.9build 20221222
Build Date      : Thursday, December 22nd 2022 18:07 UTC
OS              : Windows 11 10.0 (amd64)
Java Version    : 1.8.0_321

```
### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
1) Bring up the pc2server
2) Bring up the pc2admin
3) Select the Problems tab
4) Click on the "Add" button.  Note that the Add problem dialog correctly displays.

To test the CI:
After step 3) above:
4) Select an existing problem.
5) Click on Copy.
6) Select a new name at the prompt
7) Note that the max output size is the same as the copied problem and not 8388608

### CODE REVIEW

**Review by lane55 — APPROVED** [review]
Approved changes

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java [hunk 1]
```diff
@@ -192,6 +182,40 @@ protected void initializeFields(Problem inProblem) {
...
+            }
+            getPC2SandboxOptionMemLimitTextbox().setText(Integer.toString(Problem.DEFAULT_MEMORY_LIMIT_MB));
+       } else {
+            //activate the appropriate sandbox selection button (the buttons are in a group so selecting one will deselect the others)
+            if (problem.getSandboxType() == SandboxType.NONE) {
+                getUseNoSandboxRadioButton().setSelected(true);
+                
+            } else if (problem.getSandboxType() == SandboxType.PC2_INTERNAL_SANDBOX) {
+                isCheckSandboxSupport();
+                getUsePC2SandboxRadioButton().setSelected(true);
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java:208]: It bothers me greatly to see a call to a method that returns a boolean which is then ignored.  Shouldn't a return value of `false` here cause some kind of notification to the user?

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java [hunk 2]
```diff
@@ -192,6 +182,40 @@ protected void initializeFields(Problem inProblem) {
...
+                getUseNoSandboxRadioButton().setSelected(true);
+            }
+            getPC2SandboxOptionMemLimitTextbox().setText(Integer.toString(Problem.DEFAULT_MEMORY_LIMIT_MB));
+       } else {
+            //activate the appropriate sandbox selection button (the buttons are in a group so selecting one will deselect the others)
+            if (problem.getSandboxType() == SandboxType.NONE) {
+                getUseNoSandboxRadioButton().setSelected(true);
+                
+            } else if (problem.getSandboxType() == SandboxType.PC2_INTERNAL_SANDBOX) {
+                isCheckSandboxSupport();
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java:207]: It bothers me greatly to see a call to a method (`isCheckSandboxSupport()`) which returns a boolean which is then ignored. Shouldn't a return value of false here cause some kind of notification to the user?

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java [hunk 3]
```diff
@@ -97,10 +94,13 @@ public class EditProblemSandboxPane extends JPanePlugin {
...
     //setting this to True will cause the Sandbox Pane GUI panels to show boundary borders... useful for layout debugging.
     private boolean debugShowPanelBorders = false;
+
+    // remember if we told the user this system does not support sandboxes so we don't keep nagging
+    private boolean noSandboxNagMessage = false;
     
     //setting this to True will override the prohibition on selecting a Sandbox when running on Windows.
     // Note that THIS IS FOR DEBUGGING PURPOSES; it does NOT imply any support for Windows sandboxing.
-    private boolean debugAllowSandboxSelectionOnWindows = true;
+    private boolean debugAllowSandboxSelectionOnWindows = false;
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java:103]: I'm not convinced we should be disabling this boolean at this point in the development process.  I normally only have access to a Windows box for testing.  I believe that this change is going to stop me from testing this PR.

The original intent of this boolean (I was the one who added it to the code) was to _allow_ declaring a sandbox on a Windows machine for testing purposes (with the understanding that the developer/tester is smart enough, while testing sandbox issue, to know that it wasn't actually possible to _execute_ a sandbox on the windows test machine.

Then the idea was that, once ALL sandbox development and testing was completely, one of the very last things we'd do is THEN change this variable to `false` before releasing a production version of the code.

**Review by clevengr — COMMENTED** [review]
I have reviewed the code changes and made several comments which I'd like to see addressed in reply comments (although not necessarily "fixed").   I'm proceeding to running an actual test of the changes.

**Review by clevengr — APPROVED** [review]
I've tested the PR and it seems to work, so I'm approving it.  I would however at least like to see responses to the several comments I made in `EditProblemSandboxPane`.  (But I understand that my approval means I don't get the right to demand such responses :) )

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java [hunk 4]
```diff
@@ -943,6 +967,17 @@ private Component getHorizontalStrut_2() {
         return horizontalStrut_2;
     }
 
+    private boolean isCheckSandboxSupport()
+    {
+        boolean bSupported = OSCompatibilityUtilities.areSandboxesSupported(getContest(), getLog());
+        if(!bSupported){
+            if(!noSandboxNagMessage) {        
+                JOptionPane.showMessageDialog(getParentPane(), "You should be aware of the fact that this system does not support sandboxes.\nTherefore, you are not able to configure problems that do require a sandbox.", "Sandbox Not Available Notice", JOptionPane.WARNING_MESSAGE);
+                noSandboxNagMessage = true;
```
[the remark this answers is not in the document]
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java:976]: Agreed.  The checkbox is a good idea.  I'll add that using one of the methods suggested.

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java (hunk 2 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java:207]: The message to the user is issued in the isCheckSandboxSupport() method if sandboxes are not supported.  If sandboxes are NOT supported, we do not want to change an existing problem's setting, we just want to notify the user that an existing problem uses sandboxes, and, they're not supported on the current system.  So, there's really nothing to be done in this case if they're not supported.  I don't think it's bad programming style to not use a return value.  Maybe change the name of the method to: isCheckSandboxSupportAndNotify()?

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java (hunk 3 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java:103]: Yes.  I had turned it off for testing.  I wonder, though, if in production we should turn it off (false)?  I'll put it back to do true since we are not making a production release at this time.

Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java]: Fixed in[ this commit](https://github.com/pc2ccs/pc2v9/pull/780/commits/c1c01fe246f2af6a8190f47e20cb9563add8b221).

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java]: Fixed in [this commit](https://github.com/pc2ccs/pc2v9/pull/780/commits/de5824b5ed395ad8b4aa2bc36d614674a5339c8b).

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java (hunk 2 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java:209]: I don't think changing the name of the method is necessary (or appropriate).  I think boolean accessors which query a status ("isSandboxSupported" in this case) shouldn't have side effects -- they should return a yes/no answer to the question implied by the method name.  The _calling_ code should then do what is necessary/appropriate depending on the answer (such as notifying the user of an issue).   

I will concede that this is somewhat of a personal prejudice; I spent a lot of time teaching students about "rules of good programming" and one of those "rules" is "functions shouldn't have side-effects".  One of the primary reasons for this is that it greatly reduces issues with formal verification.

Having said that, I also concede that the idea that we will _ever_ get to the point of applying any kind of formal verification tools/techniques to PC2 is, at best, laughable -- so this really isn't a huge issue and I don't think any change is needed (hence the reason I went ahead and "Approved" the PR).  I just couldn't help myself from pointing it out as a general design principle (although I grant, not one that everyone agrees on...)

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java (hunk 3 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java]: > Yes. I had turned it off for testing. I wonder, though, if in production we should turn it off (false)? ...

Yes, I fully agree we SHOULD NOT turn it "off" in production (that is, the variable should be set `false` in a production release) -- which I THINK is what you are saying (correct me if I'm wrong).    What we probably need is a single system-wide global flag like "isProductionRelease", and have all conditionals like this (there are other places in the code where similar things exist)  assign neither `true` nor `false` but instead the "global isProductionRelease" flag value.  That way, we have only a SINGLE place we have to remember to change when we finally "promote" a release to "production" (public).

Having said that, it's yet another one of those "Someday" things....

**Review by lane55 — APPROVED** [review]
Approved new checkbox code

**Review by clevengr — CHANGES_REQUESTED** [review]
I'm not sure whether it's a manifestation of the latest changes, or it's just something I didn't catch in my previous testing, but:

When I Edit an existing problem and try to add a sandbox (on a Windows system, with the "allowSandboxOnWindows" flag true), the code does what is expected:  it pops up a dialog warning me that I cannot expect to use a sandbox.

However, when I select Add Problem, it does NOT give me the warning dialog -- it happily lets me add a new problem with a sandbox configured.  This doesn't seem like correct behavior.

(Ironically, if I then EDIT the new problem I just added, it DOES pop up the warning dialog.)

**Comment by johnbrvc** [comment]
> I'm not sure whether it's a manifestation of the latest changes, or it's just something I didn't catch in my previous testing, but:
> 
> When I Edit an existing problem and try to add a sandbox (on a Windows system, with the "allowSandboxOnWindows" flag true), the code does what is expected: it pops up a dialog warning me that I cannot expect to use a sandbox. Further, I can use the "Don't show this message again" checkbox to suppress the dialog on subsequent edits, as expected.
> 
> However, when I select Add Problem, it does NOT give me the warning dialog -- it happily lets me add a new problem with a sandbox configured. This doesn't seem like correct behavior.
> 
> (Ironically, if I then EDIT the new problem I just added, it DOES pop up the warning dialog.)

This behavior is by design iff the `debugAllowSandboxSelectionOnWindows `flag is **true**.  If the flag is **false**, an error is printed.  This is different than editing a problem since it is possible that an existing problem already has the sandbox flag set on Windows (ie having loaded a CDP that had sandbox problems, for example).  Therefore, when you edit that problem, (whether or not the `debugAllowSandboxSelectionOnWindows `is set), a warning (nag) is printed making you aware of that.  Adding a problem is simply not allowed on windows (unless the `debugAllowSandboxSelectionOnWindows `is set, and, that is for testing only as we pointed out.)  Here is the relevant code:

```
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    if (debugAllowSandboxSelectionOnWindows || ! (Utilities.getOSType().equals(OSType.WINDOWS) ) ) {
                        enableEditProblemSandboxTabComponents();
                        enableUpdateButton();
                        mostRecentlySelectedType = SandboxType.PC2_INTERNAL_SANDBOX;
                    } else  {
                        JOptionPane.showMessageDialog(getParentPane(), notAvailableOnWindowsMsg, "Not Available on Windows", JOptionPane.WARNING_MESSAGE);
                        if (mostRecentlySelectedType == SandboxType.NONE) {
                            getUseNoSandboxRadioButton().setSelected(true);
                        } else if (mostRecentlySelectedType == SandboxType.PC2_INTERNAL_SANDBOX) {
                                getUsePC2SandboxRadioButton().setSelected(true);
                            }
                    }
                }

```

File: src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java (hunk 2 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/ui/EditProblemSandboxPane.java:209]: Understood.  So does this mean that you do approve the PR.  If so, then we can merge it, correct?

**Review by clevengr — APPROVED** [review]

**Comment by lane55** [comment]
two approvals, merging
