### PR TITLE
i_1077 Handle each EF client in its own thread

### LINKED ISSUE #1077: Clients connected to the Event Feeder can block other clients
**Describe the issue**: 
During a smoke test for the NAC2025, we had several clients from across 10 timezones connecting to PC2 running on an AWS EC2 instance.  It seems if one of those clients goes away or does not consume the data sent to it, it can cause the sending loop in the event feeder to hang (timeout).  This timeout appears to be quite long, and it causes other clients to give up waiting and reconnect, thereby creating more "hung" clients.

**To Reproduce**: 
This problem happens under load is not easily producible. The idea is to connect many clients to an event feeder, then make one of them stop accepting the feed, or, if the client "just goes away" without closing the connection.

**Expected behavior**: 
The event feeder pc2 server should not hang.

**Actual behavior**:
The event feeder pc2 server appears to hang.

**Environment**: 
All.

**Log Info**: 
```
250423 172010.213|INFO|Thread-1305|log|Problem trying to send JSON '{"type":"judgements","token":"pc2-3204","id":"Run-6537402952255751008","data": {"id":"Run-6537402952255751008","submission_id":"1602","judgement_type_id":"RTE","start_time":"2025-04-23T17:19:56.998Z","start_contest_time":"00:21:16.989","end_time":"2025-04-23T17:20:06.833Z","end_contest_time":"00:21:26.824","max_run_time":0.107}}
'
|org.eclipse.jetty.io.EofException: null
|    at org.eclipse.jetty.io.ChannelEndPoint.flush (ChannelEndPoint.java:192)
|    at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush (SslConnection.java:793)
|    at org.eclipse.jetty.io.WriteFlusher.flush (WriteFlusher.java:408)
|    at org.eclipse.jetty.io.WriteFlusher.write (WriteFlusher.java:302)
|    at org.eclipse.jetty.io.AbstractEndPoint.write (AbstractEndPoint.java:129)
|    at org.eclipse.jetty.server.HttpConnection$SendCallback.process (HttpConnection.java:684)
|    at org.eclipse.jetty.util.IteratingCallback.processing (IteratingCallback.java:246)
|    at org.eclipse.jetty.util.IteratingCallback.iterate (IteratingCallback.java:208)
|    at org.eclipse.jetty.server.HttpConnection.send (HttpConnection.java:480)
|    at org.eclipse.jetty.server.HttpChannel.sendResponse (HttpChannel.java:768)
|    at org.eclipse.jetty.server.HttpChannel.write (HttpChannel.java:801)
|    at org.eclipse.jetty.server.HttpOutput.write (HttpOutput.java:147)
|    at org.eclipse.jetty.server.HttpOutput.write (HttpOutput.java:140)
|    at org.eclipse.jetty.server.HttpOutput.flush (HttpOutput.java:242)
|    at edu.csus.ecs.pc2.clics.API202306.EventFeedStreamer.sendJSON (EventFeedStreamer.java:878)
|    at edu.csus.ecs.pc2.clics.API202306.EventFeedStreamer$RunListener.runChanged (EventFeedStreamer.java:479)
|    at edu.csus.ecs.pc2.core.model.InternalContest.fireRunListener (InternalContest.java:453)
|    at edu.csus.ecs.pc2.core.model.InternalContest.updateRun (InternalContest.java:1677)
|    at edu.csus.ecs.pc2.core.model.InternalContest.updateRun (InternalContest.java:1614)
|    at edu.csus.ecs.pc2.core.PacketHandler.sendJudgementUpdate (PacketHandler.java:2505)
|    at edu.csus.ecs.pc2.core.PacketHandler.handlePacket (PacketHandler.java:216)
|    at edu.csus.ecs.pc2.core.InternalController.receiveObject (InternalController.java:2426)
|    at edu.csus.ecs.pc2.core.transport.TransportManager$2.run (TransportManager.java:343)
|    at java.lang.Thread.run (Thread.java:1583)
250423 172010.214|INFO|Thread-1305|log|Closing client stream HttpOutput@e8d4c74{OPEN}
250423 172010.214|INFO|Thread-1305|log|Closed client stream.
250423 172010.215|INFO|Thread-1305|log|Problem trying to send JSON '{"type":"runs","token":"pc2-3205","id":"TestCase-2254575542049700405","data": {"id":"TestCase-2254575542049700405","judgement_id":"Run-6537402952255751008","ordinal":1,"judgement_type_id":"AC","time":"2025-04-23T17:19:58.553Z","contest_time":"00:21:18.427","run_time":0.136}}
'
|org.eclipse.jetty.io.EofException: null
|    at org.eclipse.jetty.io.ChannelEndPoint.flush (ChannelEndPoint.java:192)
|    at org.eclipse.jetty.io.WriteFlusher.flush (WriteFlusher.java:408)
|    at org.eclipse.jetty.io.WriteFlusher.write (WriteFlusher.java:302)
|    at org.eclipse.jetty.io.AbstractEndPoint.write (AbstractEndPoint.java:129)
|    at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onIncompleteFlush (SslConnection.java:364)
|    at org.eclipse.jetty.io.AbstractEndPoint$2.onIncompleteFlushed (AbstractEndPoint.java:54)
|    at org.eclipse.jetty.io.WriteFlusher.write (WriteFlusher.java:311)
|    at org.eclipse.jetty.io.AbstractEndPoint.write (AbstractEndPoint.java:129)
|    at org.eclipse.jetty.server.HttpConnection$SendCallback.process (HttpConnection.java:684)
|    at org.eclipse.jetty.util.IteratingCallback.processing (IteratingCallback.java:246)
|    at org.eclipse.jetty.util.IteratingCallback.iterate (IteratingCallback.java:208)
|    at org.eclipse.jetty.server.HttpConnection.send (HttpConnection.java:480)
|    at org.eclipse.jetty.server.HttpChannel.sendResponse (HttpChannel.java:768)
|    at org.eclipse.jetty.server.HttpChannel.write (HttpChannel.java:801)
|    at org.eclipse.jetty.server.HttpOutput.write (HttpOutput.java:147)
|    at org.eclipse.jetty.server.HttpOutput.write (HttpOutput.java:140)
```

**Screenshots**: 

**Additional context**:

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
This will prevent one bad client from clogging up the `EventFeedStreamer`.
Also write new event to log FIRST so we don't get duplicate events in the event that PC2 is stopped while sending to clients.
Retry submission fetching.

### Issue which the PR addresses
Fixes #1077 
### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 11
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

1. This bug fix is very hard to test.
2. You need a full contest.
3. You need playback data for the contest (via feeder1)
4. You need to start up a 2023-06 API server (via feeder2)
5. You need to start several shadows to the primary (3 shadows should do)
6. You need to start 2 CDS's to the primary.
7. You then have to "jam -up" one or more of the shadows/CDS's by blocking their firewall or unplugging their network cable.  This will cause the connection to hang on the PC2 Event Feeder side.
8. PC2 should recover from these type of connected client failures.

### CODE REVIEW

**Comment by troy2914** [comment]
This looks reasonable to me, though i only did a code review.

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java [hunk 1]
```diff
@@ -128,24 +130,83 @@ public class EventFeedStreamer extends JSON202306Utilities implements Runnable,
...
         }
 
+        public boolean wantTerminateClient() {
+            return terminateClient;
+        }
+
+        public void setTerminateClient() {
+            // if terminateClient is false, this means he caller is asking us
+            // to stop because they're done.  (eg. removeClient() being called)
+            // If there's data pending, we want to wait a big for it to drain.
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java]: Multiple minor typos in the above lines:
- `he` was probably intended to be `the`
- `big` was probably intended to be `bit`.

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java [hunk 2]
```diff
@@ -128,24 +130,83 @@ public class EventFeedStreamer extends JSON202306Utilities implements Runnable,
...
             this.filter = filter;
         }
 
+        public boolean wantTerminateClient() {
+            return terminateClient;
+        }
+
+        public void setTerminateClient() {
+            // if terminateClient is false, this means he caller is asking us
+            // to stop because they're done.  (eg. removeClient() being called)
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java]: It's not clear what the reference to `removeClient()` in the above comment is talking about.  As far as I can find, there is no such method anywhere in the code.  (Was this intended to refer to `removeStream()`?)

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java [hunk 3]
```diff
@@ -128,24 +130,83 @@ public class EventFeedStreamer extends JSON202306Utilities implements Runnable,
...
+            // If there's data pending, we want to wait a big for it to drain.
+            if(terminateClient == false && outputQueue.isEmpty() == false) {
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java:160]: I don't understand the purpose of the `terminateClient == false` portion of the above `if`.  If someone calls this method (`setTerminateClient()`), and the outputQueue is not empty, don't we want to execute the `Thread.sleep()` regardless of whether `terminateClient` has already been set true?

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java [hunk 4]
```diff
@@ -864,31 +929,32 @@ public synchronized void sendJSON(String string) {
 
         string = replaceEventId (string, newId);
 
+        // Add notification to log before sending to clients
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java:934]: It might be nice (i.e., to help future developers) if this comment include an explanation of WHY we are now putting the event in the log BEFORE sending it instead of after sending it.

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java [hunk 5]
```diff
@@ -864,31 +929,32 @@ public synchronized void sendJSON(String string) {
...
          * Send JSON to each
          */
         for (Map.Entry<OutputStream, StreamAndFilter> entry : streamsMap.entrySet()) {
             StreamAndFilter streamAndFilter = entry.getValue();
 
-            try {
+            // Check if there was a problem with this client, if so, we are no longer
+            // interested in providing it with data
+            if (streamAndFilter.wantTerminateClient()) {
+                removeStream(streamAndFilter.getStream());
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java]: The method `removeStream()` called in the above line is modifying the same map which is being used to control the surrounding `for` loop.  I think this could potentially lead to throwing a `ConcurrentModificationException`.     Unless you're convinced for some reason that no such `ConcurrentModificationException` can happen, I'd suggest handling removal outside the main `for` loop.  (I note that method `removeStream()` is also called directly from the `EventFeedStreamer.run()` method, so that appears to me to be one place where concurrent modification could happen...)

(The standard solution to such an issue is to keep a list within the `for` loop of those items (`streams`, in this case) which need to be removed, and then run a separate `for` loop (after this one finishes) to remove the desired streams. )

**Review by clevengr — CHANGES_REQUESTED** [review]
Reviewed `src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java`.  In addition to several minor comments, I noted two places where I have questions about whether the code is correct.  I'll be happy accept a fix, or an explanation of why my comments don't apply.

File: src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java [hunk 6]
```diff
@@ -309,10 +310,11 @@ public synchronized Response getSubmissionFiles(@Context SecurityContext sc, @Pa
                             + submissionId + " from local model", e2);
                 }
 
-                //if runFiles is still null we failed to get the runfiles from the local model
-                if (runFiles == null) {
+                // We try to fetch the runfiles a few times
+                for(int nTry = 1; runFiles == null && nTry <= MAX_RUNFILE_RETRIES; nTry++) {
+                    // we failed to get the runfiles from the local model
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java:315]: I do not understand the deletion of the line `if (runFiles == null)`.  The code just above that line attempts to pull the runfiles from the local model.  The previous version of the code only tries to fetch them from the server if it failed to get them from the local model (which is indicated by `runFiles` still being null).  Now, it looks like the code attempts to fetch the runFiles from the server (up to three times) _whether or not it successfully got them from the local model_.  This doesn't seem logical; it should only invoke the server IF it failed to get them locally.  Am I missing something?

**Review by clevengr — CHANGES_REQUESTED** [review]
Reviewed `src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java`.  Marked one place where I do not understand the change to the code.

**Review by clevengr — CHANGES_REQUESTED** [review]
Completed a code review.  Marked several places where I've requested either a fix, or an explanation of why the code changes don't appear correct to me.    Moving on to runtime testing.

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java (hunk 1 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java]: Fixed in next push.

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java (hunk 2 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java]: Yes, removeStream() is what was meant.  Fixed in next push.

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java (hunk 3 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java:160]: No.  If `terminateClient `is already true, it means an error happened (we're dead already).  See the `catch`'s in the` run() `method.  In case of an error, there is no point in waiting for the connection to drain.  I fixed the comment to indicate this.

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java (hunk 5 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java]: The thing being operated on and modified is a `ConcurrentHashMap<>`.  AFAICT it's safe to do things on this from different threads, and even in an iterator.   (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html) - that seems to indicate it will never throw a `ConcurrentModificationException`.  While the iterator may not be "up-to-date", that's safe even if it gets something that was removed from the map before we iterated to it, since the reference to the object is still valid.  While I do not think it is necessary, since we're using entrySet(), it may not _hurt_ to put a test for `null `in the loop.  Next push.

File: src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java (hunk 6 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java:315]: Check out the `for()` loop just below.   It first checks if `runFiles == null`.  if `runFiles `is not null, the loop is never executed, and, as soon as it finds the `runFiles`, the loop will exit, else the sentinel will kick in.

File: src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java (hunk 5 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/clics/API202306/EventFeedStreamer.java]: Ok, that _probably_ covers it.

File: src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java (hunk 6 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java:315]: Aha -- I missed the compound condition in the `for` loop.

**Review by SamanwaySadhu — APPROVED** [review]
Did only code review. LGTM!
