### PR TITLE
i_984 Make sure validate stdout/stderr buffers are flushed

### LINKED ISSUE #984: Validator stdout and stderr are never copied correctly for each test case
**Describe the issue**:   
The individual validator **stdout** and **stderr** files for a run's test cases are almost always empty (0 bytes).  These files have the names `valout.#.txt` and `valerr.#.txt`, where # is replaced with the test case number.

**To Reproduce**:
Look in any autojudge or human judge's execute folder and observe the lengths of the `valout.#.txt` and `valerr.#.txt` - they are almost always 0.  I say _almost_ because if the validator generates enough output, buffers get flushed (see _Additional Context_ below).

**Expected behavior**: 
The `valout.#.txt` and `valerr.#.txt` files should contain the corresponding output and error outputs of the validator execution for each test case.

**Actual behavior**: 
The files are almost always empty.

**Environment**: 
All.

**Log Info**: 
**Screenshots**: 

**Additional context**:
The problem is related to the fact that the Buffered streams for each channel (stdout, stderr) of the validator are not flushed before the file contents are serialized.  When PC^2 saves the serialized file to each test case's respective files, the serialized files are empty.  A simple `flush()` of the `BufferedOutputStream`'s will fix the problem

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
Flush the validators stdout and stderr BufferedOutputStream buffers before serializing the files to disk.

### Issue which the PR addresses
Fixes #984 
### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 11
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

### Precise steps for _testing_ the PR 
1) Load a contest that has a custom output validator that produces output on stderr, for example.
2) Submit and judge a run.
3) Note that the valout.1.txt and/or valerr.1.txt are now not empty and contain the appropriate messages.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/core/execute/Executable.java [hunk 1]
```diff
@@ -1122,6 +1122,9 @@ protected boolean validateProgram(int dataSetNumber) {
 
 
             executionData.setvalidateTimeMS(System.currentTimeMillis() - startTime);
+            // be sure to flush before serializing.
+            stdoutlog.flush();
+            stderrlog.flush();
```
Comment (troy2914) [inline src/edu/csus/ecs/pc2/core/execute/Executable.java:1127]: is there a reason to not close those logs instead of flush'ing them?

Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/core/execute/Executable.java:1127]: Yes.  The finally {} clause below does that.

Comment (troy2914) [reply src/edu/csus/ecs/pc2/core/execute/Executable.java:1127]: why isn't the close done where the flush you added are.  There is no need to keep them open imo.  We are not doing flush's in other locations in Executable.

Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/core/execute/Executable.java:1127]: The issue is the `finally {}` has the `close()` calls for each stream.  If we close the files where the `flush()`'s are, then we'd close them twice, causing an `IOException `on the second time (in the `finally(){}`), and stack traces galore.  We could change the code so that it removes the `finally(){} `clause altoether, then duplicates the `try{close/close}catch(){}` in 2 places (once where the `flush()`'s were added, and once in the `catch()`).  The files **are** closed almost immediately by the `finally(){}` right after their corresponding files have been serialized.

Can you suggest a better and cleaner way?  Is there anything wrong with using `flush()`?  If so, why have it as part of the API?

**Review by troy2914 — APPROVED** [review]

**Review by kkarakas — APPROVED** [review]
Seems good!
