### PR TITLE
I1179 create zip for submit + CI's

### LINKED ISSUE #1179: CLICS 2023-06 submit service accepts files in wrong format
**Describe the issue**: 
When making a submission using the _CLICS 2023-06 API_ (eg. **pc2submit** Python command line utility), source files should be sent as a single _ZIP_ file encoded as _BASE64_.  The current implementation does not create a ZIP file, rather, it encodes each file as a separate BASE64 string and passes them as `CLICSFileReferenceObjects`.

In addition, the `pc2submit `Python utility should be fixed to put the source files for the submission in a single ZIP file, BASE64 encode that zip file, and pass that along to theserer

**To Reproduce**: 
Try to make a submission using a CLICS compliant command line submit utility that packages the source file(s) up as a single ZIP encoded as BASE64.

**Expected behavior**:
Submissions made to the CLICS submissions endpoint should accept a BASE64 encoded ZIP file containing the source code for the submission.

**Actual behavior**: 
Submissions made to the CLICS submissions endpoint will fail if the submission is a BASE64 encoded ZIP file containing the source code for the submission.

**Environment**: 
All.

**Log Info**:   

**Screenshots**: 
**Additional context**: 
This issue was pointed out indirectly by he DOMjudge folks.  They attempted to make a submission using the `pc2submit `utility we modified to be **CLICS 2023-06** compliant to the DOMjudge system.  It failed because the CLICS specification _unclearly_ indicates that the array of FILE included in the submission should be a single BASE64 encoded ZIP file.  The ZIP file contains the source code for the submission.

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
Accepts _CLICS 2023-06_ compliant submissions that include the source code in a single _BASE64_ encoded _ZIP_ file.  To maintain backward compatibility, we also accept a submission containing an array of BASE64 encoded files if the mime type of the FILE object is null or empty.

1. Move `getIFiles(byte []) `to `EventFeedUtilities `from `RemoteContestAPIAdapter`.  This method (now` public static`) converts a byte stream to a zip file and extracts the contents to a `List `of `IFile `objects.
2. Add additional `getIFiles(String)` method to `EventFeedUtilities `to accept a BASE64 encoded string consisting of a ZIP file, then decode that and call the `getIFiles(byte []) `method.
3. Change the CLICS 2023-06 submission service to accept the previous format (a list of BASE64 encoded files) for backward compatibility, and, also accept the correct format (BAS64 encoded ZIP file).  The distinction is made by looking at the mime type of the FILE objects passed.
4. Update the `pc2submit `command line utility to put the source files into a zip file, then encode that as base64 and send it off.  [This fix for `pc2submit `was provided by Nicky Gerritsen from the DOMjudge team.]
5. CI: Fix up the **PATCH** for the `ContestService `to set the thaw time.  Better logging.  Better messages returned to user.  Removed and handled outstanding TODO.

### Issue which the PR addresses
Fixed #1179 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 11
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Prerequisites:

- Python 3.10 (or greater) installed.
- Python `requests `package installed (`pip install requests`)

1. Load a new contest, such as `SumitHello` (`SumH`)
2. Start the **pc2server**
3. Start the **pc2admin**
4. Generate an event feeder account (**feeder1**).
5. Set the **SHADOW_PROXY_TEAM** permission on **feeder1**.
6. You should also set the _Enable CCS Test Mode_ setting on the **Configure Contest->Settings** tab under **Remote CCS Settings**.
7. Switch to the **Run Contest -> Runs** tab on the pc2admin.
8. Start the **pc2ef** and log in as **feeder1**.  
9. << I think there is a missing step here:  "Start the webserver" (jlc)
10. Start the contest.
11.  Open a command prompt window
12. Set the `SUBMITCREDENTIALS `environment variable to yes so that the submit command will prompt you for the team's user and password: `set SUBMITCREDENTIALS=yes`
13. Using the `bin/pc2submit` command line Python submit utility, make a submission: `python bin/pc2submit -y -u https://localhost:50443 -p B samps/src/hello.cpp`
14. The first time you do this, you may be prompted for your team and password (team1/team1)
15. The submission should succeed and you should see it appear on the Runs tab.
16. Select the submission and press "**View Source**" to confirm the source code is there.
17. This confirms that BASE64 encode ZIP file worked properly.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java [hunk 1]
```diff
@@ -607,24 +608,44 @@ public synchronized Response addNewSubmission(@Context HttpServletRequest servle
...
+            // Backward compatability test: If no mime property specified on the first file, then the CLICSFileReference's are
+            // actual files and not a zip file.  This is in here because initially, due to a misinterpretation of the CLICS
+            // 2023-06 specification, the command line submit utility (a.k.a. pc2submit) did not put the files in a zip file,
+            // rather, it created an array of base64 encoded file contents.  The CLICS spec has since been clarified but for now,
+            // we will still support the incorrect implementation as well as the correct one.
+            CLICSFileReference firstFile = files[0];
+            String mimeType = firstFile.getMime();
+
+            // TODO: deprecate this "if" part and leave the "else" part.  JB
+            if(mimeType == null || "".equals(mimeType)) {
```
Comment (nickygerritsen) [inline src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java:622]: A zip with an empty mime is also allowed according to the spec, I think that's not handled now?

Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java:622]: If you take a look at the comments in the PR, we are using the absence of the `mime-type `as a (temporary) indicator that the older version of `pc2submit `(`submit`) that did not zip the files is being used.  We are keeping this in for now, since some images out there (ie the **icpc2025** image) have the version of `pc2submit `that does not zip.  It also does not include the `mime-type`, so that's how we can tell (for now).  The only command line submit utilities that interact with the API are `pc2submit `(which has been fixed to add the `mime-type` and zip the files), and the playback utility, which is a private test utility.

After the next contest image cycle, we will remove the deprecated code and use the absence of the `mime-type` to indicate it's a zip file, as per the specification.

Comment (nickygerritsen) [reply src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java:622]: Makes sense!

**Review by SamanwaySadhu — APPROVED** [review]
Update steps to follow with how to set the credentials. Looks good otherwise!

File: src/edu/csus/ecs/pc2/clics/API202306/ContestService.java [hunk 2]
```diff
@@ -420,11 +421,22 @@ private Response HandleContestThawTime(SecurityContext sc, String contestId, Str
         // thaw time present, validate now
         GregorianCalendar thawTime = getDate(contestId, thawTimeValue);
         if (thawTime != null) {
-            // Set thaw time to this time.
-            // TODO: tell PC2 to thaw the contest at the given time.
-            controller.getLog().log(Log.WARNING, LOG_PREFIX + contestId + ": setting of contest thaw time is not implemented");
-            return Response.status(Status.NOT_MODIFIED).entity("Unable to set contest thaw time to " + thawTime.toString()).build();
+            Date thawDate = thawTime.getTime();
+            String thawStr = Utilities.getIso8601formatterWithMS().format(thawDate);
+            // get the local model's ContestInformation sincd we are modifying the thaw time
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/ContestService.java:426]: (trivial) typo:  "sincd" -> "since"

File: src/edu/csus/ecs/pc2/clics/API202306/ContestService.java [hunk 3]
```diff
@@ -420,11 +421,22 @@ private Response HandleContestThawTime(SecurityContext sc, String contestId, Str
...
+            ContestInformation ci = model.getContestInformation();
+            if (ci != null) {
+                // set the new start date/time into the ContestInformation
+                ci.setThawed(thawDate);
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/ContestService.java:430]: The preceding comment says we are setting the "new start date/time", but I don't think that's what's actually being set here.  (Copy/paste without an update?)

**Review by clevengr — COMMENTED** [review]
Reviewed `src/edu/csus/ecs/pc2/clics/API202306/ContestService.java`.  Minor (somewhat trivial) comments on what I think are incorrect comments in the code...

File: src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java [hunk 4]
```diff
@@ -607,24 +608,44 @@ public synchronized Response addNewSubmission(@Context HttpServletRequest servle
...
+                    // allow contestant submission of a zero length file.  This will generate a CE (hopefully).
+                    // if the following code is uncommented, the submission is not made and a 400 is returned to the submitter.
+                    // it appears that other CCS's allow zero length submissions.  *sigh* -- JB
+                    String fileData = file.getData();
+                    if(fileData == null || fileData.length() == 0) {
+                        // nice to put it in the log in case any questions come up.
+                        log.info(user + " POSTing empty source submission on behalf of team " + team_id);
+
+    //                    return Response.status(Response.Status.BAD_REQUEST).entity("no file data specified for " + fileName).build();
+                    }
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java:638]: PR #1173 (handle zero-length files in WTI) includes support for PC2 Admin configuration of "Allow zero-length files?".  Once that PR is approved and merged, the above block of code should probably check the `ContestInformation` configuration item to determine whether to allow a zero-length file.  (Unless of course the above block of code actually gets deprecated and eliminated, as suggested above...)

**Review by clevengr — COMMENTED** [review]
reviewed `src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java`.  Made one comment regarding handling of zero length files.

File: src/edu/csus/ecs/pc2/convert/EventFeedUtilities.java [hunk 5]
```diff
@@ -123,4 +131,88 @@ public static List<String> fetchRunFileNames(String dirname, String runId) {
...
+     * Get files from a zipfile's base64 encoded string data
+     *
+     * @param base64Data String comprising a zip file encoded as base64
+     * @return list of IFiles extracted from the input bytes
+     * @throws IllegalArgumentException from the base64 decoder on a data error
+     */
+    public static List<IFile> getIFiles(String base64Data) {
+
+        // use the decoder to both check the validity of, and to store, the byte data.
+        // this will throw an IllegalArgumentException if the data is basd
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/convert/EventFeedUtilities.java:144]: Typo in comment?  ("basd"?)

**Review by clevengr — COMMENTED** [review]
reviewed `src/edu/csus/ecs/pc2/convert/EventFeedUtilities.java`.  Made one comment on a trivial typo in a comment; otherwise looks good to me.

**Review by clevengr — COMMENTED** [review]
I've reviewed all the code changes.  Other than trivial issues like typos in comments (which I've noted separately), the code looks reasonable to me.  Proceeding to runtime testing.

**Review by clevengr — APPROVED** [review]
I completed a runtime test following the instructions in the PR (although the instructions were missing the information that I needed to have a valid `.netrc` file on my Windows box in order for `pc2submit` to work).   Since I was able to view the submitted source code in the admin, it appears that the PR works as intended, so I'm approving it.
