### PR TITLE
i_1171 Do not generate Honors rules for groups

### LINKED ISSUE #1171: After finalizing a contest, scoreboard client does not generate group results
**Describe the issue**: 
If a contest is "finalized", the scoreboard client is supposedto generate` results.tsv` and `results.csv` files for all teams, as well as for each group (site).  Since "Bill" "honors" rules were added, this has been broken and only the full scoreboard would generate the results files.  Any attempt to apply the "Bill" honors rules to a group with less than the total number medals being awarded will cause an exception (array out of bounds).

**To Reproduce**: 

1. Load a completed contest that has groups that contain less than the number of medals (usually 12).
2. Finalize the contest if it is not already finalized.
3. Start a scoreboard thick client.
4. Observe that only "`index.html`", "`results.tsv`" and "`results.csv`" are generated (for example).  There are no html files, tsv files or csv files for any of the groups that have less than the number of medals in the contest.

**Expected behavior**:
HTML files, csv files and tsv files should be generated for every non-hidden group.  

**Actual behavior**: 
Only the full contest html, csv and tsv files are generated.

**Environment**: 
All.

**Log Info**: 
```
250907 114125.714|FINE|AWT-EventQueue-0|log|Sending results output to C:\MyNetProjects\ICPC\pc2v9\results
250907 114125.715|WARNING|AWT-EventQueue-0|log|Exception generating scoreboard output 11
|java.lang.ArrayIndexOutOfBoundsException: 11
|    at edu.csus.ecs.pc2.exports.ccs.ResultsFile.createFileLines (ResultsFile.java:209)
|    at edu.csus.ecs.pc2.exports.ccs.ResultsFile.createTSVFileLines (ResultsFile.java:77)
|    at edu.csus.ecs.pc2.ui.board.ScoreboardCommon.generateResults (ScoreboardCommon.java:283)
|    at edu.csus.ecs.pc2.ui.board.ScoreboardView.generateOutput (ScoreboardView.java:295)
|    at edu.csus.ecs.pc2.ui.board.ScoreboardView.generateOutput (ScoreboardView.java:275)
|    at edu.csus.ecs.pc2.ui.board.ScoreboardView.access$0 (ScoreboardView.java:262)
|    at edu.csus.ecs.pc2.ui.board.ScoreboardView$PropertyChangeListenerImplementation.propertyChange (ScoreboardView.java:123)
|    at java.beans.PropertyChangeSupport.fire (PropertyChangeSupport.java:335)
|    at java.beans.PropertyChangeSupport.firePropertyChange (PropertyChangeSupport.java:328)
|    at java.beans.PropertyChangeSupport.firePropertyChange (PropertyChangeSupport.java:263)
|    at java.awt.Component.firePropertyChange (Component.java:8434)
|    at edu.csus.ecs.pc2.ui.StandingsTablePane.parseAndDisplay (StandingsTablePane.java:247)
|    at edu.csus.ecs.pc2.ui.StandingsTablePane$1.run (StandingsTablePane.java:261)
|    at java.awt.event.InvocationEvent.dispatch (InvocationEvent.java:311)
|    at java.awt.EventQueue.dispatchEventImpl (EventQueue.java:758)
|    at java.awt.EventQueue.access$500 (EventQueue.java:97)
|    at java.awt.EventQueue$3.run (EventQueue.java:709)
|    at java.awt.EventQueue$3.run (EventQueue.java:703)
|    at java.security.AccessController.doPrivileged (AccessController.java:-2)
|    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege (ProtectionDomain.java:74)
|    at java.awt.EventQueue.dispatchEvent (EventQueue.java:728)
|    at java.awt.EventDispatchThread.pumpOneEventForFilters (EventDispatchThread.java:205)
|    at java.awt.EventDispatchThread.pumpEventsForFilter (EventDispatchThread.java:116)
|    at java.awt.EventDispatchThread.pumpEventsForHierarchy (EventDispatchThread.java:105)
|    at java.awt.EventDispatchThread.pumpEvents (EventDispatchThread.java:101)
|    at java.awt.EventDispatchThread.pumpEvents (EventDispatchThread.java:93)
|    at java.awt.EventDispatchThread.run (EventDispatchThread.java:82)
```

**Screenshots**: 

**Additional context**:
"Bill" honors rules should not be applied to groups.  The fix is to avoid calculating these rules if a group scoreboard is being generated.

Possible Work-around:  Set any group that has < # medals in contest to "hidden"; in which case it will not attempt to generate a scoreboard.   For example, WF typically has about 20 or so "empty" groups that have no teams defined. (Guests, Sponsors, Judges, etc.).  If these are set to hidden, then the problem will not occur, however,  you must make sure that ALL of them have < # medals are hidden.

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
It makes no sense to apply WF honors rules for individual groups.  This PR avoids generating the honors rules results for groups.

### Issue which the PR addresses
Fixes #1171 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

Ubuntu 24.04

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
1. Load a completed contest that has groups that contain less than the number of medals (usually 12).
2. Finalize the contest if it is not already finalized.
3. Start a scoreboard thick client.
4. Observe that all "`index.html`", "`results.tsv`" and "`results.csv`" are generated for all non-hidden groups, even if the groups are empty.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/exports/ccs/ResultsFile.java [hunk 1]
```diff
@@ -172,8 +172,10 @@ public String[] createFileLines(IInternalContest contest, Group group, String re
         if (finalizeData == null) {
             finalizeData = GenDefaultFinalizeData();
         }
+        // Do not use Bill honors WF ranking rules for groups
+        boolean useHonorsRules = (group == null && finalizeData.isUseWFGroupRanking());
```
Comment (troy2914) [inline src/edu/csus/ecs/pc2/exports/ccs/ResultsFile.java]: this comment plus boolean name seem inconsistent.

**Review by kkarakas — APPROVED** [review]
LGTM!
