### PR TITLE
I1006 point scoring wti fixes

### LINKED ISSUE #1201: WTI should support Point-Scoring contests
**Describe the issue**: 
The WTI currently has a number of GUI components that do not work properly for a "Point-Scoring" contest.  These include:
- Notification of any "Yes" judgement results need to include the Score.
- The Runs page needs to include the Score (instead of just "Yes").
- The Scoreboard page needs to include the score.

**To Reproduce**: 
Run any contest that uses Point-Scoring; examine the above WTI GUI components.

**Expected behavior**: 
The components should reflect Point-Scoring information.

**Actual behavior**: 
The components do not reflect Point-Scoring information.

**Environment**: 
All.

**Additional context**: 
Verifying this issue (as well as testing any proposed fixes) requires the ability to run a Point-Scoring contest.   
@johnbrvc has created a test contest based on the WF49 Baku Codeforces Challenge.  The contest is here: https://github.com/icpcsysops/NAC2026/tree/main/contests/challenge_test
It loads and runs for PC2.  There is a single problem with 51 test cases and an output validator (JohnB converted the Codeforces output validator to generate CLICS output and exit codes).

His instructions for re-running this contest include:
```
...In the `challenge_test/replay/replay`folder I have all the files you should need to playback the 
submissions for the 1st, 2nd and 3rd place teams.  
There is a shell script (`doplayback.sh`) there that calls `ContestAPIReplay.py` (also in that directory).  
You may have to modify the `doplayback.sh` script to adjust the URL / credentials to connect to the CLICS API.  
I also have created 3 json files: `team99sub.json`, `team16sub.json` and `team57sub.json` which are the just 
submissions for the 1st, 2nd and 3rd place teams.  So if you do something like:

doplayback.sh team99sub.json

It will playback JUST team99's 24 submissions (making debugging a lot easier).  
BTW, I sped up the playback by a factor of 60 - you may want to adjust that too in the 
doplayback.sh script.  
```

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does
Updates multiple WTI-UI components to support point-scoring.  Specifically:
- adds `snakeyaml.jar` to the WTI project so that the WTI can recognize class references generated by SnakeYAMLLoader.  (See Issue #1208).
- Updates various classes to support point-scoring, including support for passing point-scoring information between PC2-API classes and the WTI Server which utilizes the PC2 API and between the WTI Server and the WTI-UI Angular code which displays the point-scoring information.
- adds support for SCOREBOARD_TYPE to WTI-UI Angular code.
- adds a `/scoreboardtype` endpoint to the WTI-API (Server), including adding appropriate @Json annotations to various classes.
- refactors multiple WTI-UI Angular classes, including adding a `ScoreboardModeService` class, plus reorganizing various Angular imports and provider-declarations.
- updates WTI-UI Angular classes for runs-page, scoreboard-page, and new-run-alert-page to support display of scores when the scoreboardType is point-scoring.
- adds a `utils/json-utils` package contain methods to ensure certain JSON objects are contained in arrays, and updates various classes to use `json-utils` to ensure that objects passed into WTI-UI Angular code are arrays in situations where the corresponding HTML templates expect Iterables.

### Issue which the PR addresses
FIxes #1201.  Also represents a partial fix for the larger Issue #1006.

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
-Windows 11, Eclipse Version: 2021-12 (4.22.0), Java version "1.8.0_381", Chrome Version 142.0.7444.60 (Official Build) (64-bit), Edge Version 144.0.3719.82 (Official build) (64-bit)

#### Setup
- **Download and unzip the PR distribution**.
- **Set up a contest configured for "point scoring"**.  You can configure your own point-scoring contest, load it into the PC2 Server, and submit multiple runs (both correct and incorrect) to it if desired, but a much easier approach is:
  - **Download the `NAC2024-Challenge.zip` file** from the [SysOps GDrive>CCS>PC2>profiles>pointScoringContest folder](https://drive.google.com/drive/folders/11i55pRYbh4rJB4Vj2pCAY2TkK9eINysB?usp=drive_link) into a separate folder.
  - **Unzip the downloaded file**.  This will give you a folder `profiles` and a separate file `profiles.properties`.
  - **Copy `profiles` and `profiles.properties`** into the root level of the unzipped PC2 distribution (from the PR) _before starting the PC2 Server_.

The following steps presume that you've chosen to use the `NAC2024Challenge` contest; if you set up a different point-scoring contest then adjust the steps as necessary...
- **Start the PC2 Server**, using a command like `./bin/pc2server --login s1 --contestpassword contest`.  This will automatically load the NAC2024Challenge contest into PC2.  This contest has 6 "point-scoring" problems, and has several runs already submitted to the contest.
- **Start a PC2 Admin**, using a command like `./bin/pc2admin --login r`.  
  - **Verify that you see six Challenge problems** on the `Configure Contest>Problems` tab.
  - **Verify that you see five runs** on the `Run Contest>Runs` tab, already submitted and judged.
  - **Verify that the standings show the following** on the `Run Contest>Standings` tab:  
```
1st: Brigham Young, Solved 2, Score 125.39
2nd: Columbia, Solved 1, Score 78.0; 
3rd: University of Minnesota, Solved 1, Score 25.6
4th and beyond:  all show Solved 0, Score 0.0
```
(For future reference, BYU is Team 25, Columbia is Team 1, and UMinn is Team 17.)
- **Unzip the WTI distribution** in the unzipped PR distribution PC2 "projects" folder.
- **Start the WTI Server**: `cd` into the resulting `WebTeamInterface` folder and use the command `./bin/pc2wti`.  (Ensure that the console window indicates "Started".)

#### Test Runs page and Scoreboard page
- **Open a browser and connect to the WTI Server**. Note that it is recommended to use "Incognito" (or "InPrivate") mode in the browser to ensure clean updates to downloaded WTI-UI Angular code.
- **Login as `team25`**, with password `team25`.  Note that this is the "current leader" in the contest (You can use other accounts as well, but note that some of the following instructions need to change correspondingly.  Note also that _some_ accounts may not have "joe passwords"; you'll have to look in the PC2 Admin to determine passwords for other accounts.)
- **Verify that the WTI Runs page matches the runs for Team 25 shown in the PC2 Admin** `Runs` tab; specifically, that Team 25 has two runs submitted, that both are accepted, that one has a score of 69.690 and the other has a score of 55.700.  Note also that 69.690 + 55.700 = 125.390.
- **Click on the "Scoreboard" link** in the WTI header.
- **Verify that the WTI Scoreboard matches the PC2 Admin** `RunContest>Standings` scoreboard, in terms of (1) number solved by each of the top three teams (count the "green bubbles" for each team, and (2) total score for each team.
- **Verify that the WTI Scoreboard matches the run results in the PC2 Admin**. In particular, for each of the top three teams, look at the `Runs` tab on the Admin and:
  - (1) for each problem solved by that team, find the highest score for a run for that problem;
  - (2) Verify that this is the score shown in the "green Yes bubble" for that problem.
  - (3) Verify that the "total submissions" listed in each bubble matches the total number of runs for that team for that problem.  (For example, Team 25 made just one submission on Problem C - Key Exchange, and got a score of 69.69 on it; the green bubble for that team and problem should show "1/69.690"
- **Click the "Logout" link** in the WTI header.
- **Log back into the WTI as "team1"** with password "team1".
- **Verify that the WTI Runs page matches the PC2 Admin runs** for Team 1.
- **Click on the "Scoreboard" link** in the WTI header.
- **Verify that the WTI Scoreboard matches the PC2 Admin** `RunContest>Standings` scoreboard.
- **Verify that the individual "problem data" in the WTI Scoreboard matches** the data in the PC2 Admin `Runs` table.
- **Hit F5** on the WTI browser.
- **Verify that the WTI Runs and Scoreboard pages still match** the data shown in the PC2 Admin.

#### Test New Submissions
- **Start the contest running**:  on the PC2 Admin "Configure Contest" screen, select "Times" and click "Start All".  (The contest as initially downloaded has been Stopped.)   Note that this is a very short contest -- just one hour long and with only 38 minutes remaining and a freeze-time of 20 minutes; if you plan to require more than a few minutes for testing you may want to use the Admin `Times` tab to edit the contest time (increase the contest length).
- **Login as team25**.
- **Click "Submit Problem"** on the "Runs" page.
- **Select a problem for which the team already has an accepted solution** (e.g. Key Exchange).
- **Select any language**.
- **Select any arbitrary text file as the "Main File"**  (it does not even have to be a legitmate source-code file; you're not going to actually compile or run it).
- **Click "Submit"**.
- **Verify that you get a green "Run has been submitted successfully!" pop-up**. (Note:  if you get a red "Bad Request" message instead, perhaps you forgot to start the contest running?  See also Issue #1174.)
- **Verify that the submitted run shows up on the Runs page** with a  blue "judgement" status of "Pending" and a score of "--".
- **Verify there is a "QUEUED_FOR_COMPUTER_JUDGEMENT" run** on the PC2 Admin `Run Contest>Runs` tab.
- **Edit the pending run status** on the PC2 Admin (by selecting the run and clicking "Edit"), as follows:
  - **Change "Status" to "Judged"**.
  - **Change "Score" to some real number** _which is less than the current highest score the team has earned for that problem_.
  - **Change "Judgement" to "Accepted"**.
  - **Check the "Notify Team" checkbox**.
  - **Click `Update`**.  You have effectively now "judged" the submission, without having to involve correct source code or a PC2 judge. 
- **Verify that on the WTI browser page you see**:
  - **a "Run Results Received" pop-up** listing the correct problem, a Judgement of "accepted", and the score value you entered.
  - **the "Pending" submission on the Runs page has changed to "accepted"** and shows the proper score.
- **Click the "Scoreboard" link** in the WTI header.
- **Verify that the SUBMISSION COUNT for the submitted problem has increased** (if you submitted for Problem C, it should have increased from 1 to 2), and also that the total Score for the team has NOT changed (because the score you gave the new submission was less than their best score).
- **Repeat the above process, submitting a new run for a team and judging it, but give the new submission a HIGHER score** than the highest score the team has received for the problem.
- **Verify that the WTI scoreboard shows the new, higher, score** underneath the individual problem, and that the team's total Score has increased based on the larger score you gave the new submission.

If all this goes correctly it demonstrates that the WTI updates to support Point Scoring work correctly,

#### Regression Testing (verifying new point-scoring code did not break "Pass/Fail" mode)
For a full, proper test of this PR, it is necessary to verify not just that the WTI properly supports Point Scoring (which is what the above tests do), but also that the PR changes do not _break_ anything regarding "Pass/Fail" contests.  Unfortunately, Issue #1204 makes it not possible to run a Pass/Fail contest using this branch (because this branch is "hard-coded" to assume a Point-Scoring contest because of #1204 and therefore can't be used to run a Pass/Fail contest).

The steps which _would have_ been done under this PR to demonstrate Regression Testing is correct have instead been copied into a comment in Issue #1204.  When THAT issue is resolved, and/or when the Point-Scoring branch (Issue #1006) is completed, care should be taken to do this "regression testing" -- that is, to make sure that the WTI works properly in a PC2 distribution which supports both Point-Scoring AND Pass/Fail contests. 
 

Also relevant for testing:  [Testing PC2 Point Scoring Contests](https://docs.google.com/document/d/1vUQCLh0_ek6alJ-x90Cvjq2uL42YWvXXbKxGgmMKNfg/edit?tab=t.0)

### CODE REVIEW

File: projects/WTI-UI/src/app/modules/scoreboard/components/scoreboard-page/scoreboard-page.component.ts [hunk 1]
```diff
@@ -139,15 +164,31 @@ export class ScoreboardPageComponent implements OnInit, OnDestroy, DoCheck {
...
 		
-		//get the "problem" array out of standingsHeader, or use an empty array ("[]"] if the problem array is null
-		const problems = standingsHeader.problem ?? [];
+		//create an array containing the problems from standingsHeader, or an empty array ("[]"] if the problem array is null
+		
+		const problemsRaw = standingsHeader.problem;
+
+		let problems: any[];
+
+		if (Array.isArray(problemsRaw)) {
```
Comment (johnbrvc) [inline projects/WTI-UI/src/app/modules/scoreboard/components/scoreboard-page/scoreboard-page.component.ts:184]: Didn't you create a magic function (ensureArray()) in json-utils previously to do this?  Or, is that not accessible from here?

**Review by johnbrvc — APPROVED** [review]
Reviewed code (FWIW), and had one minor comment (not a show stopper).  I'm not sure I fully understand the business with "SummaryRow" and "StandingsRecord" and the @jsonIgnore, but clearly, the author does.

All tests in the test procedure passed.   The entire testing process took about 15 minutes, including a build of the entire code base; very easy to test if you follow the directions.  (It also helps that I've done similar testing for the past month.)

For the record, I did run into the "Bad request"error doing my first submit because I forgot to start the contest (as mentioned in the PR test procedure.) 😉

File: projects/WTI-UI/src/app/modules/scoreboard/components/scoreboard-page/scoreboard-page.component.ts (hunk 1 above)
Comment (clevengr) [reply projects/WTI-UI/src/app/modules/scoreboard/components/scoreboard-page/scoreboard-page.component.ts:184]: Good catch; yes, that's essentially what json-utils.ensureArray() does.  The reason it wasn't used here is simply historical; this was the FIRST place I realized that I needed to do that function, so I coded it locally; later, I discovered there were other places that also needed the same conversion so I created json-utils.ensureArray() to handle that -- but I never went back and replaced this code with a call to that.  (It isn't accessible as-written, but it would be if a simple `import` was added.)   I'll try to remember to fix that as a "CI"... one of these days :)

**Review by kkarakas — COMMENTED** [review]
Code itself looks good to me.
