### PR TITLE
i680: implement filter WTI scoreboard by team's division

### LINKED ISSUE #680: WTI scoreboard is blank or shows all teams from all divisions
**Describe the issue**: 

A team WTI scoreboared with 3 divisions should show just
the team's divisions rankings/runs.  The scoreboard shows
all teams in all divisions.

Under certain cirsumstances the WTI scoreboard is blank
and throws an exception, found in the log and below
Log Info section.

**To Reproduce**: 

Use tc1 CDP at PacNWSpring2023/testcontest1/config

start server with tc1
start wti 
login as team101
click Scoreboard

**Expected behavior**: 

Should show only teams from D1

**Actual behavior**: 

Shows all 47 teams from all 3 divisions

**Environment**: 

Linux ip-172-16-1-46 5.15.0-1028-aws #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)

**Log Info**:  

The scorboard2's scoring settings for Minute penalty is null

Caused by: java.lang.NumberFormatException: Cannot parse null string
    at java.base/java.lang.Integer.parseInt(Integer.java:630)
    at java.base/java.lang.Integer.parseInt(Integer.java:786)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.getPropIntValue(DefaultScoringAlgorithm.java:248)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.getPenaltyPointsPerYesMinute(DefaultScoringAlgorithm.java:278)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.calcProblemScoreData(DefaultScoringAlgorithm.java:208)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.generateStandingsValues(DefaultScoringAlgorithm.java:947)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.getStandings(DefaultScoringAlgorithm.java:447)
    at controllers.ContestController.getStandings(Unknown Source)

**Screenshots**:  

**Additional context**:

### PR DESCRIPTION
**Pull request by lane55**
Added code to filter runs on WTI scoreboard for team to only show runs in the same division as the team.
In WTI, Will find all runs in the curernt team's division

### Description of what the PR does

If the following ini entry is in pc2v9.ini the WTI scoreboard should show
only teams in the same division as the logged in team.

From the logging it shows that the runs are restricted to the same division.
BUT the display still shows all runs from all divisions

ini entry is:
[server]
wtiBoardUseDivisions=Yes

Also assigns default scoring properties to properties to avoid NPE in DSA (PR 681)

### Issue which the PR fixes

#680 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Microsoft Windows [Version 10.0.19044.2130]

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Load tc1, submit a bunch of runs in different divisions

Add to pc2v9.ini in [server] section
wtiBoardUseDivisions=Yes

Start WTI, login as teams from different divisions,
select Scoreboard
teams on scoreboard should be in the same division as the logged in team

### Actual

The debugging shows that the teams are from the same division but
the display shows all runs from all divisions.

### Logging

  Shows for logged in teams the number of runs from their division

debug 22 XL useDivisionFilter is true
debug 22 XL debug 22 useDivisionFilter userLogin = team101
debug 22 XL debug 22 useDivisionFilter clientNumber = 101
debug 22 XL debug 22 useDivisionFilter clientId = TEAM101 @ site 1
debug 22 XL debug 22 useDivisionFilter total runs  = 42

debug 22 XL useDivisionFilter is true
debug 22 XL debug 22 useDivisionFilter userLogin = team801
debug 22 XL debug 22 useDivisionFilter clientNumber = 801
debug 22 XL debug 22 useDivisionFilter clientId = TEAM801 @ site 1
debug 22 XL debug 22 useDivisionFilter total runs  = 7

### CODE REVIEW

File: projects/WTI-API/src/main/config/WebServer.java [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 import java.net.URISyntaxException;
 import java.util.EnumSet;
+import java.util.logging.ConsoleHandler;
```
Comment (clevengr) [inline projects/WTI-API/src/main/config/WebServer.java:5]: This added import does not appear to be used anywhere, which will generate at least a warning, maybe an error, in Eclipse.  If there's no need for the import, please remove it.

File: projects/WTI-API/src/main/controllers/ContestController.java [hunk 2]
```diff
@@ -547,9 +561,11 @@ public Response getStandings(
 			synchronized (updateStandingsMutex) {
 				
 				// check if some event has occurred which could have changed the standings
+				wtiServerStandingsAreCurrent = false; // NEW - forcing to false so will recalculate for each user
```
Comment (clevengr) [inline projects/WTI-API/src/main/controllers/ContestController.java:564]: This is incredibly inefficient -- to the point where in some contests (like in ACPC) where there are thousands of users (yet no Divisions) this might completely overload the system.  I think forcing this variable false should at least be conditional on whether or not the .ini file contains `server.wtiBoardUseDivision`.

File: projects/WTI-API/src/main/controllers/ContestController.java [hunk 3]
```diff
@@ -566,7 +582,53 @@ public Response getStandings(
...
+
+						        Arrays.sort(keys);
+								xlog(logger, "debug 22   Scoring Properties, there are " + keys.length + " keys");
+
+						        for (String string : keys) {
+									xlog(logger, "debug 22      " + string + "='" + props.get(string) + "'");
+						        }
+						}
+						
+						props = DefaultScoringAlgorithm.getDefaultProperties();
```
Comment (clevengr) [inline projects/WTI-API/src/main/controllers/ContestController.java:600]: The above line is (should be) a very temporary fix.  As a result, it should at _least_ have a comment that indicates
- it is temporary.
- the issue which reports the underlying problem for which this is a temporary workaround.

File: projects/WTI-API/src/main/controllers/ContestController.java [hunk 4]
```diff
@@ -566,7 +582,53 @@ public Response getStandings(
...
+						xlog(logger, "debug 22  set Default Scoring Props for "+key);
```
Comment (clevengr) [inline projects/WTI-API/src/main/controllers/ContestController.java:601]: As noted in a previous review, the value of `key` in the above statement appears to be undefined.  Please either change it to whatever it was intended to be, or remove the statement.

File: projects/WTI-API/src/main/controllers/ContestController.java [hunk 5]
```diff
@@ -566,7 +582,53 @@ public Response getStandings(
...
+
+						
+						/**
+						 * Should we use filer by division logic to filter runs ?
```
Comment (clevengr) [inline projects/WTI-API/src/main/controllers/ContestController.java:605]: Please fix typo in the above statement:  "filer" should be "filter"?

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 2 above)
Comment (clevengr) [reply projects/WTI-API/src/main/controllers/ContestController.java:564]: On further review of code below, I see there IS a test for whether server.wtiBoardUseDivision is present in the .ini file.  I think that check should be done here as well...

File: projects/WTI-API/src/main/controllers/ContestController.java [hunk 6]
```diff
@@ -566,7 +582,53 @@ public Response getStandings(
...
+							Integer clientNumber = StringUtilities.getTeamNumber(userLogin);
+							xlog(logger, "debug 22 useDivisionFilter clientNumber = "+clientNumber);
+							ClientId clientId = new ClientId(internalContest.getSiteNumber(), Type.TEAM, clientNumber);
+							xlog(logger, "debug 22 useDivisionFilter clientId = "+clientId);
+							runs = ScoreboardUtilites.getRunsForUserDivision(clientId, internalContest);
+							
+						} else {
+							runs = internalContest.getRuns();
+						}
+						xlog(logger, "debug 22 useDivisionFilter total runs  = "+runs.length);
```
Comment (clevengr) [inline projects/WTI-API/src/main/controllers/ContestController.java:629]: I think outputting this message unconditionally, when the message refers to `useDivisionFilter`, is misleading.  I suggest either dropping the `useDivisionFilter` from the log message, or move the logging up under the "if" condition.

File: src/edu/csus/ecs/pc2/core/StringUtilities.java [hunk 7]
```diff
@@ -276,4 +276,25 @@ public static boolean getBooleanValue(String string, boolean defaultBoolean) {
         return value;
     }
     
+    /**
+     * get team number from login string.
+     * 
+     * @param user,
+     *            team login in form team#, team102
+     * @return null if no number found or number
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/StringUtilities.java:284]: The above comment doesn't make sense; please explain what "if no number found or number" is supposed to mean.

File: src/edu/csus/ecs/pc2/core/scoring/IScoringAlgorithm.java [hunk 8]
```diff
@@ -28,4 +29,20 @@ public interface IScoringAlgorithm {
...
+    /**
+ * Returns an XML description of the current contest standings.
+     * 
+     * @param theContest
+     *            A proxy object referencing the underlying model describing the contest
+     * @param properties
+     *            general and implementation specific settings.
+     * @param log
+     *            a logger, used to add info to the log file and window.
+     * @return An XML descriptor giving standings properties for each team
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/scoring/IScoringAlgorithm.java:42]: Please delete this extraneous comment (it is a duplicate of the line two lines below...)

File: src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java [hunk 9]
```diff
@@ -188,6 +190,95 @@ public static ScoreboardJsonModel createContestStandingsFromJSON(File jsonFile)
...
+        }
+        
+        String groupName = group.getDisplayName().trim();
+        
+        return getDivision(groupName);
+    }
+
+    public static String getDivision(String groupName) {
+
+        int idx = groupName.lastIndexOf('D');
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java:273]: It is very scary that we're putting something as "hard-coded and deeply hidden" as "Group names must end with Dx" into the core code.  At _least_ it seems like this should be flagged as something intended to be temporary, hopefully with a reference to an Issue number for fixing it.

File: src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java [hunk 10]
```diff
@@ -188,6 +190,95 @@ public static ScoreboardJsonModel createContestStandingsFromJSON(File jsonFile)
...
+     */
+    public static Run[] getRunsForUserDivision(ClientId clientId, IInternalContest contest) {
+
+        String division = getDivision(contest, clientId);
+        
+//        System.out.println("debug 22 getRunsForUserDivision for "+clientId+" div is "+division);
+
+        if (ClientType.Type.TEAM.equals(clientId.getClientType())) {
+
+            List<Run> teamRuns = new ArrayList<Run>();
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java:208]: `teamRuns` is a very misleading name for this variable -- the variable in fact is holding not just the runs for the specified team, but also all runs for other teams in the same division.  It seems like "divisionRuns" would be a better name.

File: src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java [hunk 11]
```diff
@@ -188,6 +190,95 @@ public static ScoreboardJsonModel createContestStandingsFromJSON(File jsonFile)
...
+
+    protected static boolean matchDivsion(IInternalContest contest, String inputDivision, ClientId submitter) {
+        
+          String division = getDivision(contest, submitter);
+          
+//          System.out.println("debug 22 matchDivsion  "+inputDivision+" vs "+division+" for "+submitter);
+          
+          if (inputDivision == null && division == null) {
+              return true;
+          } if (inputDivision == null) {
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java:240]: The code structure here is very misleading.  It _looks_ like the above line is intended to be an `else if`, but there's no `else` keyword.  As a result, the `if` represented on the above line is executed unconditionally (unless the return above is taken).  I suggest either adding an `else`, or adding a line break so it's clear what is intended.

File: src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java (hunk 9 above)
Comment (troy2914) [reply src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java:273]: it's not clear to mean why the code from the DSA that dealt with finding the division number was not re-used?
```
+        // TODO this bit should in the future can probably go away when divisions are supported better.
+        int lastFound = 0;
+        for (Group group : groups) {
+            // no reference to groups that should not be displayed on scoreboard
+            if (!group.isDisplayOnScoreboard()) {
+                continue;
+            }
+            Pattern pattern = Pattern.compile("D\\d+$");
+            Matcher matcher = pattern.matcher(group.getDisplayName());
+            if (matcher.find()) {
+                Integer found = Integer.parseInt(matcher.group(0).substring(1));
+                if (found.intValue() > lastFound) {
+                    lastFound = found.intValue();
+                }
+                divisionIndexHash.put(group, found);
+            }
+        }
+        divisionCount = lastFound;
```

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 2 above)
Comment (troy2914) [reply projects/WTI-API/src/main/controllers/ContestController.java:564]: I was concerned with that force execution also,  I agree it should be based on server.wtiBoardUseDivision.

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 3 above)
Comment (troy2914) [reply projects/WTI-API/src/main/controllers/ContestController.java:600]: imo,  an `if props == null`  should be added to that call.

**Comment by clevengr** [comment]
I have created a test plan wherein the "filter by divisions" operation appears to fail.  Here's the plan:
- Load PacNWTestContest1
- Edit the pc2v9.ini _for the WTI_ to include "**wtiBoardUseDivisions=Yes**"
- Start the WTI.
- From a browser, login as team 101 (this is the team "TODO" at the British Columbia - D1 site)
- Submit a "yes" run.
- Click the "Scoreboard" menu item on the WTI screen

Expected:  
- the WTI console logging shows "**debug 22 XL useDivisionFilter is true**"
- Team101 is in first place
- All other D1 teams are in 2nd place
- NO teams that are not in D1 are shown.

Actual:
- the WTI console logging (correctly) shows "**debug 22 XL useDivisionFilter is true**"
- Team101 is (correctly) in 1st place.
- All other teams are (correctly) in 2nd place.
- ALL teams (D1, D2, and D3) are shown (this is incorrect).

So, this test has already failed.  But there's more:

Continuing the test:
- Logout from the WTI, then login as team 151 (this is team "D2 Discrete Dummy Diabase" at the British Columbia D2 site).
- Submit a "yes" run.
- Click the "Scoreboard" menu item on the WTI screen.

Expected:  
- Team151 is in first place
- All other D2 teams are in 2nd place
- NO teams that are not in D2 are shown.

Actual:
- Team151 is in 1st place.
- All other teams are in 2nd place.
- ALL teams (D1, D2, and D3) are shown.
Note in particular that in this scenario _team 101 (TODO, Site BC D1) is shown on the scoreboard_ -- but they have "zero solved" (therefore they are somewhere down the 2nd-place rankings) _even though they show as having ONE SOLVED_ when they are logged in and look at the scoreboard.

File: projects/WTI-API/src/main/config/WebServer.java (hunk 1 above)
Comment (lane55) [reply projects/WTI-API/src/main/config/WebServer.java]: removed, pushed fix.

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 2 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java:565]: Adding conditional around wtiServerStandingsAreCurrent = false;

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 3 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java:596]: will add comment and conditional.

Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java:596]: > imo, an if props == null should be added to that call.

Add where?  In the current/PR code is there any possibility that the prop == null ?

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 4 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java]: debugging removed and pushed

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 5 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java:600]: rewrote comment/description of useDivisionFilter

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 6 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java]: It used to be in the useDivisionFilter  block, moved it down.

Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java]: rewrote the log now is:

Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java]: pushed

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 3 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java:596]: pushed new "temp" comment

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 5 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java:600]: pushed

File: src/edu/csus/ecs/pc2/core/StringUtilities.java (hunk 7 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/StringUtilities.java:284]: Changed to: @return null if no team number found or string after team is not a number.

File: src/edu/csus/ecs/pc2/core/scoring/IScoringAlgorithm.java (hunk 8 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/scoring/IScoringAlgorithm.java:40]: cleaned up

File: src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java (hunk 9 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java:273]: not aware of that code, until now.   No plans to use that code because the entire division/group is gong to be redesigned/written.   I will add a comment that the above is temporary and reference the issue added to redesign how divisions are done.    Added https://github.com/pc2ccs/pc2v9/issues/689 for this purpose.

Comment (lane55) [reply src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java:273]: > 
The whole D# is kludgy and should be temporary and will be done someday.

File: src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java (hunk 10 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java:208]: will rename, but they are teams' runs.

Comment (lane55) [reply src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java]: pushed

File: src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java (hunk 11 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/standings/ScoreboardUtilites.java]: reformatted and pushed

**Comment by lane55** [comment]
> I have created a test plan wherein the "filter by divisions" operation appears to fail. Here's the plan:
> Load PacNWTestContest1
> Edit the pc2v9.ini for the WTI t

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 2 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java]: > This is incredibly inefficient --

File: src/edu/csus/ecs/pc2/core/StringUtilities.java (hunk 7 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/StringUtilities.java]: pushed

File: src/edu/csus/ecs/pc2/core/scoring/IScoringAlgorithm.java (hunk 8 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/scoring/IScoringAlgorithm.java]: pushed

File: projects/WTI-API/src/main/controllers/ContestController.java (hunk 5 above)
Comment (lane55) [reply projects/WTI-API/src/main/controllers/ContestController.java]: rewrote comment/description of useDivisionFilter

**Review by troy2914 — APPROVED** [review]

**Review by clevengr — APPROVED** [review]

**Review by johnbrvc — APPROVED** [review]
