### PR TITLE
I1032: Configure Contest Identifier

### LINKED ISSUE #1032: There is no way to specify/configure the contest id (contest identifier)
**Describe the issue**: 
The current "contest id" is formed, by default, using the string "`Default-`" followed by a unique ID (element id), eg: `Default-2578644969309899578`.  There is no way for a remote user making use of the event feed endpoints to know what this ID is.  The newer CLICS specifications require a URL of the format: `.../contests/<contestid>/endpoint` where <`contestid`> is the contest Id.

**To Reproduce**:

1. Load a new contest, like **sumithello**
2. Start an event feeder client
3. Start the event feed.
4. Check out the contest Id in the event feeder log file.

**Expected behavior**: 
The contest id should come from the YAML (JSON) configuration files, and, if not specified there, use the contest short name,
eg **wf48astana**, **nac2024**, etc.  

**Actual behavior**: 
The contest id is quite random with the "`Default-`" prefix.

**Environment**: 
All.

**Work around**:
You can edit the profile name in the profiles tab to presumably change the contest id.

**Log Info**: 
Excerpt from Event Feeder log file indicating the contest id of: `Default-2578644969309899578`
```
250103 183030.972|INFO|AWT-EventQueue-0|log|Starting /contests web service
250103 183030.973|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/access web service
250103 183030.976|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/accounts web service
250103 183030.980|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/scoreboard web service
250103 183030.982|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/languages web service
250103 183030.984|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/teams web service
250103 183030.986|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/groups web service
250103 183030.987|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/organizations web service
250103 183030.990|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/judgement-types web service
250103 183030.994|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/clarifications web service
250103 183031.119|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/submissions web service
250103 183031.122|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/problems web service
250103 183031.127|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/judgements web service
250103 183031.129|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/runs web service
250103 183031.131|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/event-feed web service
250103 183031.133|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/state web service
250103 183031.135|INFO|AWT-EventQueue-0|log|Starting /contests/Default-2578644969309899578/awards web service
```

**Screenshots**: 

**Additional context**:   
See also: #823

### PR DESCRIPTION
**Pull request by SamanwaySadhu**
### Description of what the PR does
Updates Contest Identifier object of InternalContest with CLICS Contest ID (or name if ID not present) as well as Contest ID object of Profile.

### Issue which the PR addresses
Fixes #1032 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 10, Eclipse 2021-12 R, JDK 8u381 (1.8), C++ 13.2.0

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
- Run the Ant script build.xml in the pc2v9 project.
- Start a PC2 server.
- Start a PC2 Event Feeder (Generate one feeder account if not present).
- Click `View Event Feed`.
- The logs should now have the correct id from `contest.yaml` present

### CODE REVIEW

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 1]
```diff
@@ -548,13 +548,36 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
...
+                    "1) Atmost 36 characters in length,\n" + 
+                    "2) Consisting only of characters [`a`-`z`, `A`-`Z`, `0`-`9`, `_`, `-`, `.`],\n" + 
+                    "3) Do not start with `-` or `.`, and\n" + 
+                    "4) Not end with `.`"
+                );
+            }
+        }
+
+        // only if CLICS id is not present do we try older key `short-name`
+        if (StringUtilities.isEmpty(shortContestName)) {
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Should this be an else from the "if" above?

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 2]
```diff
@@ -885,6 +908,95 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
...
+     * Not ending with `.`
+     * @param shortContestName
+     */
+    private boolean isStringCLICSCompliant(String shortContestName) {
+        if (StringUtilities.isEmpty(shortContestName)) {
+            return false;
+        }
+
+        int shortContestNameLength = shortContestName.length();
+        if (shortContestNameLength > 36) {
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Define a constant for this (36).

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 3]
```diff
@@ -885,6 +908,95 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
...
 
+    /**
+     * Check if id is CLICS compliant i.e.
+     * length atmost 36,
+     * consisting only of characters [`a`-`z`, `A`-`Z`, `0`-`9`, `_`, `-`, `.`],
+     * Not starting with `-` or `.` and
+     * Not ending with `.`
+     * @param shortContestName
+     */
+    private boolean isStringCLICSCompliant(String shortContestName) {
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Maybe this should be in StringUtils or "someplace" else.  I'm not sure it belongs here.  However, I can be convinced to leave it hear, since this is going to be old code when we read configs from JSON files as per spec.  In that case, none of this will be used anyway.

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 4]
```diff
@@ -885,6 +908,95 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
...
+            return false;
+        }
+
+        int shortContestNameLength = shortContestName.length();
+        if (shortContestNameLength > 36) {
+            return false;
+        }
+
+        if (
+            !Character.isLetterOrDigit(shortContestName.charAt(0)) &&
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: I am not in love with all these: shortContestName.charAt(XXX) calls.  Maybe set a character variable to the element of interest and just compare against that.  It would make the code tighter and easier to read

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 5]
```diff
@@ -885,6 +908,95 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
...
+     * truncating length to 36 if more,
+     * replacing invalid characters with `_`
+     * @param shortContestName
+     */
+    private String makeStringCLICSCompliant(String shortContestName) {
+        if (StringUtilities.isEmpty(shortContestName) || isStringCLICSCompliant(shortContestName)) {
+            return shortContestName;
+        }
+        
+        if (shortContestName.length() > 36) {
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Change 36 to a constant.

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 6]
```diff
@@ -885,6 +908,95 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
...
+            !Character.isLetterOrDigit(shortContestName.charAt(0)) && 
+            shortContestName.charAt(0) != '_'
+            ) {
+            return false;
+        }
+
+        if (
+            !Character.isLetterOrDigit(shortContestName.charAt(shortContestNameLength - 1)) && 
+            shortContestName.charAt(shortContestNameLength - 1) != '_' && 
+            shortContestName.charAt(shortContestNameLength - 1) != '-'
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Maybe make up a method that check a char for one of letterdigit+_+-, since this condition is used in many places below.

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 7]
```diff
@@ -129,12 +129,12 @@ String getSnakeParserDetails(MarkedYAMLException markedYAMLException) {
     }
 
     @Override
-    public IInternalContest fromYaml(IInternalContest contest, String directoryName) {
+    public IInternalContest fromYaml(IInternalContest contest, String directoryName) throws Exception {
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Is there a reason for the "throws" ?  IIRC some of the fromYaml methods already did throw, but didn't specify it.  What's the reasoning for it here?  (I see you throw exceptions, that's fine, but why the clause - `fromYaml(IInternalContest contest, String directoryName, boolean loadDataFileContents)` already did a throw...?

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 8]
```diff
@@ -885,6 +908,95 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
...
+        int shortContestNameLength = shortContestName.length();
+        if (
+            !Character.isLetterOrDigit(shortContestName.charAt(0)) && 
+            shortContestName.charAt(0) != '_'
+            ) {
+                shortContestName = '_' + shortContestName.substring(1);
+        }
+
+        if (
+            !Character.isLetterOrDigit(shortContestName.charAt(shortContestNameLength - 1)) &&
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Put this stuff in a common method (the stuff that tests for digit/alpha/_/-

**Review by johnbrvc — COMMENTED** [review]
See the comments I left for the specific modules.

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 7 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: I believe that the problem here is that you added (around line 552) a series of statements that include `throw new Exception(...)`.  This causes Eclipse to (correctly) note that you haven't _handled_ the throwing of type `Exception`, and that one fix is to "Add a `throws Exception` to the method header.

However, that's not (IMHO) the proper fix.  Instead of adding the line `throw new Exception(...)`, you should use `throw new YamlLoadException(...)`.  Since `YamlLoadException` is already imported and is defined as `extends RuntimeException`, Eclipse will not flag this as an error (because Java does not require `RuntimeException`s to be caught -- note that there are MANY places in this class where methods `throw YamlLoadException`, and none of those methods have a `throws` clause in their header or a corresponding `try/catch` clause).

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 9]
```diff
@@ -548,13 +548,36 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
         loadDataFileContents = fetchBooleanValue(content, PROBLEM_LOAD_DATA_FILES_KEY, loadDataFileContents);
 
         String shortContestName = fetchValue(content, CLICS_CONTEST_ID);
-        // only if CLICS id is not present do we try the older short-name
-        if(shortContestName == null) {
+
+        // Check if id is CLICS compliant
+        if (!StringUtilities.isEmpty(shortContestName)) {
+            if (!isStringCLICSCompliant(shortContestName)) {
+                throw new Exception(
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Recommend changing this to `throw new YamlLoaderException`, and removing the `throws Exception` clause from the method header.

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 10]
```diff
@@ -2569,7 +2681,7 @@ public Problem[] getProblems(String[] contents, int defaultTimeOut, boolean load
     }
 
     @Override
-    public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, String directoryName) {
+    public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, String directoryName) throws Exception {
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: As noted above, remove the `throws Exception` clause and replace whatever statement is throwing `Exception` with a statement to `throw new YamlLoaderException(...)`.

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java [hunk 11]
```diff
@@ -257,9 +257,10 @@ public interface IContestLoader {
      * @param directoryName
      *            directory to load files from.
      * @return contest
+     * @throws Exception
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: This change shouldn't be necessary when the `throws Exception` statements in `ContestSnakeYAMLLoader` are replaced with `throws YamlLoaderException`.   This entire interface should be reverted.

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java [hunk 12]
```diff
@@ -257,9 +257,10 @@ public interface IContestLoader {
      * @param directoryName
      *            directory to load files from.
      * @return contest
+     * @throws Exception 
      *
      */
-    IInternalContest fromYaml(IInternalContest contest, String directoryName);
+    IInternalContest fromYaml(IInternalContest contest, String directoryName) throws Exception;
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Ditto above:  this change shouldn't be necessary when the `throws Exception` statements in `ContestSnakeYAMLLoader` are replaced with `throws YamlLoaderException`.   This entire interface should be reverted.

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java [hunk 13]
```diff
@@ -270,12 +271,13 @@ public interface IContestLoader {
      * @param loadDataFileContents
      *            true - load files, false do not load files (files considered external).
      * @return contest
+     * @throws Exception 
      */
-    IInternalContest fromYaml(IInternalContest contest, String directoryName, boolean loadDataFileContents);
+    IInternalContest fromYaml(IInternalContest contest, String directoryName, boolean loadDataFileContents) throws Exception;
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Ditto above.

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java [hunk 14]
```diff
@@ -270,12 +271,13 @@ public interface IContestLoader {
...
 
-    IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, String directoryName);
+    IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, String directoryName) throws Exception;
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Ditto above.

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java [hunk 15]
```diff
@@ -270,12 +271,13 @@ public interface IContestLoader {
...
 
-    IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, String directoryName, boolean loadDataFileContents);
+    IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, String directoryName, boolean loadDataFileContents) throws Exception;
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Ditto above.

File: src/edu/csus/ecs/pc2/shadow/IRemoteContestAPIAdapter.java [hunk 16]
```diff
@@ -33,8 +33,9 @@ public interface IRemoteContestAPIAdapter {
      * </pre>.
      * 
      * @return the configuration of a remote CCS contest
+     * @throws Exception 
      */
-    public RemoteContestConfiguration getRemoteContestConfiguration();
+    public RemoteContestConfiguration getRemoteContestConfiguration() throws Exception;
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/shadow/IRemoteContestAPIAdapter.java]: This shouldn't be necessary if the recommended fixes in `ContestSnakeYamlLoader` are implemented.

File: src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java [hunk 17]
```diff
@@ -63,7 +63,7 @@ public MockContestAPIAdapter(URL remoteURL, String login, String password) {
      * {@inheritDoc}
      * 
      */
-    public RemoteContestConfiguration getRemoteContestConfiguration() {
+    public RemoteContestConfiguration getRemoteContestConfiguration() throws Exception {
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java]: Ditto -- this change shouldn't be necessary.

File: src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java [hunk 18]
```diff
@@ -82,8 +82,9 @@ public RemoteContestConfiguration getRemoteContestConfiguration() {
      * @param configDirectory config directory for CDP
      * @param remoteConfigMap map to add to, if null creates a new Map
      * @return
+     * @throws Exception 
      */
-    protected Map<REMOTE_CONFIGURATION_ELEMENT, List<AbstractRemoteConfigurationObject>> loadFileCDPMap(File configDirectory, Map<REMOTE_CONFIGURATION_ELEMENT, List<AbstractRemoteConfigurationObject>> remoteConfigMap) {
+    protected Map<REMOTE_CONFIGURATION_ELEMENT, List<AbstractRemoteConfigurationObject>> loadFileCDPMap(File configDirectory, Map<REMOTE_CONFIGURATION_ELEMENT, List<AbstractRemoteConfigurationObject>> remoteConfigMap) throws Exception {
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java]: Change shouldn't be necessary.

File: test/edu/csus/ecs/pc2/convert/LoadRunsTest.java [hunk 19]
```diff
@@ -93,8 +93,9 @@ public void testLoadCDP() throws Exception {
      * @param contest
      * @param configDir
      * @return
+     * @throws Exception 
      */
-    private IInternalContest loadYaml(IInternalContest contest, String configDir) {
+    private IInternalContest loadYaml(IInternalContest contest, String configDir) throws Exception {
```
Comment (clevengr) [inline test/edu/csus/ecs/pc2/convert/LoadRunsTest.java]: This change shouldn't be necessary.

File: test/edu/csus/ecs/pc2/core/imports/clics/CLICSContestsTest.java [hunk 20]
```diff
@@ -83,7 +83,7 @@ public void testContestsElement() throws Exception {
 
     }
 
-    private IInternalContest loadContest(String cdpPath) {
+    private IInternalContest loadContest(String cdpPath) throws Exception {
```
Comment (clevengr) [inline test/edu/csus/ecs/pc2/core/imports/clics/CLICSContestsTest.java]: Change shouldn't be necessary.

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java [hunk 21]
```diff
@@ -3572,7 +3572,7 @@ public void testOne() throws Exception {
         yamlTestTeamDisplayOnBoard(dataDirName, teamDisplayString, expected);
     }
     
-    void yamlTestTeamDisplayOnBoard (String dirname, String teamDisplayString, String expectedString) {
+    void yamlTestTeamDisplayOnBoard (String dirname, String teamDisplayString, String expectedString) throws Exception {
```
Comment (clevengr) [inline test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java]: This change shouldn't be necessary.

File: test/edu/csus/ecs/pc2/imports/ccs/ICPCTSVLoaderTest.java [hunk 22]
```diff
@@ -172,8 +172,9 @@ public void testTeamNumberfromAccountsTSVFile() throws Exception {
      * @param contest
      * @param configDir
      * @return
+     * @throws Exception 
      */
-    private IInternalContest loadYaml(IInternalContest contest, String configDir) {
+    private IInternalContest loadYaml(IInternalContest contest, String configDir) throws Exception {
```
Comment (clevengr) [inline test/edu/csus/ecs/pc2/imports/ccs/ICPCTSVLoaderTest.java]: This change shouldn't be necessary.

**Review by clevengr — CHANGES_REQUESTED** [review]
I have reviewed all the changed files.  The addition of `throws Exception` clauses on multiple methods isn't necessary or appropriate; see my detailed explanation of why this is the case (and how to fix it) in the comments.  Other than that, and the comments that @johnbrvc made regarding isolating all the character-change code (which I agree with), the rest of the code looks reasonable. 

I still have to download and do a runtime test to verify things work as expected.

**Comment by clevengr** [comment]
When I follow the "Testing Instructions" in the PR, the very first instruction (`Run the Ant script build.xml in the pc2v9 project.`) fails to build and gives me the following error:
```
An internal error occurred during: "Launching pc2v9 build.xml".
Cannot invoke "org.eclipse.jdt.launching.IVMInstall.getLibraryLocations()" because "install" is null
```
However, running `package.xml` script _does_ allow me to build successfully.  I suppose this could be an issue in my Eclipse configuration, although the `package.xml` script invokes the `build.xml` script and both scripts match exactly what's in the Develop branch so I'm not sure what the problem is...

**Review by clevengr — COMMENTED** [review]
I made a run-time test of the PR.  I loaded two different contests using the Develop branch and verified that the Event Feed contains a long "pc2 contest id", like `Default-xxxxx`.  I then switched to the PR branch and reran the same two contests, verifying that the Event Feed now contains an id based on the "short-name" in the `contest.yaml` file.  Looks good to me.  Approval pending (waiting for code updates per comments.)

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 7 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 9 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 10 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java (hunk 11 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java (hunk 13 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java (hunk 12 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java (hunk 14 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java (hunk 15 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/shadow/IRemoteContestAPIAdapter.java (hunk 16 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/shadow/IRemoteContestAPIAdapter.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java (hunk 17 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java (hunk 18 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/shadow/MockContestAPIAdapter.java]: Fixed in latest commit

File: test/edu/csus/ecs/pc2/convert/LoadRunsTest.java (hunk 19 above)
Comment (SamanwaySadhu) [reply test/edu/csus/ecs/pc2/convert/LoadRunsTest.java]: Fixed in latest commit

File: test/edu/csus/ecs/pc2/core/imports/clics/CLICSContestsTest.java (hunk 20 above)
Comment (SamanwaySadhu) [reply test/edu/csus/ecs/pc2/core/imports/clics/CLICSContestsTest.java]: Fixed in latest commit

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java (hunk 21 above)
Comment (SamanwaySadhu) [reply test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java]: Fixed in latest commit

File: test/edu/csus/ecs/pc2/imports/ccs/ICPCTSVLoaderTest.java (hunk 22 above)
Comment (SamanwaySadhu) [reply test/edu/csus/ecs/pc2/imports/ccs/ICPCTSVLoaderTest.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 1 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 2 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 3 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 4 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 5 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 6 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 8 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: Fixed in latest commit

**Comment by SamanwaySadhu** [comment]
> When I follow the "Testing Instructions" in the PR, the very first instruction (`Run the Ant script build.xml in the pc2v9 project.`) fails to build and gives me the following error:
> 
> ```
> An internal error occurred during: "Launching pc2v9 build.xml".
> Cannot invoke "org.eclipse.jdt.launching.IVMInstall.getLibraryLocations()" because "install" is null
> ```
> 
> However, running `package.xml` script _does_ allow me to build successfully. I suppose this could be an issue in my Eclipse configuration, although the `package.xml` script invokes the `build.xml` script and both scripts match exactly what's in the Develop branch so I'm not sure what the problem is...

@clevengr  I don't see this in my machine. However, in my case a few JUnits fail when I try to build it locally but through the Github CI everything passes.

File: src/edu/csus/ecs/pc2/core/StringUtilities.java [hunk 23]
```diff
@@ -13,14 +13,15 @@
...
 
-    /**
-     *
-     */
     private static final long serialVersionUID = -4197938292232525730L;
     /**
      * A constant containing three dots.
      */
     private static final String ELLIPSIS = "...";
+    /**
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/core/StringUtilities.java:21]: Update copyright to 2025.

File: src/edu/csus/ecs/pc2/core/StringUtilities.java [hunk 24]
```diff
@@ -505,4 +506,86 @@ else if (lastNumericCompare == 0)
         else
             return aLength - bLength;
     }
+
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/core/StringUtilities.java:509]: Again, I'm not 100% certain this is where these routines belong, since we really don't have a "ClicsUtils", and this is very specific string checking, so I think it's OK for now.  This will eventually be deprecated when we read the configuration from JSON files anyway.  No reply necessary.

**Review by johnbrvc — COMMENTED** [review]
Code reviewed and it looks OK to me.   Now I just have to test it.

File: src/edu/csus/ecs/pc2/core/StringUtilities.java (hunk 23 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/core/StringUtilities.java:21]: Fixed in latest commit

File: src/edu/csus/ecs/pc2/core/StringUtilities.java (hunk 24 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/core/StringUtilities.java:509]: Perhaps we SHOULD have a 'ClicsUtils' class? Or a 'Clics' package?

**Comment by johnbrvc** [comment]
> > When I follow the "Testing Instructions" in the PR, the very first instruction (`Run the Ant script build.xml in the pc2v9 project.`) fails to build and gives me the following error:
> > ```
> > An internal error occurred during: "Launching pc2v9 build.xml".
> > Cannot invoke "org.eclipse.jdt.launching.IVMInstall.getLibraryLocations()" because "install" is null
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, running `package.xml` script _does_ allow me to build successfully. I suppose this could be an issue in my Eclipse configuration, although the `package.xml` script invokes the `build.xml` script and both scripts match exactly what's in the Develop branch so I'm not sure what the problem is...
> 
> @clevengr I don't see this in my machine. However, in my case a few JUnits fail when I try to build it locally but through the Github CI everything passes.

See https://github.com/pc2ccs/pc2v9/issues/888 for an explanation (tl;dr;)

**Review by johnbrvc — APPROVED** [review]
Seems to work as advertised.
I think we do have to create another issue though to allow modification (and display) of the current contest id.  Right now, the only way to see what the contest ID is to look at one of the Reports, such as the "Contest XML" report.  It would be nice if it showed the contest ID on the Profiles tab and perhaps the Settings tab.  In addition, when you "Clone" a profile, a new ID is automatically created by the clone process called: "Copy-<big long unique ID".  Maybe you should be able to specify the ID of the "new" cloned contest on the clone contest dialog.  Also, a reason to be able to change the contest ID from the GUI: on the Profiles tab and possibly on the Settings tab.  I will file a new issue for this since we do not need this for NAC or WF since we do not use multiple profiles in the same contest.

**Comment by johnbrvc** [comment]
@clevengr Is there anything left that has to change before this can be approved?  I tested and approved it.  It appears as though you reviewed it and tested it, are we waiting for something before it can be approved?

**Review by clevengr — APPROVED** [review]
I reiterate my suggestion that maybe, given the number of "Clics Utilities" introduced in this PR, along with the likelikhood that we're going to be doing  more and more implementation of "CLICS support" in the future, the utilities introduced here should be put into a separate class, maybe in a package named, say, `Clics`.  But while I hate to see things added without consideration of the longer-term, it doesn't rise to the level of _needing_ to be done now -- so I'm marking this "Approved".

**Comment by johnbrvc** [comment]
> I reiterate my suggestion that maybe, given the number of "Clics Utilities" introduced in this PR, along with the likelikhood that we're going to be doing more and more implementation of "CLICS support" in the future, the utilities introduced here should be put into a separate class, maybe in a package named, say, `Clics`. But while I hate to see things added without consideration of the longer-term, it doesn't rise to the level of _needing_ to be done now -- so I'm marking this "Approved".

I agree, in fact, I do have such a class for each of the CLICS API packages called JSONXXXXUtilities.java.  XXXX = api version.  The problem, of course is, this is different for each API version.  Our ContestSnakeYAML loader is API >= 2022-07 aware, meaning it uses the rules for 2022-07 and above for ID's (until someone decides to change what is a valid ID).  So, I suppose we could stick such a routine in ecs/pc2/clics/API202306/JSON202306Utilities.java, and then reference that package in ContestSnakeYAML loader to verify the ID?  We can discuss this and decide if we should create an issue.  I'm fine leaving it as-is for now.
