### PR TITLE
remember when we are already answering a clar

### LINKED ISSUE #493: Clarification gets stuck in BEING ANSWERED state
Thank you for working to help us improve PC^2!  
Please fill in the following fields in order to help us understand what issue you are reporting.

**Describe the issue**: 
It has been observed on the KSA (ACPC) contest that a clarification was in BEING ANSWERED state when no judge was
answering it.  This led to the clarification being stuck.  Attempts to edit the clarification from Administrators failed since
the Edit Clarification function is not implemented. 

**To Reproduce**: 
Can not reproduce, but the problem was observed.  It may have to do with the fact that it was observed on a multi-site
contest and some of the sites were trying to send to other sites that were not there.  (The sites were removed prior to contest
start, but the server was not restarted).  The logs show the servers can't be reached to send messages related to the
Clarification.  This could be a contributing factor.

**Expected behavior**: 
Clarifications should not be marked as BEING ANSWERED if no on is currently answering it.

**Actual behavior**: 
A clarification was marked as BEING ANSWERED yet no one was answer it.

**Environment**: 
Version 9.8build 20220713 (Wednesday, July 13th 2022 15:07 UTC) build 6258~develop
Java version 11.0.15
OS: Linux 5.13.0-1031-aws (amd64)
Ubuntu 20.04

**Log Info**: 
```
220715 084938.153|INFO|Thread-73648|log|sendToRemoteServer SERVER0 @ site 13 at 13 Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111492 SERVER0 @ site 10 -> SERVER0 @ site 13 null
220715 084938.153|SEVERE|Thread-73648|log|Unable to send packet to site 13 (SERVER0 @ site 13)Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111492 SERVER0 @ site 10 -> SERVER0 @ site 13
220715 084938.153|INFO|Thread-73648|log|sendToRemoteServer SERVER0 @ site 11 at 11 Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111493 SERVER0 @ site 10 -> SERVER0 @ site 11 null
220715 084938.153|SEVERE|Thread-73648|log|Unable to send packet to site 11 (SERVER0 @ site 11)Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111493 SERVER0 @ site 10 -> SERVER0 @ site 11
220715 084938.153|INFO|Thread-73648|log|sendToRemoteServer SERVER0 @ site 12 at 12 Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111494 SERVER0 @ site 10 -> SERVER0 @ site 12 null
220715 084938.154|SEVERE|Thread-73648|log|Unable to send packet to site 12 (SERVER0 @ site 12)Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111494 SERVER0 @ site 10 -> SERVER0 @ site 12
220715 084938.154|INFO|Thread-73648|log|sendToRemoteServer SERVER0 @ site 14 at 14 Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111495 SERVER0 @ site 10 -> SERVER0 @ site 14 null
220715 084938.154|SEVERE|Thread-73648|log|Unable to send packet to site 14 (SERVER0 @ site 14)Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111495 SERVER0 @ site 10 -> SERVER0 @ site 14
220715 084938.154|INFO|Thread-73648|log|sendToRemoteServer SERVER0 @ site 13 at 13 Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111496 SERVER0 @ site 10 -> SERVER0 @ site 13 null
220715 084938.154|SEVERE|Thread-73648|log|Unable to send packet to site 13 (SERVER0 @ site 13)Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111496 SERVER0 @ site 10 -> SERVER0 @ site 13
220715 084938.154|INFO|Thread-73648|log|sendToRemoteServer SERVER0 @ site 12 at 12 Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111497 SERVER0 @ site 10 -> SERVER0 @ site 12 null
220715 084938.154|SEVERE|Thread-73648|log|Unable to send packet to site 12 (SERVER0 @ site 12)Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111497 SERVER0 @ site 10 -> SERVER0 @ site 12
220715 084938.154|INFO|Thread-73648|log|sendToRemoteServer SERVER0 @ site 13 at 13 Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111498 SERVER0 @ site 10 -> SERVER0 @ site 13 null
220715 084938.154|SEVERE|Thread-73648|log|Unable to send packet to site 13 (SERVER0 @ site 13)Packet[CLARIFICATION_SUBMISSION_CONFIRM] #111498 SERVER0 @ site 10 -> SERVER0 @ site 13
```

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.

**Additional context**: please add any other context about the issue here.

### PR DESCRIPTION
**Pull request by troy2914**
fixes #493

to test:
./bin/pc2reset
./bin/pc2server --login s1 --contestpassword contest --load samps/contests/sumitMTC/config
./bin/pc2admin --login r
start the contest
./bin/pc2team --login 1
submit a general clar and a sumit clar
./bin/pc2judge --login j10

play with answering either clar.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java [hunk 1]
```diff
@@ -1114,7 +1130,24 @@ protected void requestSelectedClarification() {
...
             ElementId elementId = clarificationTable.getElementIdFromTableRow(selectedIndexes[0]);
             Clarification clarificationToAnswer = getContest().getClarification(elementId);
-
+            if (elementId.equals(lastAnswered)) {
+                // try to make it visible
+                answerClarificationFrame.setVisible(true);
+                return;
+            }
+            if (lastAnswered != null) {
+                int showConfirmDialog = JOptionPane.showConfirmDialog(getParentFrame(), "You are already answering a clar, do you want to return to that one (YES) or start answering the new one (NO)", "Already answering a Clarifition", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null);
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java:1139]: YES == Cancel, Maybe should only have Yes and Cancel; change Yes to switch to new clar Cancel keeps?

**Review by johnbrvc — CHANGES_REQUESTED** [review]
Just the one dialog button thing.  Otherwise it works.

File: src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java (hunk 1 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java:1139]: I agree with JohnB; it works but I think the message to the user is slightly confusing.  For example, selecting "No" to cause it to move to the new clar is a bit unintuitive.

I would suggest what JohnB said:  change the dialog to have just two buttons, "Yes" and "Cancel", and change the dialog message to say:
```
You are asking to answer a new clarification, but you already have a clarification checked out for answering.  \n
If you want to give up the previous clarification and switch to answering the new one, click "Yes"; \n
otherwise, click "Cancel" and go back to answering the previous clarification.
```

Or an alternative would be to provide _three_ buttons:  `Switch to New Clar`, `Return to Previous Clar`, and `Cancel` (with appropriate adjustments to the suggested dialog message).

In either case I'd also like to see ToolTips added to the buttons explaining in more detail what they do.

**Review by clevengr — CHANGES_REQUESTED** [review]
See the comment following JohnB's comment.

File: src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java (hunk 1 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java:1139]: I'm not sure about the 3 button alternative.  What exactly would cancel do in that case?  Would it close the currently open clar and just return to the list of all clars, with none selected?  (That may surprise the user, since "cancel" is supposed to bring you back to where you were with things unchanged - in this case, it would CLOSE the already open answer clar dialog.  Not what you would expect.  Surprise!)   That's why the 2 button Yes/Cancel solution is probably the clearest.  IMHO.

Comment (troy2914) [reply src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java:1139]: Perhaps you noticed I was using JOptionPane?  I can't control what the buttons say or their tooltips.
I can do a Yes/No solution.   With JohnC's message.

File: src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java [hunk 2]
```diff
@@ -1114,7 +1130,29 @@ protected void requestSelectedClarification() {
...
+                return;
+            }
+            if (lastAnswered != null) {
+                int showConfirmDialog = JOptionPane.showConfirmDialog(getParentFrame(), "You are asking to answer a new clarification, but you already have a clarification checked out for answering.\n" + //
+                        "\n" + //
+                        "If you want to give up the previous clarification and switch to answering the new one, click \"Yes\";\n" + //
+                        "\n" + //
+                        "otherwise, click \"No\" and go back to answering the previous clarification.\n" + //
+                        "", "Already answering a Clarifition", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null);
+                if (showConfirmDialog == JOptionPane.NO_OPTION) {
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java:1145]: The above line causes a bug: if the user hits the "Closing X" on the dialog frame, the value returned from the `showConfirmDialog()` call is `-1` (undefined).  Since `-1 != JOptionPane.NO_OPTION`, hitting the "Close X" is the same thing as saying "Yes (I want to switch)" -- and so it switches to the new clar (which would, I think, surprise the user).  The test here should be `showConfirmDialog != JOptionPane.YES_OPTION`.

To reproduce:  go through the "Steps to test the PR", including checking out one clar for answering and then attempting to check out a second clar for answering.  When the following dialog appears:

image

hit the "X" in the upper right corner.

Expected result:   no change in the state of the system.
Actual result:  judging will switch to the new clar.

Also: I think the message in the title of the dialog should say "Clarification" instead of "Clarifition"...

Comment (troy2914) [reply src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java]: good catches.

Comment (troy2914) [reply src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java]: fixed both items.

**Review by clevengr — CHANGES_REQUESTED** [review]
See the Conversation Comments for a bug I found (hitting the "Closing X" switches clars) which needs to be fixed.

Also, @troy2914 made a comment `Perhaps you noticed I was using JOptionPane? I can't control what the buttons say ....`

Yes, you can -- you just called the wrong JOptionPane method for doing it.  If you replace your call with the following code:

```
 String [] options = {"Yes, I really want to change clars", "No, I'll stick with the previous clar"};
 String message = 
   "You are asking to answer a new clarification, but you already have a clarification checked out for answering." + //
   "\n" + //
   "If you want to give up the previous clarification and switch to answering the new one, click \"Yes\";" + //
    "\n" + //
   "otherwise, click \"No\" and go back to answering the previous clarification."  ;

 int showConfirmDialog = JOptionPane.showOptionDialog(getParentFrame(), message, "Switch to different Clarification?",
   JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]) ;
```

then you get a nice little dialog with custom-labeled buttons, like the following:

image

You can even also set the ToolTips for the buttons if you declare JButton objects instead of Strings...  (not that I think that's critical since the buttons pretty much say what a ToolTip would probably say...)

Although I don't think it's a requirement, feel free to grab the above code and add it... 

But I do think the "X" issue needs to be fixed...

**Review by clevengr — APPROVED** [review]
I would like to see the buttons relabeled with improved text such as the suggestion I made on my previous review.  However, I don't see that as a reason not to approve the PR, so I'll submit that as a new Issue.

**Review by johnbrvc — APPROVED** [review]
Look OK to me.
