### PR TITLE
I448 wti general clar category

### LINKED ISSUE #448: Using WTI when submit a clar there is no General category
**Describe the issue**: please provide a clear and concise description of what the bug is.  

One can select all problems defined in contest for a clar but no General category is present.

**To Reproduce**: please describe, in order, the steps to reproduce the behavior:

Start server
Start WTI
Login as team 
Submit a clar 

**Expected behavior**: please provide a description of what you *expected* to happen when you took the above steps:  

Team able to select General category

**Actual behavior**: please describe what _actually_ happened when you took the above steps:

No General category

**Environment**: please complete the following information:
 - OS name and version under which the issue was detected (e.g. Windows 10 or Ubuntu 18.04):
 - PC2 Version (e.g. 9.7.0):   
 - Browser (if the bug is related to web-based team clients) (e.g. _Chrome Version 75.0.3770.142_ or _Safari Version 11.1.2_):

**Log Info**:  PC^2 generates logs (in the **logs** folder for client modules; under the **profiles** folder for the PC2 Server).  Please review the relevant logs and provide copies of them as attachments -- particularly if the logs show Exceptions being thrown.  

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.

**Additional context**: please add any other context about the issue here.

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does
Adds support for "General" clarifications to the WTI.  Specifically, the following four files were changed:
- `WTI-UI/src/app/modules/clarifications/components/new-clarification/new-clarification.component.html`
  - `allowGeneral` was set to `true`, allowing this component to tell its child `ProblemSelectorComponent` to include "General" in the dropdown list of problems on the New Clarification page's `Select Problem` list.
- `/pc2v9/src/edu/csus/ecs/pc2/api/ServerConnection.java`
  - Added documentation to method `submitClarification(IProblem problem, String question)` explaining some subleties associated with the inclusion of `Category`s as a type of "problem".
  - No logic changes were made to this file.
- `WTI-API/src/main/controllers/MainController.java`
  - Added substantial documentation explaining the addition of `Category`s to the input parameters to method `findProblem(IProblem[] problems, String nameOfProblem)`.  
  - Some very minor reformatting of code; no logic changes.
- Updated `WTI-API/src/main/controllers/TeamsController.java` method `SubmitClarification(ServerConnection teamConn, SubmitClarificationRequestModel clar)` to fetch problem `Category`s from the PC2 Server (via the PC2 API) and include the returned `Category` values in the list of "problems" to be searched for a match with the "problem" (which could be a `Category`) specified in the submitted clar request. 

### Issue which the PR addresses
Fixes #448 

### Environment in which the PR was developed
Windows 11, Eclipse Version: 2020-12 (4.18.0) with Java version "1.8.0_271"

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
- Start a PC2 Server, loading a contest with multiple problems (e.g. --load sumithello). 
  - Do NOT start the contest yet (sumithello by default does not automatically start).
  - Be sure the contest you start has a Scoreboard2 account (sumithello does).
- Start the WTI Server.
- Open a browser and connect to the WTI Server (e.g. at http://localhost:8080 which is the default.)
- Login as a team.
- Verify:
  - Clicking `Runs>Submit Problem>Select Problem` does NOT show any problems (because the contest hasn't been started).
  - Clicking `Clarifications>New Clarification>Select Problem` shows "General" but does not show any actual problems (again, because the contest hasn't started).
- Start a PC2 Admin.
- Start the contest.
- On the WTI, verify:
  - Selecting `Runs>Submit Problem>Select Problem` now shows the contest problems (but does NOT show "General").
  - Selecting `Clarifications>New Clarification>Select Problem` shows all the contest problems AND shows "General".
- Select a problem (not "General") and submit a clarification request for that problem.
- On the Admin, verify that the clarification is received.
- On the Admin, answer the clarification but do NOT check "Send to all teams".
- On the WTI team, verify that the reply was received.
- On the WTI team, submit another clarification, selecting "General".
- On the Admin, verify that the clarification was received and is marked "General" under the "Problem" column.
- On the Admin, answer the "General" clar, and DO check the box "Send to all teams".
- On the WTI team, verify that the answer was received.
- Open a separate browser and login as a *different* team.
- Verify that the new team can see the answer to the "General" clarification that was sent to all teams.

### CODE REVIEW

File: projects/WTI-API/src/main/controllers/MainController.java [hunk 1]
```diff
@@ -14,6 +14,7 @@
 import edu.csus.ecs.pc2.api.IProblem;
 import edu.csus.ecs.pc2.api.ServerConnection;
 import edu.csus.ecs.pc2.api.implementation.Contest;
+import edu.csus.ecs.pc2.api.implementation.ProblemImplementation;
```
Comment (johnbrvc) [inline projects/WTI-API/src/main/controllers/MainController.java]: This should be removed as it is not used (Eclipse flags it as a warning).

**Review by johnbrvc — COMMENTED** [review]
Other than the warning, (which will not prevent approval), this looks good to me.
I have tested this "under fire" using the _WF Online Practice contest_ and it works.

There is a "however", however.   It seems the clarification filtering does not list "**General**" as one of the things that can be filtered on.   That is, I submitted a "**General**" clarification using team 151.  I then answered that clarification from the administrator.  Team 151 received the reply.  I then tried to filter on just "**General**" and that was not one of the choices in the filter pull-down.

I am not sure this is a show-stopper, or should prevent the approval of this PR.  Maybe a new issue for that?  Although, it seems like it should be an easy fix - that is, construct the list of filters similar to the way the list is constructed for finding the clarification in `TeamsController`.

Other than that I see no issues.

File: projects/WTI-API/src/main/controllers/MainController.java (hunk 1 above)
Comment (clevengr) [reply projects/WTI-API/src/main/controllers/MainController.java]: I know how this happened.  Originally the lengthy comments I had added included a javadoc reference like `{@link ProblemImplementation}`.  This caused Eclipse to add the import (since it would be needed by javadoc).  Later, in an effort to reduce the complexity of the comments, I removed some of those "{@link...}" references. However, I didn't notice that the import still remained.  I just pushed a commit that removes it.

**Comment by clevengr** [comment]
I pushed commits that fix the "unused import" and the "can't filter on 'General' clarifications" issues.

File: projects/WTI-UI/src/app/modules/clarifications/components/clarifications-page/clarifications-page.component.ts [hunk 2]
```diff
@@ -66,7 +66,7 @@ export class ClarificationsPageComponent implements OnInit, OnDestroy {
     if (filterParams.recipient === 'all') { filtered = filtered.filter(x => (x.recipient === 'All' || x.recipient === "No Answer Yet")); }
     if (filterParams.recipient === 'some') { filtered = filtered.filter(x => (x.recipient === 'Some' || x.recipient === "No Answer Yet")); }
     if (filterParams.recipient === 'team') { filtered = filtered.filter(x => (x.recipient === 'My Team' || x.recipient === "No Answer Yet")); }
-    if (filterParams.problem) { filtered = filtered.filter(x => x.problem === filterParams.problem); }
+    if (filterParams.problem) { filtered = filtered.filter(x => x.problem?.toLowerCase() === filterParams.problem.toLowerCase()); }
```
Comment (kkarakas) [inline projects/WTI-UI/src/app/modules/clarifications/components/clarifications-page/clarifications-page.component.ts:69]: So the problem for x (clarification) is undefined when the clarification is for general?

**Review by kkarakas — APPROVED** [review]
I did a code review, looks good.
