### PR TITLE
I820: Changed JRadioButton, pickFileButton text from 'Select' to 'Select...'

### LINKED ISSUE #820: All "Select" JButtons should show have a title of "Select..."
**Describe the issue**: 

There are a number of JButtons in the UI that have the title "Select"

To be consistent all JButton labels with "Select" should be changed
to "Select..."

Search source code for "Select" text for JButton

**To Reproduce**: 

start server
start Admin
Search for buttons with only "Select"

**Expected behavior**: 

All JButton with Select should show Select...

**Actual behavior**: 

Many JButton with Select do not show Select...

**Environment**: 

All.

**Log Info**:  

**Screenshots**:  

**Additional context**:

### PR DESCRIPTION
**Pull request by SamanwaySadhu**
### Description of what the PR does
Changed the texts for a few JRadioButton, pickFileButton from 'Select' to 'Select...'

### Issue which the PR addresses
Fixes #820 

### Environment in which the PR was developed (OS, IDE, Java version, etc.)
Windows 10, Eclipse 2021-12 R, JDK 8u381 (1.8)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
Start Server, Admin and Team and check for any buttons which shows 'Select...' and none shows 'Select'

### CODE REVIEW

File: src/edu/csus/ecs/pc2/ui/JSerializFilePicker.java [hunk 1]
```diff
@@ -76,8 +76,8 @@ private void initialize() {
     private JButton getPickFileButton() {
         if (pickFileButton == null) {
             pickFileButton = new JButton();
-            pickFileButton.setName("Select");
-            pickFileButton.setText("Select");
+            pickFileButton.setName("Select...");
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/ui/JSerializFilePicker.java:79]: I don't see any reason to change the "Name" of the button.  Select was probably fine for the name.  However, that being said, I don't think it matters here since no one looks up the component by name.  I'm fine leaving as "Select...", or, removing that line altogether.

**Review by johnbrvc — APPROVED** [review]
Other than the comment I made, I tested this out, and it seems to work as desribed.

File: src/edu/csus/ecs/pc2/ui/JSerializFilePicker.java (hunk 1 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/ui/JSerializFilePicker.java]: Removed the line then build and ran the JUnits again.

**Review by troy2914 — APPROVED** [review]
looks good.

**Review by johnbrvc — APPROVED** [review]
Resolves the issue.  Low risk/impact on system. 
Builds and runs.

**Review by clevengr — APPROVED** [review]
Looks good; adding an approval.  I'll also merge the PR.
