### PR TITLE
use bouncycastle to generate cacerts.pc2

### LINKED ISSUE #687: Can not generate valid cacerts.pc2 for Event Feed web services on newer JRE's
**Describe the issue**: please provide a clear and concise description of what the bug is.  
With newer JRE's, when the cacerts.pc2 certificate file needs to be created (IE it doesn't exist), pc2ef throws an Illegal Access exception and an invalid SSL certificate is produced.  As a result, the web services endpoints to not work since a remote host can not establish a secure
connection.

**To Reproduce**: 
On the ICPC 2022 WF Image:
1) Load a contest.
2) Start pc2 server
3) make sure there is a feeder account created
4) start pc2ef from a folder where there is no cacerts.pc2 file
5) Start the web services feeds
6) observe the standard output produced (there will be an exception report as shown in the logs below)

**Expected behavior**: 
A valid certificate (cacerts.pc2) should be created.

**Actual behavior**: 
An invalid certificate is created.

**Environment**:
Version         : 9.9build 20230128
Build Date      : Saturday, January 28th 2023 14:48 UTC
Build Number    : 6437
OS              : Linux 5.15.0-56-generic (amd64)
Java Version    : 17.0.5

**Log Info**: 
```
java.lang.IllegalAccessException: class edu.csus.ecs.pc2.services.eventFeed.WebServer cannot access class sun.security.tools.keytool.CertAndKeyGen (in module java.base) because module java.base does not export sun.security.tools.keytool to unnamed module @62bd2070
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at edu.csus.ecs.pc2.services.eventFeed.WebServer.createKeyStoreAndKey(WebServer.java:129)
        at edu.csus.ecs.pc2.services.eventFeed.WebServer.startWebServer(WebServer.java:186)
        at edu.csus.ecs.pc2.ui.WebServerPane.startWebServer(WebServerPane.java:164)
        at edu.csus.ecs.pc2.ui.WebServerPane.access$000(WebServerPane.java:42)
        at edu.csus.ecs.pc2.ui.WebServerPane$1.actionPerformed(WebServerPane.java:133)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-02-13 10:34:34.495:INFO::AWT-EventQueue-0: Logging initialized @15702ms
Mon Feb 13 10:34:34 EST 2023 Starting /starttime web service
Mon Feb 13 10:34:34 EST 2023 Starting /fetchRun web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/scoreboard web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/languages web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/teams web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/groups web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/organizations web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/judgement-types web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/clarifications web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/submissions web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/problems web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/judgements web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/runs web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/event-feed web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/state web service
Mon Feb 13 10:34:34 EST 2023 Loading /home/pc2/realm.properties
2023-02-13 10:34:34.658:INFO:oejs.Server:AWT-EventQueue-0: jetty-9.2.11.v20150529
2023-02-13 10:34:35.018:INFO:oejsh.ContextHandler:AWT-EventQueue-0: Started o.e.j.s.ServletContextHandler@548fe051{/,null,AVAILABLE}
2023-02-13 10:34:35.075:INFO:oejs.ServerConnector:AWT-EventQueue-0: Started ServerConnector@1250e5c9{SSL-HTTP/1.1}{0.0.0.0:50443}
2023-02-13 10:34:35.075:INFO:oejs.Server:AWT-EventQueue-0: Started @16284ms
Mon Feb 13 10:34:35 EST 2023 Started web server on port 50443
```
**Workaround **:
Run the event feed module on JRE 1.8 or Java 8 

**Screenshots**:  
image

**Additional context**: 
Browsers will report an "End of File" error when trying to connect to a feeder that is using a bad certificate.
There is a fair amount of discussion on google about the issue: https://stackoverflow.com/questions/29060064/sun-security-x509-certandkeygen-and-sun-security-pkcs-pkcs10-missing-in-jdk8
This error is caused by the fact that sun.security module is no longer supported in Java 16 and higher. Try using the methods described here: https://openjdk.java.net/jeps/396  [JohnB Note: I did not read the link suggestion - I pulled it from a forum]

### PR DESCRIPTION
**Pull request by troy2914**
This now generates a 2048 byte RSA key self signed cert.

Though for finals in Sharm I suggest we create a icpc signed cert for pc2ef (where will it be run from)?

fixes #687 

to test start a server loading a contest from samps/contests
start a pc2ef

you should see a cacerts.pc2 created (make sure it is not there before you start).
and the command line should emit not any exceptions.

### CODE REVIEW

**Comment by johnbrvc** [comment]
I don't believe we need a certificate for WF. No one is connecting to our EF.

File: src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java [hunk 1]
```diff
@@ -107,80 +114,95 @@ public class WebServer implements UIPlugin {
...
+
+        X509CertificateHolder certificateHolder = certificateBuilder.build(contentSigner);
+
+        Certificate selfSignedCert = new JcaX509CertificateConverter()
+                .getCertificate(certificateHolder);
+
+        return selfSignedCert;
+    }
+
+    // based on https://stackoverflow.com/questions/43960761/how-to-store-and-reuse-keypair-in-java/43965528#43965528
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java:164]: Maybe move these comments to the beginning of the "bouncy" section, around line 117-119?   Not a big deal though.

**Review by johnbrvc — APPROVED** [review]
Tested on GNY AWS server running Ubuntu 22.04 (contest image).  Removed existing windows generated cacerts.pc2.  It generated a cacerts.pc2 and I could access the web server from the internet.  Looks good.

File: src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java (hunk 1 above)
Comment (troy2914) [reply src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java]: fixed.

**Review by johnbrvc — APPROVED** [review]

**Comment by clevengr** [comment]
I'm trying to verify this PR.  I cloned @troy2914 's github fork, then switched to the `i687_fix_cacerts` branch.  After verfiying there was no `cacerts.pc2` file present,  I started a PC2 Server using `--load sumithello`, started an Admin (to verify that a `scoreboard1` account existed), then logged into the `b1` account.  The Board created `html` and `public_html` folders, but nowhere can I find a new `cacerts.pc2` file.  There is no error on any of the PC2 consoles.  

The "Steps to Test the PR" indicate I should see a new `cacerts.pc2` file. I'm assuming that should be in the root folder where I launch the server/admin/board from -- but it's not there.  What am I doing wrong?

Notes:  
- I am running the server and clients out of Eclipse -- but it _should_ work correctly doing that, right?  
- I DO see the `bcpkix-jkd18on-176.jar` (Bouncy Castle jar) in my Build Path
- I am using JDK 1.8.0_371

**Comment by johnbrvc** [comment]
Event feeder account... not board.  Also you to have to start the event feeder.

**Review by lane55 — CHANGES_REQUESTED** [review]
EF failed to Start Web Servies
Start printed exceptions and did not start

**Comment by lane55** [comment]
Test: 
load sumh sample contest, 
create 1 EF account
login as ef1
Click Start on Web Services

Expected
Web services to start

Actual
threw exceptions to stdout 
web services did not start

Environment
Microsoft Windows [Version 10.0.19044.2130]
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Attaching stacktraces output to stdout
[i687_fix_cacerts.fail.errors.txt](https://github.com/pc2ccs/pc2v9/files/12974175/i687_fix_cacerts.fail.errors.txt)

**Review by clevengr — COMMENTED** [review]
The "steps to test" listed in the PR are wrong (it says to start a _board_ when in fact you need to 
- ensure there is an "EFClient" account in the sample contest you choose (not all samples have such an account), 
- start an _**ef-client**_,
- start the WebServer (services), and
- open a browser to verify you can hit the web server without errors.)

Yes, the above "might have been obvious" but hey -- I like to believe the instructions given to me, at least for starters.  In any case, once I followed the correct "steps to test"  I was able to successfully run the PR without errors showing either in the logs or on the console.  That is, I started the server, admin, efclient, and webserver without errors, and I was able to hit various web services (including "/", "/contest", and "/contest/scoreboard") with no errors.  I also noted the creation of a new `cacerts.pc2` file where none existed before.

Because of this, I'm essentially ready to "Approve" the PR.

However, it's important that @lane55 noted errors when attempting to run the PR.  I suspect that these may be because of the Java version he is using, which from his comments was:  
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
```

I used 
```
Java ver 1.8.0_271 build  Windows 10 10.0 (amd64)
```

I seem to recall there was a major security change in Java around version 1.8.0_178 (or thereabouts); it was the thing which led us to revamp the "security model" and to require the use of 
```
-Djdk.crypto.KeyAgreement.legacyKDF=true
```
when running PC2.  Essentially, at that point (which was several years ago) I believe we effectively made the decision that the minimum Java requirement for PC2 was not just Java 1.8, but Java 1.8.x  where x is whatever Java version included that security change.

@lane55 : can you please re-run your tests on this PR using a more recent version of Java (either Java 1.8.x where x>200, or Java 1.9+?   I suspect this might remove the issues you were having... at which point we can Approve the PR.

**Comment by johnbrvc** [comment]
I can confirm it works correctly on WIndows 11, using jdk1.8.0_321.

**Comment by troy2914** [comment]
> The "steps to test" listed in the PR are wrong (it says to start a _board_ when in fact you need to
> 
>     * ensure there is an "EFClient" account in the sample contest you choose (not all samples have such an account),
> 
>     * start an _**ef-client**_,
> 
>     * start the WebServer (services), and
> 
>     * open a browser to verify you can hit the web server without errors.)
> 
> 
> Yes, the above "might have been obvious" but hey -- I like to believe the instructions given to me, at least for starters. In any case, once I followed the correct "steps to test" I was able to successfully run the PR without errors showing either in the logs or on the console. That is, I started the server, admin, efclient, and webserver without errors, and I was able to hit various web services (including "/", "/contest", and "/contest/scoreboard") with no errors. I also noted the creation of a new `cacerts.pc2` file where none existed before.
> 
> Because of this, I'm essentially ready to "Approve" the PR.
> 
> However, it's important that @lane55 noted errors when attempting to run the PR. I suspect that these may be because of the Java version he is using, which from his comments was:
> 
> ```
> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> ```
> 
> I used
> 
> ```
> Java ver 1.8.0_271 build  Windows 10 10.0 (amd64)
> ```
> 
> I seem to recall there was a major security change in Java around version 1.8.0_178 (or thereabouts); it was the thing which led us to revamp the "security model" and to require the use of
> 
> ```
> -Djdk.crypto.KeyAgreement.legacyKDF=true
> ```
> 
> when running PC2. Essentially, at that point (which was several years ago) I believe we effectively made the decision that the minimum Java requirement for PC2 was not just Java 1.8, but Java 1.8.x where x is whatever Java version included that security change.
> 
> @lane55 : can you please re-run your tests on this PR using a more recent version of Java (either Java 1.8.x where x>200, or Java 1.9+? I suspect this might remove the issues you were having... at which point we can Approve the PR.

I updated the directions.

File: src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java [hunk 2]
```diff
@@ -107,80 +114,95 @@ public class WebServer implements UIPlugin {
...
-            exts.set(SubjectKeyIdentifierExtension.NAME, new SubjectKeyIdentifierExtension(new KeyIdentifier(chain[0].getPublicKey()).getIdentifier()));
-            info.set(X509CertInfo.EXTENSIONS, exts);
-
-            X509CertImpl outCert = new X509CertImpl(info);
-            outCert.sign(rootPrivateKey, issuerSigAlg);
-
-            ks.setCertificateEntry("jetty", outCert);
-            ks.setKeyEntry("jetty", rootPrivateKey, keystorePassword.toCharArray(), chain);
         } catch (Exception ex) {
+            log.throwing("WebServer", "createKeyStoreAndFile", ex);
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java:185]: If the EFClient is using a GUI (and I don't see how the WebServer can be started otherwise), I think the occurrence of an exception here should be displayed with a GUI dialog (the user might not be monitoring the console, and typically _won't_ be poring over logs).  

For example, the following block of code added between the above `log.throwing()` and the following `ex.printStackTrace()` would do the trick:
```java
            if (getController().isUsingGUI()) {
                String msg = "Warning: exception occurred during KeyStore creation: " + ex.getMessage();
                msg += "\nStack trace:";
                StackTraceElement[] stackTraceElements = ex.getStackTrace();
                for (StackTraceElement line : stackTraceElements) {
                    if (line.toString().contains("edu.csus.ecs.pc2")) {
                        msg += "\n" + line;
                    }
                }
                msg += "\n...";
                JOptionPane.showMessageDialog(null, msg, "Error creating WebServer KeyStore", JOptionPane.WARNING_MESSAGE);
            }

```

I've tested this code by forcing an exception above this `catch` clause and it works; here's an example:

image

**Review by clevengr — CHANGES_REQUESTED** [review]
I would like the occurrence of an exception during keystore creation to be presented to the user in the GUI.  See the comment in the `Webserver.java` file at line 185 (also listed in the comments above) for details and an already-implemented solution.

File: src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java (hunk 2 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java:185]: The event feed CAN be (and for us in GNY is always) started in `--nogui `mode.  Page 140 of the _PC2 Administrators Guide_ explains it in Appendix M.  In this case, the `pc2ws.properties` file is examined for the settings.  In addition, the https://github.com/pc2ccs/pc2v9/wiki/Event-Feed-Module page has a whole section on the _non-gui_ mode of the event feeder.  That being said, to log exceptions to a logfile is fine for the --nogui mode.  But yes, a message/dialog of some sort would be nice in the event the SS Certificate can not be generated.

Comment (troy2914) [reply src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java:185]: do you want an exit after they hit the ok on that dialog?

Comment (troy2914) [reply src/edu/csus/ecs/pc2/services/eventFeed/WebServer.java:197]: anyways, i have added that code.

**Review by clevengr — APPROVED** [review]
