### PR TITLE
i_942 Fix entry points with periods

### LINKED ISSUE #942: Submissions with entry points containing periods are not processed properly
**Describe the issue**: 
This was noticed during the WF Luxor wf47/systest1 pre-contest test where PC2 was shadowing DOMjudge.  If a submission (such as a Java submission) arrives on the event feed and includes an **entry_point** property of `nwerc2021.Knitpicking`, PC2 will trim this to `nwerc2021`, which causes the run to get a compile error since the appropriate class file can not be found.  A similar issue with Python submissions where the supplied **entry_point** is specified as `flatlandolympics.py`, PC2 will trim it `flatlandolympics`, causing it to fail.

**To Reproduce**:
Requires a great deal of set-up.  You will need a primary that can feed very specific _submission_ events to the shadow.  For example, the events have to look something like this:
```
[
   {
      "external_id" : null,
      "entry_point" : "nwerc2021.Knitpicking",
      "team_id" : "47037",
      "contest_time" : "0:10:50.578",
      "id" : "359",
      "problem_id" : "knitpicking",
      "files" : [
         {
            "filename" : "submission.zip",
            "mime" : "application/zip",
            "href" : "contests/wf47_systest1/submissions/359/files"
         }
      ],
      "time" : "2024-03-16T14:10:50.578+02:00",
      "language_id" : "java",
      "import_error" : null
   },
   {
      "problem_id" : "flatlandolympics",
      "files" : [
         {
            "href" : "contests/wf47_systest1/submissions/1346/files",
            "mime" : "application/zip",
            "filename" : "submission.zip"
         }
      ],
      "contest_time" : "1:23:50.568",
      "id" : "1346",
      "entry_point" : "flatlandolympics.py",
      "team_id" : "47043",
      "external_id" : null,
      "language_id" : "python3",
      "import_error" : null,
      "time" : "2024-03-16T15:23:50.568+02:00"
   }
]

```
This can only be achieved over the event feed and not the the pc2team fat client.  This may mean hand-crafting events.  

**Expected behavior**:
The **entry_point**'s provided in the event-feed should be utilized correctly, and not stripped after the period.

**Actual behavior**: 
Debugging reveals that the first **entry_point**, `nwerc2023.Knitpicking` gets changed to `nwerc2023`.  And the second, `flatlandolympics.py` gets changed to `flatlandolympics`.  

**Environment**: 
Windows 11
Ubuntu 22.04
jdk1.8.0_321

**Log Info**:
 

**Screenshots**:  

**Additional context**:
The `setEntryPoint()` method in **Run.java** is the one responsible for stripping the **entry_point** of the required information by calling the `Utilities.getFileBaseName()` method.  This should be fixed to possibly adjust the **entry_point** based on the language supplied.

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
If an `entry_point `was specified in a "**submissions**" event on the event-feed that contained a package (for Java) or an explicit file (for Python3), the run would fail (_compile error_ for Java and _Run time Exception_ for Python3). Add code to handle the special cases for each language that can specify an entry point. Code works the same as before if no `entry_point `specified.
Remove pruning of `entry_point `when it is set in the **Run**.   This was removing important information for Java entry points with package information specified and extensions on Python files.

CI: Add constant for {files} command substitution string and change in places it's used.
NOTE: This may relate to issue #869 in that the {files} substitution variable is mistyped in the code perhaps.  It should be {:files} probably.  That change is not part of this code, but it is now easier to fix that, should we decide to do it.  It's unclear if if {files} is a type or legacy nomenclature.

### Issue which the PR addresses
Fixes #942 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 11
Java jdk1.8.0_321

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
Refer to the issue #942.  This is very difficult to test without a shadow system, and the procedure described there is lengthy and involved.

A good thorough code review is probably a good first step.

### CODE REVIEW

**Review by troy2914 — COMMENTED** [review]
These changes look okay.

**Review by troy2914 — APPROVED** [review]
new change look reasonable to me.

**Review by kkarakas — APPROVED** [review]
I think it looks good!

**Comment by clevengr** [comment]
Regarding the comment in the PR description:
```
It's unclear if if {files} is a type or legacy nomenclature.
```
I'm pretty sure this is typo (which is what I assume "type" in the above meant).  I don't recall that we ever had "command substitution" that didn't use a colon.

File: src/edu/csus/ecs/pc2/core/Constants.java [hunk 1]
```diff
@@ -96,18 +96,23 @@ private Constants() {
...
     /**
      * Command substitution variable for name of thing to execute (basename of source file)
      */
     public static final String CMDSUB_BASENAME_VARNAME = "{:basename}";
-    
+
+    /**
+     * Command substitution variable for all files submitted. Note the missing ':' - legacy.
+     */
+    public static final String CMSSUB_FILES_VARNAME = "{files}";
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/Constants.java:114]: "CMSSUB..." seems to me to be a weird name.  Was the intention that it be "CMDSUB...", as in "Command Substitution"? If so, I'd like to see that corrected, for the sake of keeping code clean and clear...

Also, I haven't yet reviewed the rest of the code but:  there are just one or two places where `{files}` (without the colon) is used; all other places use the proper form (`{:files}`).  It seems weird to me to provide a "code solution" like this to fix something that is (almost certainly) a typo.  Why not just correct the typo in the one or two places it occurs?
And on a related note (again, I haven't reviewed the rest of the code changes), are there OTHER places that are now using this substitution constant (when they should be using `{:files}`) ?

Having said this, I can see filing a "clean-up" Issue that suggests defining a string like "CMDSUB_FILES_VARNAME" -- and then replacing all hard-coded instances of `{:files}` with that string....  But I don't like having a string like this that uses the WRONG value.  It's too possible for someone in the future to think "oh, there's a CONST for this substitution so I should use that" -- thus getting the WRONG substitution.  Brrrr... brittle code.

Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/core/Constants.java:114]: Heh.  Yeah, that is a typo **CMSSUB** vs **CMDSUB**.
w/r/t `{files} `vs. `{:files}`, I was just concerned that `{files}` has been there so long (since 2017 when Doug added it), that if any CDP counts on `{files}` will break and any 
users that may use the GUI and "know" to use `{files}`, will now find it no longer works.  Are we concerned about "backward" compatibility for stuff that was wrong in the first place and was done 7 years ago?

Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/core/Constants.java]: BTW, I actually mention https://github.com/pc2ccs/pc2v9/issues/869 in the PR description, which is what you are referring to.  Quite frankly, I'm inclined to leave {files} there and ADD {:files} as well, but others may have a different opinion.  (I hate to break things by unbreaking things).
