### PR TITLE
I 292 Insure all judgements on all sites

### LINKED ISSUE #292: In a multiple sites contest  all judgements may not be on all sites  (NPE in Contest XML report)
**Describe the issue**: 

During a recent contest, the admin was not able to 

**To Reproduce**: 

Install pc2 version

unpack acpc-teens-2021-arch.zip

start server

show report, Report  ->  Contest XML Report

**Expected behavior**: 

   Create report with xml with no errors.

**Actual behavior**: please describe what _actually_ happened when you took the above steps:

NPE thrown

CSUS Programming Contest Control System
Version 9.7.0 20220106 (Thursday, January 6th 2022 04:19 UTC) Java ver 1.8.0_121 build 5822 Windows 10 10.0 (amd64) 
Contest Title: International Collegiate Programming Contest, Africa and Arab Collegiate Programming Championship for teens 2021
On: Friday, January 7, 2022 11:30:30 AM PST  Contest date/time: Sun Dec 05 01:00:34 PST 2021
Profile: Default (Default Contest)

** Contest XML Report

Exception in report: null
java.lang.NullPointerException
	at edu.csus.ecs.pc2.core.imports.ContestXML.addJudgementMemento(ContestXML.java:552)
	at edu.csus.ecs.pc2.core.imports.ContestXML.addRunMemento(ContestXML.java:522)
	at edu.csus.ecs.pc2.core.imports.ContestXML.toXML(ContestXML.java:168)
	at edu.csus.ecs.pc2.core.report.ContestReport.writeReport(ContestReport.java:44)
	at edu.csus.ecs.pc2.ui.ReportPane.createReportFile(ReportPane.java:534)
	at edu.csus.ecs.pc2.ui.ReportPane.generateSelectedReport(ReportPane.java:604)
	at edu.csus.ecs.pc2.ui.ReportPane$3.actionPerformed(ReportPane.java:438)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	

**Environment**: please complete the following information:

All env.
211204 214058.165|INFO|main|info|Version 9.7.0 20210317 (Wednesday, March 17th 2021 06:30 UTC) Java ver 11.0.11 build 6181 Linux 5.4.0-1030-aws (amd64) 

**Log Info**:  

N/A

**Screenshots**:  

N/A 

**Additional context**: 

none.

### PR DESCRIPTION
**Pull request by lane55**
### Description of what the PR does

PR changes server so every judgement from every server is on every server.

This only applies to contests with more than one site.

### Issue which the PR fixes

#292 - In a multiple sites contest all judgements may not be on all sites (NPE in Contest XML report)

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Java version 1.8.0_121
OS: Windows 10 10.0 (amd64)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Test 1 - prove all judgements are on all sites.
Start 3 sites (non-GUI).
   Start site 1 with samps\contests\problemflagtest CDP (creates 5 sites)
Run Judgements Report on each site.
Each report should show all judgements are on all sites.

Test 2 - test Contest XML
Can use Test 1 
Site 2: Add team and judge accounts  
Submit runs on site 1
Judge runs on site 2
Run Contest XML report - there should be no NPE.

Note: There are also a number of test case descriptions in the issue.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/core/PacketHandler.java [hunk 1]
```diff
@@ -3602,11 +3602,9 @@ private boolean isThisSite(Account account) {
     }
 
     /**
-     * Loads only the settings from the remote server into this server.
+     * Loads only the settings from the remote server into this server's model.
      * 
-     * Loads settings from other server, submissions, etc.  Sends
-     * out a login packet to any "new" servers which this site
-     * is not logged into. 
+     * Loads settings from other server, submissions, etc. into model.
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/PacketHandler.java:3607]: This is a trivial and certainly non-blocking note, but:  I don't understand why both lines 3605 and 3607 are present; they seem to say the same thing.

File: src/edu/csus/ecs/pc2/core/PacketHandler.java [hunk 2]
```diff
@@ -3642,6 +3640,20 @@ public void loadSettingsFromRemoteServer(ContestLoader loader, Packet packet, Co
 
         loader.addRemoteLoginsToModel(contest, controller, packet, remoteSiteNumber);
         
+        loader.addJudgementsToModel(contest, controller, packet);
+
+        if (isServer()) {
+            try {
+                contest.storeConfiguration(controller.getLog());
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/PacketHandler.java:3647]: I don't understand why the process of fixing bug 292 (which is about judgements not being added to the model) involves adding a new call to `storeConfiguration()`.   Is there some reason this is within the scope of bug 292?

File: src/edu/csus/ecs/pc2/core/list/JudgementSortBySiteAcronymComparator.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+    @Override
+    public int compare(Judgement jOne, Judgement j2) {
+
+        if (jOne.getSiteNumber() != j2.getSiteNumber()) {
+            return jOne.getSiteNumber() - j2.getSiteNumber();
+        } else if (jOne.getAcronym().equals(j2.getAcronym())) {
+            return jOne.getDisplayName().compareTo(j2.getDisplayName());
+        } else {
+            return jOne.getAcronym().compareTo(jOne.getAcronym());
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/core/list/JudgementSortBySiteAcronymComparator.java:29]: This line of code makes no sense to me. Why is it comparing a Judgement Acronym to itself?

File: src/edu/csus/ecs/pc2/ui/ReportPane.java [hunk 4]
```diff
@@ -486,9 +486,9 @@ protected void createHeader(PrintWriter printWriter, IReport report) {
             resumeTime = getContest().getContestTime().getResumeTime();
         }
         if (resumeTime == null) {
-            printWriter.print("  Contest date/time: never started");
+            printWriter.print("  Contest date/time: never started on site "+getContest().getSiteNumber());
         } else {
-            printWriter.print("  Contest date/time: " + resumeTime.getTime());
+            printWriter.print("  Contest date/time: " + resumeTime.getTime()+" on site "+getContest().getSiteNumber());
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/ui/ReportPane.java:491]: The same problem appears to exist here (`getContest().getSiteNumber()` could throw an NPE).

File: src/edu/csus/ecs/pc2/ui/ReportPane.java [hunk 5]
```diff
@@ -486,9 +486,9 @@ protected void createHeader(PrintWriter printWriter, IReport report) {
             resumeTime = getContest().getContestTime().getResumeTime();
         }
         if (resumeTime == null) {
-            printWriter.print("  Contest date/time: never started");
+            printWriter.print("  Contest date/time: never started on site "+getContest().getSiteNumber());
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/ui/ReportPane.java:489]: It looks to me like this new line could now throw an uncaught NPE.  Specifically, the previous lines start with resumeTime being set to null, then _if `getContest()` is not null_, resumeTime is updated from the value of `getContest().getContestTime().getResumeTime()`.  So when THIS statement is reached, _`getContest()` could be returning null_.  If that happens, _`getContest().getSiteNumber()` will throw an NPE_.

**Review by clevengr — CHANGES_REQUESTED** [review]
I couple of my comments are "dealer's choice"; if you don't like my suggestions, I have no problem with that.  But a couple of them are about places where I think the code needs to be fixed...

File: src/edu/csus/ecs/pc2/ui/ReportPane.java (hunk 5 above)
Comment (troy2914) [reply src/edu/csus/ecs/pc2/ui/ReportPane.java:489]: if getContest() return'ed null that would thrown a NPE in the bit before the == null.

Comment (clevengr) [reply src/edu/csus/ecs/pc2/ui/ReportPane.java:489]: I don't believe that's true.  The "bit before the == null" is only executed if getContest() != null.  So assume getContest() DOES return null.  Then when it gets to line 488, resumeTime will (still) be null, so it will execute line 489 -- with a null value for getContest().

File: src/edu/csus/ecs/pc2/core/PacketHandler.java (hunk 2 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/PacketHandler.java:3647]: Yes.   The judgements and other settings (from other sites) were not being saved to disk.

File: src/edu/csus/ecs/pc2/core/list/JudgementSortBySiteAcronymComparator.java (hunk 3 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/list/JudgementSortBySiteAcronymComparator.java:29]: copy/paste, typo, will push a fix.

File: src/edu/csus/ecs/pc2/ui/ReportPane.java (hunk 5 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/ui/ReportPane.java:489]: It is possible for a NPE.  It is very very unlikely.

File: src/edu/csus/ecs/pc2/core/list/JudgementSortBySiteAcronymComparator.java (hunk 3 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/core/list/JudgementSortBySiteAcronymComparator.java]: Pushed fix: 
commit b569c919d396e2d810b46c25700eba5649377eaf
Author: Douglas A. Lane <laned@ecs.csus.edu> 2022-01-25 09:49:15

**Comment by lane55** [comment]
Requested change fix pushed on 1/25/2022.   Ready for review.

File: src/edu/csus/ecs/pc2/ui/ReportPane.java (hunk 5 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/ui/ReportPane.java:489]: Sooo... "very very unlikely" is a criterion for allowing code that COULD cause an NPE?  That seems like a strange position coming from someone who is constantly harping that we should always be doing "continual improvement".  In fact, it sounds more like a "Tammy" comment :)    However, I'm going to let it go based on the fact that there is already a much earlier call to getContest() in this method (see line 476) which is (also) not protected by any handling of an NPE on getContest().    Fixing THAT one would probably require significant additional effort and is indeed "outside the scope" of this Issue.

**Review by clevengr — APPROVED** [review]
I'm not exactly overwhelmingly thrilled with the current state; there are comments which I've made to which no answer was given, and there is code which can throw an NPE which has no protection.  However, wanting to get SOMETHING moving, I'm approving this PR.

**Comment by lane55** [comment]
> Sooo... "very very unlikely" is a criterion for allowing code that COULD cause an NPE?
Yes, esp in this case.

Here is the explanation I decided not to clutter the Issue initially with.

The code that has been assigning the contest and controller has been in place
and tested for decade(s).   So, yes it is more likely that a bug in the JVM or OS would cause
a NPE due to Report’s getContest() or getController() than a bug in the code that assigns the
instances.  Also there a Junits that test the assignment as well.

Since we were moving fast I decided to not provide a specific criteria about the internals
of how Report was instanciated.

The other classes where NPE due to getContest() or getController() will very very unlikely are
all JFrame, JPane classes in pc2.

Tammy’s error was that she did not log in a try/catch which we long ago knew was a mistake
in error handling.   In that case the catch block was empty when an I/O exception would
occur, and as we know it did.    I would phrase the possibility as “some day the Exception
will be thrown”

Doug

ps. I am just a tiny more experienced and familiar with the code than Tammy 😊

dal.
