### PR TITLE
i700: change default to not load sample data sets

### LINKED ISSUE #700: Change default to not load sample test data sets (disable feature #244)
**Describe the issue**: 

Temporarily disable #244, there is a bug, the fix for that bug is described in #701 

This change defaults to not load samples data files as coded in #244

Work around:
in contest.yaml use this
load-sample-judges-data: false

Code fix to change default to FALSE
in class ContestSnakeYAMLLoader change
 boolean loadSamples = fetchBooleanValue(content, LOAD_SAMPLE_JUDGES_DATA, true);
to 
boolean loadSamples = fetchBooleanValue(content, LOAD_SAMPLE_JUDGES_DATA, **false**);

**To Reproduce**: please describe, in order, the steps to reproduce the behavior:

**Expected behavior**: please provide a description of what you *expected* to happen when you took the above steps:  

**Actual behavior**: please describe what _actually_ happened when you took the above steps:

**Environment**: please complete the following information:
 - OS name and version under which the issue was detected (e.g. Windows 10 or Ubuntu 18.04):
 - PC2 Version (e.g. 9.7.0):   
 - Browser (if the bug is related to web-based team clients) (e.g. _Chrome Version 75.0.3770.142_ or _Safari Version 11.1.2_):

**Log Info**:  PC^2 generates logs (in the **logs** folder for client modules; under the **profiles** folder for the PC2 Server).  Please review the relevant logs and provide copies of them as attachments -- particularly if the logs show Exceptions being thrown.  

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.

**Additional context**: please add any other context about the issue here.

### PR DESCRIPTION
**Pull request by lane55**
Disable loading data/sample files.  Short term fix, long term fix is #701 

Added "TODO 701" todo items into source

### Description of what the PR does

The PR does not load data/sample/ test data sets into a Problem,
only files from secret/ are loaded.

### Issue which the PR fixes

#700

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

--load mini
view problem is Problem tab

submit a run
judge a run (source from accepted/ dir)

**Expected behavior**:

There should be 7 data files (not 10)
sumit.in
sumit1.in
sumit2.in
sumit3.in
sumit4.in
sumit5.in
sumit6.in

run should be judged Yes.

### CODE REVIEW

**Comment by troy2914** [comment]
I would rather see the prior comment reverted.  
```
git revert f805e1f8caeaa71afc14b6303f3d9ef380b42758
```
based on conversation in Seattle that data/sample then data/secret should be executed.

**Comment by lane55** [comment]
> I would rather see the prior comment reverted.
> git revert f805e1f8caeaa71afc14b6303f3d9ef380b42758

Bure,, but tat failed in my fork.

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 1]
```diff
@@ -410,7 +410,8 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
             setCcsTestMode(contest, ccsTestMode);
         }
         
-        boolean loadSamples = fetchBooleanValue(content, LOAD_SAMPLE_JUDGES_DATA, true);
+        // TODO 701 change LOAD_SAMPLE_JUDGES_DATA, false); to , true);
+        boolean loadSamples = fetchBooleanValue(content, LOAD_SAMPLE_JUDGES_DATA, false);
```
Comment (troy2914) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java:414]: it might be safer to change this to loadSamples = false,  we know we do not want to enable this broken implementation.

**Review by troy2914 — CHANGES_REQUESTED** [review]

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 1 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java:414]: This is a non-documented change, so only us (or those who happen to read the code) would enable it.

Comment (lane55) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java:414]: This change allows the person who update the code to test it with a single .ini entry.

**Comment by lane55** [comment]
> > I would rather see the prior comment reverted.
> > git revert [f805e1f](https://github.com/pc2ccs/pc2v9/commit/f805e1f8caeaa71afc14b6303f3d9ef380b42758)

I pushed the revert, does that work?
Accidentally pushed to develop, that's what started the mess.

**Review by johnbrvc — APPROVED** [review]
