### PR TITLE
I397 shadow exception logging

### LINKED ISSUE #397: Shadow code does not properly log exceptions
**Describe the issue**: 
Various modules in package  `pc2.shadow` do not log sufficient information when an exception occurs.  Specifically, for example, class `RemoteEventFeedMonitor` contains at least five `catch` clauses in non-Static methods which log an error message but _do not include the exception in the log message_.  It is much easier to debug an issue when the specific exception is identified in the log.

**To Reproduce**: 
This is tricky; it requires connecting to an Event Feed which supplies events which, when processed, throw an exception.  The issue was initially detected when attempting to process a Kattis event feed from their `ProgNova20` contest (https://prognova20.kattis.com/clics-api/contests/prognova20/event-feed) using PC2 Build 6238~develop, but it's not clear (since the specific exception wasn't logged) exactly what caused the issue to surface.

**Expected behavior**: 
When an exception occurs during Shadow Event-Feed processing, the specific exception should be identified in the log.

**Actual behavior**: 
There is a message in the log identifying the Event Feed event which caused the exception, but nothing identifying exactly what exception occurred.

**Environment**: please complete the following information:
 - Ubuntu 20.04 - ICPC NAC build 2022-0507
 - PC2 Version (e.g. 9.7.0): 6238~develop  

But it probably happens on all platforms in all PC2 Builds since Shadowing was first added.

**Log Info**:  
```
220511 182848.183|INFO|RemoteEventFeedMonitorThread|run|Got event string: {"type": "submissions", "id": "15ac3021-feeb-4080-a3d4-2665d2b4f63d", "op": "create", "data": {"id": "5296543", "time": "2020-02-07T23:03:39.516+01", "team_id": "169565", "problem_id": "courseplanning", "entry_point": "Tests", "language_id": "java", "contest_time": "0:03:39.516", "files": [{"href": "/clics-api/contests/prognova20/submissions/5296543/files", "mime": "application/zip"}]}}
220511 182848.184|INFO|RemoteEventFeedMonitorThread|run|Found event of type submissions: {"type": "submissions", "id": "15ac3021-feeb-4080-a3d4-2665d2b4f63d", "op": "create", "data": {"id": "5296543", "time": "2020-02-07T23:03:39.516+01", "team_id": "169565", "problem_id": "courseplanning", "entry_point": "Tests", "language_id": "java", "contest_time": "0:03:39.516", "files": [{"href": "/clics-api/contests/prognova20/submissions/5296543/files", "mime": "application/zip"}]}}
220511 182848.184|INFO|RemoteEventFeedMonitorThread|run|Processing submission event: {"type": "submissions", "id": "15ac3021-feeb-4080-a3d4-2665d2b4f63d", "op": "create", "data": {"id": "5296543", "time": "2020-02-07T23:03:39.516+01", "team_id": "169565", "problem_id": "courseplanning", "entry_point": "Tests", "language_id": "java", "contest_time": "0:03:39.516", "files": [{"href": "/clics-api/contests/prognova20/submissions/5296543/files", "mime": "application/zip"}]}}
220511 182848.385|INFO|RemoteEventFeedMonitorThread|run|Found run 5296543 from team 169565: event= {"type": "submissions", "id": "15ac3021-feeb-4080-a3d4-2665d2b4f63d", "op": "create", "data": {"id": "5296543", "time": "2020-02-07T23:03:39.516+01", "team_id": "169565", "problem_id": "courseplanning", "entry_point": "Tests", "language_id": "java", "contest_time": "0:03:39.516", "files": [{"href": "/clics-api/contests/prognova20/submissions/5296543/files", "mime": "application/zip"}]}}
220511 182848.385|INFO|RemoteEventFeedMonitorThread|run|Fetching files from remote system using id 5296543
220511 182849.246|INFO|RemoteEventFeedMonitorThread|run|Got files for submission id 5296543 from remote CCS after 1 try.
220511 182849.246|INFO|RemoteEventFeedMonitorThread|run|Received files from remote system for id 5296543
220511 182849.246|INFO|RemoteEventFeedMonitorThread|run|Invoking submitter.submitRun() for team 169565 problem courseplanning language java time 219516 submissionID 5296543
220511 182849.261|WARNING|RemoteEventFeedMonitorThread|run|Exception submitting run for: \{"type": "submissions", "id": "15ac3021-feeb-4080-a3d4-2665d2b4f63d", "op": "create", "data": {"id": "5296543", "time": "2020-02-07T23:03:39.516+01", "team_id": "169565", "problem_id": "courseplanning", "entry_point": "Tests", "language_id": "java", "contest_time": "0:03:39.516", "files": [{"href": "/clics-api/contests/prognova20/submissions/5296543/files", "mime": "application/zip"}]}}
```

**Suggested fix**: 
Update all log messages in `catch` clauses to use the form log( LEVEL, String, Throwable) instead of just log(LEVEL,String).
- Note: care must be taken in doing this; some `Static` methods contain log messages and it's possible that the `log` variable isn't set when these Static methods are called.

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does
Adds logging of exceptions in catch clauses where previously only a text message was logged.

### Issue which the PR fixes
Fixes #397 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 10.0, Eclipse Version: 2019-12 (4.14.0) Build id: 20191212-1212; Java 1.8_201

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
- Obtain access to a Primary CCS capable of generating an Event Feed containing submissions.
  - For example, https://open.kattis.com/clics-api/contests/prognova20/ can be used, along with the PC2 credentials allowing access to Kattis.  Alternatively, a separate PC2 Primary could be set up, including ensuring there are submissions in the Primary CCS and also including running an Event Feed generator on the Primary.
- Start a Shadow PC2 server configured for a contest which has NO teams.
  - Ensure the server is configured with a CDP matching the Primary.
- Start an Admin
  - On the Settings tab, configure Shadow Mode to connect to the Primary CCS:
    - Enable CCS Test mode (required for Shadow to work).
    - Enable Shadow Mode.
    - Enter the Primary CCS URL along with Login and Password information .
  - On the Accounts tab, ensure that a Feeder1 account is defined.
- Start an Event Feeder client (pc2ef)
- Select "Shadow Mode" on the EF client.
- Click "Start Shadowing".

The Shadow system should begin fetching the Primary CCS Event Feed,  finding submissions in the Event Feed.  Since there are no teams in the Shadow CCS (see above), the call to `RemoteRunSubmitter.submitRun` will throw an exception.

Examine the Shadow FEEDER1 log; verify that the exception itself is shown in the log.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java [hunk 1]
```diff
@@ -464,20 +464,19 @@ public void run() {
                                             } catch (Exception e) {
                                                 // TODO design error handling reporting
                                                 if (Utilities.isDebugMode()) {
-                                                    System.err.println("Exception submitting run for: " + event);
+                                                    System.err.println("Exception submitting run for event: " + event + ": " + e);
                                                 }
-                                                log.log(Level.WARNING, "Exception submitting run for: \\" + event);
-                                                
+                                                log.log(Level.WARNING, "Exception submitting run for event: " + event + ": ", e);
```
Comment (lane55) [inline src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java:469]: Missing exception message in log message, the message will show this when after the : should be a message
Exception submitting run for event: <EVENT>:   
before:
+ event + ": ", e);
change to:
+ event + ": ", + e, e);

File: src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java [hunk 2]
```diff
@@ -464,20 +464,19 @@ public void run() {
...
                                                 e.printStackTrace();
                                             }
                                         }
 
                                     } catch (Exception e) {
                                         // TODO design error handling reporting (logging?)
                                         if (Utilities.isDebugMode()) {
-                                            System.err.println("Exception processing event: " + e.toString() + ": event = " + event);
+                                            System.err.println("Exception processing event: " + event + "\n " + e.toString());
```
Comment (lane55) [inline src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java:477]: Avoid newlines in log messages.   It may seem to read better but it does not allow grep to list both
the message and the event line.   This is inconsistent with nearly all log messages.    Note that even System.err
can be captured to a log file (as it was in the CSUS Contest).

File: src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java (hunk 1 above)
Comment (lane55) [inline src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java:469]: *** Note *** There are 3 comments about log messages, instead of adding a comment for every log change, a
single comment per "correction" has been added.

**Review by lane55 — CHANGES_REQUESTED** [review]
Comments describe changes to make the logging like the typical logging throughout
the rest of pc2.

File: src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java (hunk 1 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java:469]: I don't think this is a good suggestion.  I believe that the form  `log.log(LEVEL,String, Throwable)` (which is what the new code does) already puts the exception in the log (that's what the `Throwable` parameter is for).  Your suggested change would cause the exception to be placed in the log TWICE.

And anyway, the suggestion to change it to `event + ": ", + e, e);` is going to generate a syntax error -- there are too many commas in that suggested change.  But I think you meant "change to: `event + ": " + e, e);` " (which would put the exception in the log twice).

File: src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java (hunk 2 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java:477]: Agreed; I'll change it (I had already made such a change in other places; that one slipped by me...)

File: src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java [hunk 3]
```diff
@@ -464,20 +464,19 @@ public void run() {
...
                                         }
-                                        log.log(Level.WARNING, "Exception processing event: " + e.toString() + ": event = " + event);
+                                        log.log(Level.WARNING, "Exception processing event: " + event, e);
```
[the remark this answers is not in the document]
Comment (clevengr) [reply src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java:479]: Again, I believe the form `log.log(LEVEL, String, Throwable)` already puts the exception in the log.
And I disagree that it's better to have a huge log line that the user has to scroll across; I'd much rather see the exception in the log in the form put there by the "standard log message" form of `log(LEVEL, String, Throwable)`.
I also disagree that the form you suggest is "convention"; there are _many_ places in the system that use the form `log(LEVEL, String, Throwable)`.

File: src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java (hunk 1 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java:469]: I'm not sure what this comment is intended to request (if anything).

**Review by lane55 — APPROVED** [review]
approved

**Comment by clevengr** [comment]
Doug agreed to accept the PR for merging.
