### PR TITLE
I897: Added Additional Files in the Confirm Submission window of Team GUI

### LINKED ISSUE #897: Team client GUI do not show Additional Files in the confirmation Window
**Describe the issue**:
When someone tries to submit some Additional files, the Confirm Submission window does not display the additional files' paths like it shows for the main file.

**To Reproduce**:
Start a Server, Admin and Team client. Start the contest and then try to make a submission from Team GUI with some additional files.

**Actual behavior**:
Capture

**Expected behavior**:
The list of additional files' paths should also show up in the window.

**Environment**: please complete the following information:
Windows 10, Eclipse 2021-12 R, JDK 8u381 (1.8)

**Additional context**:
Probably need to update `testOrSubmitRun` function of the class `src/edu/csus/ecs/pc2/ui/SubmitRunPane.java` at this line the string [confirmQuestion](https://github.com/pc2ccs/pc2v9/blob/e1da7a679e659057fd08b1634cd0eed61af67f21/src/edu/csus/ecs/pc2/ui/SubmitRunPane.java#L495)

### PR DESCRIPTION
**Pull request by SamanwaySadhu**
### Description of what the PR does
Updated class `SubmitRunPane` and put a check in function `testOrSubmitRun` to add the Additional Files (if included) in the confirm submission window.

### Issue which the PR addresses
Fixes #897 

### Environment in which the PR was developed (OS, IDE, Java version, etc.)
Windows 10, Eclipse 2021-12 R, JDK 8u381 (1.8)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
- Run the Ant script `build.xml` in the `pc2v9` project.
- Start a PC2 server, loading a sample contest such as "SumitHello".
- Start a PC2 Admin.
- Start the contest.
- Start a PC2 Team.
- Try to submit a problem where you add some files with the same name as each other or the Main File name in Additional Files.
- The confirm submission window will now include all the Additional File(s) included.
Capture

### CODE REVIEW

File: src/edu/csus/ecs/pc2/ui/SubmitRunPane.java [hunk 1]
```diff
@@ -493,14 +493,40 @@ protected void testOrSubmitRun(boolean submitTheRun) {
...
-
-                    log.info("submitRun for " + problem + " " + language + " file: " + filename);
+                    
+                    String logInfo = "submitRun for " + problem + " " + language + " main file: " + filename;
+                    if (additionalFilesMCLB.getRowCount() > 0) {
+                        logInfo += " additional file(s): [";
+                        for (int i = 0; i < additionalFilesMCLB.getRowCount(); i++) {
+                            String otherfilename = (String) additionalFilesMCLB.getRow(i)[0]; 
+                            logInfo += otherfilename;
+                            if (i == additionalFilesMCLB.getRowCount() - 1) logInfo += "]";
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/ui/SubmitRunPane.java:525]: For "if" statements that have a single line of code, we usually like to put the code in a block with braces as opposed to putting it on the same line.

**Review by johnbrvc — CHANGES_REQUESTED** [review]
Built and tested; checked the logs as well, generates a very nice message in the log when multiple files are submitted.
Submit confirm dialog looks good with all the files.
Just the one change with the:
```
if(...) {
      one line;
}
```

File: src/edu/csus/ecs/pc2/ui/SubmitRunPane.java (hunk 1 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/ui/SubmitRunPane.java]: Updated

**Review by johnbrvc — APPROVED** [review]
Look ok to me.

File: src/edu/csus/ecs/pc2/ui/SubmitRunPane.java [hunk 2]
```diff
@@ -493,14 +493,44 @@ protected void testOrSubmitRun(boolean submitTheRun) {
...
+                    confirmQuestion += "<TR><TD><FONT SIZE=+1>Additional File(s):</FONT></TD><TD><FONT COLOR=BLUE SIZE=+1>" + Utilities.forHTML(otherfilename) + "</FONT></TD></TR>";
+                    for (int i = 1; i < additionalFilesMCLB.getRowCount(); i++) {
+                        otherfilename = (String) additionalFilesMCLB.getRow(i)[0]; 
+                        confirmQuestion += "<TR><TD> </TD><TD><FONT COLOR=BLUE SIZE=+1>" + Utilities.forHTML(otherfilename) + "</FONT></TD></TR>";
+                    }
+                    confirmQuestion += "</TBODY></TABLE>";
+                }
+                else {
+                    confirmQuestion += "<TABLE><TBODY><TR><TD><FONT SIZE=+1>Main File:</FONT></TD><TD><FONT COLOR=BLUE SIZE=+1>" + Utilities.forHTML(filename)
+                        + "</FONT></TD></TR></TBODY></TABLE>";
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/ui/SubmitRunPane.java:511]: These two lines are essentially identical to lines 499/500 (with the exception of adding the `</TBODY><TABLE>` in line 511)  -- meaning the same code is being executed unconditionally (i.e. for the `if(true)` condition as well as for the `else` condition).   It seems to me it would be better to have these instructions appear just once -- i.e. code it as
```java
confirmQuestion += "...html which is _always_ added" ;
if (additionalFilesMCLB.getRowCount() > 0) {
  ... code to add each additional file name ...
}
confirmQuestion += "</TBODY></TABLE>";
```

However, I grant that this is somewhat in the realm of "coding style", and I certainly don't claim that the way it's done is _wrong_.  I'm also not saying it is a reason to reject the PR -- just pointing it out.

**Review by clevengr — APPROVED** [review]
I've reviewed the code changes, and also built and executed a distribution on the branch.  Everything seems great; approval.

**Comment by clevengr** [comment]
Two approvals; merging...

File: src/edu/csus/ecs/pc2/ui/SubmitRunPane.java (hunk 2 above)
Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/ui/SubmitRunPane.java:511]: Yes agreed, it could be made more concise.
