### PR TITLE
i_1061 Use supplied team_id for submissions by admins via the CLICS API

### LINKED ISSUE #1061: CLICS 2023-06 API Submission by admin for team uses wrong client id
**Describe the issue**: 
If an administrator or judge makes a submission on behalf of a team (by specifying a `team_id `property in the submission record), the `team_id `property is validated, but never used for the submission.

**To Reproduce**:

1. Start a contest like sumithello
2. Start an administrator client
3. Start an event feeder client and have it start listening for API requests on the 2023-06 API endpoints.
4. Add/change an entry in your `~/.netrc`  to: `machine localhost login administrator1 password administrator1`
5. Execute the following (or equivalient) from the command prompt:` pc2submit -p a -y --team_id 1 samps/src/hello.cpp`
6. Look at the **Runs** tab on the administrator client - note the run is from **administrator1** and not **team1**

**Expected behavior**: 
The run should be from **team1** since the `--team_id 1` was specified.

**Actual behavior**:
The run is incorrectly shown as being from `administrator1`

**Environment**: 
All.  PC^2 should have had #864 applied since this only applies to the new CLICS protocol.

**Log Info**: 

**Screenshots**: 

**Additional context**:

### PR DESCRIPTION
**Pull request by johnbrvc**
### Description of what the PR does
Use the optionally supplied `team_id `to make a submission on behalf of a team by an **adminsitrator**.  Previously, the `team_id `was validated, but never used.  We now create a `ClientId `and use that when we make the submission.
CI: expand error logging to include both the user making the request AND the `team_id `of the submission.
CI: expand error logging if a team is trying to submit on behalf of another team, or otherwise causes a permission error.

### Issue which the PR addresses
Fixes #1061 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 11
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
1. Start a contest like sumithello
2. Start an administrator client
3. Start an event feeder client and have it start listening for API requests on the 2023-06 API endpoints.
4. Add/change an entry in your `~/.netrc`  to: `machine localhost login administrator1 password administrator1`
5. Execute the following (or equivalient) from the command prompt:` pc2submit -p a -y --team_id 1 samps/src/hello.cpp`
6. Look at the **Runs** tab on the administrator client - note the run is from **team1** and not **administrator1**

### CODE REVIEW

File: src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java [hunk 1]
```diff
@@ -733,17 +766,20 @@ private ClientId getClientIdFromUser(String user) {
...
+                // an account must exist for this client id or it's invalid.
+                if(model.getAccount(clientId) == null) {
+                    clientId = null;
+                }
             }
         } catch (Exception e) {
             controller.getLog().log(Log.WARNING, "Can not convert the supplied team id " + id + " to a ClientId", e);
         }
-        return(valid);
+        return(clientId);
```
Comment (SamanwaySadhu) [inline src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java]: Use space instead of parentheses in the `return` statement

**Review by SamanwaySadhu — APPROVED** [review]
Other than the one comment, code changes looks good. Did not test out the code as `~/.netrc` step is a complicated to replicate in Windows.

File: src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java (hunk 1 above)
Comment (johnbrvc) [reply src/edu/csus/ecs/pc2/clics/API202306/SubmissionService.java]: Fixed in next push.

**Comment by johnbrvc** [comment]
> Other than the one comment, code changes looks good. Did not test out the code as `~/.netrc` step is a complicated to replicate in Windows.

Actually, it's not that hard to test.   Simply use notepad to create \users\YOURUSER\.netrc on Windows, and make whatever changes you want and save it.  Then run the test.  Repeat as necessary...
