### PR TITLE
I326 bad contest time in json

### LINKED ISSUE #326: Event Feed JSON report contains incorrect contest times in submissions
**Describe the issue**: 
A contest was configured to run for 8 days, with a freeze length (duration) of 24 hours (i.e. freeze the scoreboard for the last day).  Several submissions were received within the freeze period, but when the Event Feed was input to the Resolver, the Resolver reported "0 pending runs".  

Examination of the Event Feed JSON report (which is what was used to generated the input to the Resolver) revealed the following event in the event feed:
```
{"type":"submissions", "id":"pc2-824", "op":"create", "data": {"id":"648","language_id":"C++-1491114644002074695","problem_id":"Hello-1","team_id":"430","time":"2022-03-01T21:30:16.735-08","contest_time":"21:28:47.332","entry_point":"Hello-1","files":[{"href":"/submissions/648/files"}]}}
```
The submission time for that run, as shown on the Admin, is 11368 (minutes).  That's 189 hours and 28 minutes.  That run should have had a "contest_time"  entry of something like 189:28:47 -- just a few hours before the end of the contest and WELL past the freeze point, which as shown by this JSON event:
```
{"type":"state", "id":"pc2-2", "op":"create", "data": {"started":"2022-02-22T00:01:00.005-08","ended":"2022-03-02T00:01:00-08","frozen":"2022-03-01T00:01:00.005-08","finalized":"2022-03-02T00:17:01.180-08"}}
```
was at 1 minute past midnight on march 1st (i.e., one minute into Tuesday -- 24 hours before the end of the contest.

The submission event has a "contest_time" of `21:28:47.332` which is on the first day of the contest; that's wrong.

**To Reproduce**:
Run a contest for multiple days, with a freeze duration of 24 hours.  Submit a run within the freeze period.  Generate an Event Feed JSON report and look at the submission time (contest time) in the submission event.

**Expected behavior**:
The submission time should be more than 24 hours.

**Actual behavior**: 
The submission time ("contest_time") will be less than 24 hours.

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does
Adds method `public static String formatDuration (long milliseconds)` to class `Utilities`, and updates method ` JSONTool.convertToJSON(Run submission, HttpServletRequest servletRequest, SecurityContext sc)` to invoke `formatDuration()` instead of `ContestTime.formatTimeMS(msec)` when outputting a `contest_time` element to the JSON Event Feed.

The problem with `ContestTime.formatTimeMS()` is that it cannot handle times which are greater than 23:59:59; the new Utilities method will handle durations of arbitrary size.

PR also includes JUnits tests for a wide variety of duration formats.

### Issue which the PR fixes
#326 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Eclipse Version: 2019-12 (4.14.0) Build id: 20191212-1212
Windows 10.1
Java 1.8.0_201

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
Start a contest
Let it run for more than 24 hours
Submit some runs after more than 24 hours
On a PC2 admin, generate an Event Feed JSON report
Examine the "contest_time" field in the submissions which occurred more than 24 hours after the contest started.

Previously, those submissions would show contest_time values which were truncated modulo 24 hours; now, the contest_time values will be correct no matter how long the contest has been running.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/core/Utilities.java [hunk 1]
```diff
@@ -1903,8 +1903,61 @@ public static long convertCLICSContestTimeToMS(String time) {
...
+     * always be three digits.
+     * 
+     * @param milliseconds the duration to be formatted, in msec.
+     * @return the formatted value of the input duration.
+     */
+    public static String formatDuration (long milliseconds) {
+        
+        String result = "";
+        
+        long msecPerSecond = 1000;
```
Comment (lane55) [inline src/edu/csus/ecs/pc2/core/Utilities.java:1924]: Consider changing to time constants in Constants class, ex. Constants.MS_PER_SECOND, Constants.MS_PER_MINUTE

File: src/edu/csus/ecs/pc2/core/Utilities.java [hunk 2]
```diff
@@ -1903,8 +1903,61 @@ public static long convertCLICSContestTimeToMS(String time) {
...
+     * The general form of the returned format is HHHH:MM:SS.sss, where the number of hour digits will always be
+     * at least two, but may be more depending on the input value 
+     * (in other words, this is not a "time of day" which is restricted to just two hour-digits).
+     * Note however that the minutes and seconds fields will always be two digits, and the msec field will 
+     * always be three digits.
+     * 
+     * @param milliseconds the duration to be formatted, in msec.
+     * @return the formatted value of the input duration.
+     */
+    public static String formatDuration (long milliseconds) {
```
Comment (lane55) [inline src/edu/csus/ecs/pc2/core/Utilities.java:1920]: Consider handling negative milliseconds.

**Review by lane55 — APPROVED** [review]
There are a couple comments "Consider", these are not necessarily fixes,
just code/logic to consider.
