### PR TITLE
I432 command line suppress connections and logins grids

### LINKED ISSUE #432: Temporary support for command-line suppression of Connections and Logins grids on Admin.
**Describe the issue**: 
The ACPC 2022 Kickoff Contest died because of issues with PC2.  The contest had 3300+ teams and had received 6700+ submissions by the time it was called off.  The root issue seems to have been that the server crashed (probably due to OOM) and failed to write a large number of RunFiles to disk.  This in turn caused errors when attempts to fetch those runs were made.  At the same time, the Admin became totally unusable ("frozen") so no investigation or recovery attempts were possible.

A detailed investigation by a number of people spread across 9 time zones seems to indicate that the issue with the Admin freezing was the MCLB grids failing to handle the large number of WTI connections and logins.  Removing those two grids from the AdminView allowed a recreation of the contest to function smoothly (i.e., without the Admin locking up).

A longer-term solution needs to be found -- for example, replacing all uses of MCLB with JTables.  However, in order to get the next ACPC contest running in a few days, a workaround is to provide the ability to start the Admin without those two grids present.

**To Reproduce**: 
- Start up the ACPC 2022 Kickoff Contest on AWS, then start an Admin.  

**Expected behavior**: 
The Admin GUI should be responsive.

**Actual behavior**: 
The Admin GUI locks up (doesn't respond to input).

### PR DESCRIPTION
**Pull request by clevengr**
### Description of what the PR does
Adds two command-line options:  `--noconnectionspane` and `--nologinspane`.  When one (or both) of these options are specified on starting an Admin from the command line, the appearance of the corresponding grid (_Connections_ and _Logins_ respectively) is suppressed.  This provides a (brute-force) workaround for issues where these grids take so long to load that they effectively freeze the Admin.

Note: it is possible that PR #433, which replaces the old MCLB grids in AdminView with newer "JTable" versions, obviates the need for the fixes in this PR.  However, if it turns out that #433 does _not_ completely eliminate the problem described in Issue #432, this PR is needed to provide a rapid-response workaround for upcoming contests such as ACPC.  In any case, the PR is benign if the new options are not used.

### Issue which the PR fixes
Fixes #432, which was filed in an effort to provide the ACPC contest with a viable workaround when running extremely large contests (>3000 teams).

The code in the PR passes all JUnit tests, and a local build generated from the PR works as intended.

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 10.1; Eclipse Version: 2020-12 (4.18.0) Build id: 20201210-1552; Java 1.8.0_271.

### Precise steps for _testing_ the PR
- Start a server loading a contest, e.g. "SumitHello".
- Login a team (e.g. team1).
- Start an Admin using defaults.
- Observe the presence of the "Connections" and "Logins" tabs on the "Run Contest" tab.
  - Note the presence of both Connection and Login information (on the respective tabs) for "team1".
- Shut down the Admin.
- Restart the Admin, specifying either `--noconnectionspane` and/or `--nologinspane` as arguments on the command line.
  - Note the _absence_ of either or both of the "Connections" and/or "Logins" tabs on the "Run Contest" tab.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/core/model/IFileImpl.java [hunk 1]
```diff
@@ -2,8 +2,6 @@
 
 import java.util.Base64;
 
-import edu.csus.ecs.pc2.core.model.IFile;
```
Comment (troy2914) [inline src/edu/csus/ecs/pc2/core/model/IFileImpl.java:5]: the changes to this file seem unrelated to this ticket.

File: test/edu/csus/ecs/pc2/tools/PasswordGeneratorTest.java [hunk 2]
```diff
@@ -4,8 +4,6 @@
 import java.util.List;
 
 import edu.csus.ecs.pc2.core.util.AbstractTestCase;
-import edu.csus.ecs.pc2.tools.PasswordGenerator;
-import edu.csus.ecs.pc2.tools.PasswordType2;
```
Comment (troy2914) [inline test/edu/csus/ecs/pc2/tools/PasswordGeneratorTest.java:8]: more unrelated changes.

**Review by troy2914 — APPROVED** [review]
Approving, though confused about unrelated cleanup in a couple of files.

File: src/edu/csus/ecs/pc2/core/model/IFileImpl.java (hunk 1 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/core/model/IFileImpl.java:5]: The relationship of the changes in this file to the ticket is simply that the unchanged version of this file generates Errors in Eclipse -- and I didn't want to submit a PR with code that has Errors flagged in it.  I suspect the underlying issue might be that I'm developing in a different Eclipse environment -- my laptop, in Sharm -- from what I normally use.  However, I tried but failed to figure out what is different, and given the urgency for ACPC of getting this ticket resolved I had two choices -- check in code with Errors, or fix the item causing the Error.  (Yes, I could have filed a separate ticket just for this -- but I didn't have time to do that and get the code working and tested.

File: test/edu/csus/ecs/pc2/tools/PasswordGeneratorTest.java (hunk 2 above)
Comment (clevengr) [reply test/edu/csus/ecs/pc2/tools/PasswordGeneratorTest.java:8]: Same response as to the previous comment.
