### PR TITLE
i31: add support for stop on first in contest.yaml

### LINKED ISSUE #31: Add support for global yaml load stop-on-first-failed-test-case
**Feature Description**: 
Provide a "global" stop-on-first-failed-test-case setting.

In each problem.yaml there is an optional setting to stop testing on first failure
stop-on-first-failed-test-case : true

The default setting is false, execute all test cases.  If one want to set the setting
to true, one must edit every problem.yaml.   This also provides a place for potential
miss-configuration if one missed on problem.yaml file.

A second issue can be created to support this change in the Admin GUI.

**Have you considered other ways to accomplish the same thing?

  As described above, a stop-on-first-failed-test-case, must be placed in each problem.yaml

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?

Create a "global" scope stop-on-first-failed-test-case, at the same level as the scoreboard freeze 
name/value.
If a stop-on-first-failed-test-case is specified in problem.yaml that will override the "global" value.

**Additional context**: 

   A unit test should be created for this change.

### PR DESCRIPTION
**Pull request by lane55**
Add global support for stop-on-first-failed-test-case in
contest.yaml.
problem.yaml stop-on-first-failed-test-case can override the
settings in contest.yaml

### Description of what the PR does

Add yaml support for stop-on-first-failed-test-case in contest.yaml

### Issue which the PR fixes

#31 

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Add the following line to contest.yaml as a global setting.
```
stop-on-first-failed-test-case: true
```

By default the value is false.

Start  server loading the CDP/contest.yaml.
Start admin and check problem Test Data Files checkbox: Stop execution on first filed test case.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 1]
```diff
@@ -398,6 +402,13 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
             setCcsTestMode(contest, ccsTestMode);
         }
         
+        boolean stopOnFirstFail = fetchBooleanValue(content, STOP_ON_FIRST_FAILED_TEST_CASE_KEY, false);
+        if (stopOnFirstFail) {
+            setStopOnFirstFailedTestCase (contest, stopOnFirstFail);
+        }
+        
+        System.out.println("debug 22 for stopOnFirstFail is " +contest.getContestInformation().isStopOnFirstFailedtestCase() + " "+directoryName );
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java:410]: As someone keeps pointing out to me, debug print statements should be removed.

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java [hunk 2]
```diff
@@ -398,6 +402,13 @@ public IInternalContest fromYaml(IInternalContest contest, String[] yamlLines, S
             setCcsTestMode(contest, ccsTestMode);
         }
         
+        boolean stopOnFirstFail = fetchBooleanValue(content, STOP_ON_FIRST_FAILED_TEST_CASE_KEY, false);
+        if (stopOnFirstFail) {
```
Comment (clevengr) [inline src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java:406]: This "if" test doesn't make sense to me.  It says "if the 'stopOnFirstFail' boolean is TRUE, then update the setting".  It seems to me the setting should be updated whether it is true or false...

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java [hunk 3]
```diff
@@ -3499,5 +3499,63 @@ public void testScoreboardHTMLLocations() throws Exception {
...
+        Problem[] problems = contest.getProblems();
+        assertEquals("Num problems ",10, problems.length);
+        
+        for (Problem problem : problems) {
+            assertTrue(problem.getShortName()+" stop on first ", problem.isStopOnFirstFailedTestCase());
+        }
+        
+    }
+    
+    public void tesproblemflagtestStopOnFirstFailedTestCase() throws Exception {
```
Comment (clevengr) [inline test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3519]: If I recall correctly, JUnit methods must start with the characters "test...".   This method doesn't do that, so I don't think it will be recognized by JUnit as a Test.   Any anyway, it's a weird name for a method...

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java [hunk 4]
```diff
@@ -3499,5 +3499,63 @@ public void testScoreboardHTMLLocations() throws Exception {
...
+        
+        for (Problem problem : problems) {
+            assertTrue(problem.getShortName()+" stop on first ", problem.isStopOnFirstFailedTestCase());
+        }
+        
+    }
+    
+    
+    
+    public void testvaltesttStopOnFirstFailedTestCase() throws Exception {
```
Comment (clevengr) [inline test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3536]: This seems like a weird name for a method... why is there a "double-t" in the name?

**Review by clevengr — COMMENTED** [review]
See inline comments in source files.

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java (hunk 3 above)
Comment (lane55) [reply test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java]: pushed fix.  renamed method.  (when renamed, executed and failed, now passes)

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 2 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: removed if, pushed.

File: src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java (hunk 1 above)
Comment (lane55) [reply src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java]: :)  pushed fix.

File: test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java (hunk 4 above)
Comment (lane55) [reply test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3541]: renamed method and pushed.

Comment (clevengr) [reply test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3541]: I'm still confused about this method name:  why does it refer to "valtest"?  And again, why does it have a "double-t" in the name  (...valtesttStop...)?

Comment (clevengr) [reply test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java:3541]: ... I'm letting this go....

**Review by clevengr — APPROVED** [review]
I pulled the code from Doug's fork, created a contest with three problems, set the first problem to have stop-on-first-fail=true, the second problem to have stop-on-first-fail=false, and the third problem to have no setting for stop-on-first fail.  I then ran this contest (i.e., loaded it into a clean server) three times:  once with stop-on-first-fail=true in the contest.yaml, once with stop-on-first-fail=false in the contest.yaml, and once with NO setting for stop-on-first-fail in the contest.yaml.

For each configuration, I started an Admin and examined all three problems; all three had the correct stop-on-first-fail settings for the specified combination of problem.yaml settings and contest.yaml settings.

I approve this PR for merging.
