### PR TITLE
i441: Removed duplicate plugin entries, fixes #441

### LINKED ISSUE #441: Multiple entries are duplicated in pc2rui Plugins list
**Describe the issue**: please provide a clear and concise description of what the bug is.  
The `pc2rui` ReportsUI module contains a `UI Plugins` tab that displays a drop-down list of all PC2 UIPlugins and allows selecting a plugin and either opening it in a new window or adding it as a tab to the `pc2rui` GUI.  The plugin drop-down list contains _two_ entries for `Clarifications Table Pane`.  The first one was (probably) intended to be "Clarifications Pane" and intended to display the old "ClarificationsLegacyPane" which used MCLB instead of JTable.

**To Reproduce**: 
- Start the pc2rui module.
- Login as an administrator.
- Select the "UI Plugins" tab.
- Click the drop down box and scroll down.
- Observe that there are two identical entries for `Clarifications Table Pane`, and that when selected they produce identical results.

**Expected behavior**: 
There should not be two identical entries producing identical results.  The first one should probably be "Clarifications Pane" (or maybe "Clarifications Legacy Pane".

**Actual behavior**: 
See above.

**Environment**:
All.

**Screenshots**:  
image

### PR DESCRIPTION
**Pull request by johnbrvc**
Some entries were duplicated and they have been removed.  Also, the block of code that adds the plugins to the plugins array is now in alphabetical order.  This makes it easier to find existing entries, and to add new ones, without duplicating any.

Before submitting your Pull Request, please make sure you have read the [Guidelines for Submitting Pull Requests](https://github.com/pc2ccs/pc2v9/wiki/Guidelines-for-Submitting-Pull-Requests).  Then please provide the following information:

### Description of what the PR does
Removed duplicate entries from the plugins array so they do not appear in the pc2rui and other panes that use the plugins array.
### Issue which the PR fixes
#441 
### Environment in which the PR was developed (OS,IDE, Java version, etc.)
OS              : Windows 11 10.0 (amd64)
Java Version    : 1.8.0_321

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
1) Start the pc2rui application.
2) Go to the "UI Plugins" tab
3) Pull down the combo box and note there are no duplicate entries.

Notes: after removing the duplicate entries, I decided it was best to sort the lines that add entries to the array.  I do
realize that the array is sorted afterwards, but, this is purely to make the code more readable in the future.  It is now
easy to find entries (if they're there), and hopefully it will avoid adding duplicates in the future.  I realize the person
(@clevengr) who has to merge this will likely not be happy with all the differences in relatively few lines, but I think
it is worth it.  To compare the code it may be easier to cut and paste the relevant lines from both files, sort them, and
compare the sorted results to see what is different.  There will be 5 lines different which are the duplicates.

### CODE REVIEW

**Comment by lane55** [comment]
The test case should include the list of duplicated plugin classes.

**Comment by lane55** [comment]
these 5 panes were duplicated
AccountsTablePane
ClarificationsTablePane
EventFeedServerPane
RunsTablePane
StandingsTablePane

File: src/edu/csus/ecs/pc2/ui/PluginLoadPane.java [hunk 1]
```diff
@@ -178,47 +178,42 @@ public void setContestAndController(IInternalContest inContest, IInternalControl
     private JPanePlugin[] getPluginList() {
         Vector<JPanePlugin> plugins = new Vector<JPanePlugin>();
         
-        plugins.add(new RunsTablePane());
-        plugins.add(new AccountsTablePane());
-        plugins.add(new StandingsTablePane());
-        plugins.add(new ClarificationsTablePane());
-        plugins.add(new EventFeedServerPane());
-        plugins.add(new AccountsTablePane());
         plugins.add(new AccountsPane());
```
Comment (lane55) [inline src/edu/csus/ecs/pc2/ui/PluginLoadPane.java:181]: Expected to see a change with 5 fewer lines/Panes, aka remove duplicated panes.
As a result of the way this was changed I am required to manually determine determine
if extra Panes were removed or added.

Comment (lane55) [reply src/edu/csus/ecs/pc2/ui/PluginLoadPane.java:181]: In the future to avoid this confusion, push two commits.
1 - that fixes the problem without any scope creep/CI
2 - the scope creep (sorting of array)

**Review by lane55 — APPROVED** [review]
In the future push a commit that fixes the issue, then another to do CI.  That will
make it much easier to review the diffs/do the code review.

File: src/edu/csus/ecs/pc2/ui/PluginLoadPane.java (hunk 1 above)
Comment (clevengr) [reply src/edu/csus/ecs/pc2/ui/PluginLoadPane.java:181]: I have no problem with the rearrangement of the code (so that the list of additions is in alphabetical order); that is precisely the kind of "continuous improvement" that will help avoid a repetition of the problem (the existence of duplicate entries) in the future.  I also agree that while it's not (strictly speaking) part of the "Issue" which was filed, it's very reasonable to include it _as part of the PR_, under the banner of "CI" (because it's the kind of thing that would NEVER get done if it was shuffled off to it's own separate "Issue".)

Having said that, I also agree with Doug that it would have been very helpful if the "original issue" part (removal of the duplicates and the "CI" part (rearranging the list into alphabetical order to make it easier in the future to avoid duplicates)  had been submitted in separate commits (while still part of the same PR).  As it was, it turned this PR from a "5 minute review/approval" into one that took -- literally -- over three months, the reason being that I looked at it twice before, once in June and once again in July, and both times I hit the situation that I realized it was going to take way more than 5 minutes to review so I ended up putting it back in the "queue of things to do".  (In fact, it took me over half an hour to verify that (a) all the correct duplicates had been removed; (b) no incorrect entries had been removed, and (c) all the correct entries were still present in the "reshuffled" list.  I'm pretty sure I could have done that same verification in 5 minutes if there had been separate commits.)

Having said _that_, I will freely admit that _I'm not certain that I **myself** would have thought to make two separate commits when doing this_.   Hopefully we'll all get better at realizing how to make things easier... :)

**Review by clevengr — APPROVED** [review]
After a detailed review, verified that (a) the correct duplicate entries were removed (the original Issue), and also (b) no other entries were removed or added during the code rearrangement (the "CI" part).

I'm approving, and since this is the second approval I'll merge into Develop.
