### PR TITLE
I1049 Fix Contest Identifier during Profile Reset

### LINKED ISSUE #1049: Reset of contest loses ContestId
**Describe the issue**:
If you reset a contest its ContestId is set to the random "Default-##############" string.  The original ContetId is not preserved.

**To Reproduce**: 

1. Load up a contest.
2. Start it.
3. Stop it.
4. From an administrator, go to Profiles.
5. Select the contest.
6. Click on Reset.
7. Leave the 2 boxes it prompts for (languages and problems) unchecked.
8. Reset the contest.
9. Close admin
10. Close server
11. Start server
12. Start admin.
13. ContestId is no longer the original contest id, rather Default-XXXXXXXXXXXXXX

**Expected behavior**:
The ContestId should be preserved during a reset. 

**Actual behavior**: 
ContestId is not preserved, rather a new random one is created.

**Environment**:
All.

**Log Info**: 

**Screenshots**:  

**Additional context**: 
It appears when you reset, a backup is made of the contest, and a new one is created (copy).  The ContestId is not copied.
See line 2878  (or thereabouts) in routine `clone()` in `InternalContest.java`

```
        newProfile.setName(settings.getName());
        newProfile.setDescription(settings.getDescription());

        contest.setProfile(newProfile); // This also sets the contest identifier

```

### PR DESCRIPTION
**Pull request by SamanwaySadhu**
### Description of what the PR does
When the profile is getting cloned during reset, the `contestId` new profile object is set as same as the old profile's.

### Issue which the PR addresses
Fixes #1049 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 10, Eclipse 2021-12 R, JDK 8u381 (1.8), C++ 13.2.0

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
- Run the Ant script build.xml in the pc2v9 project.
- Start a PC2 Server.
- Start a PC2 Administrator.
- Start a PC2 Event Feeder (Generate one feeder account if not present).
- Click `View Event Feed`.
- The logs should now have the correct id from `contest.yaml` present.
- Now go to `Profiles` tab in Administrator.
- Reset the contest (when prompted keep the boxes unchecked).
- Go back to Event Feeder and `View Event Feed` again.
- The logs should still indicate correct id from `contest.yaml`.

### CODE REVIEW

File: src/edu/csus/ecs/pc2/core/PacketHandler.java [hunk 1]
```diff
@@ -1177,6 +1177,9 @@ private Profile cloneContest (Packet packet, ProfileCloneSettings settings, bool
         Profile newProfile = new Profile(settings.getName());
         newProfile.setDescription(settings.getDescription());
         newProfile.setSiteNumber(contest.getSiteNumber());
+        if (!StringUtilities.isEmpty(packet.getContestIdentifier())) {
```
Comment (johnbrvc) [inline src/edu/csus/ecs/pc2/core/PacketHandler.java:1180]: I guess it does make more sense to copy the contest ID here than in `InternalContest `since `InternalContest `is only a single implementation of `IInternalContest`, and we want the ID copied for `IInternalContest` implementation.  Please confirm this was your thinking in doing it this way.  The suggesting I put in the issue, namely, update it in `InternalContest`, appears to be insufficient.

Comment (SamanwaySadhu) [reply src/edu/csus/ecs/pc2/core/PacketHandler.java:1180]: There was no efficient way to get the contest short name in `InternalContest` without invoking a call to `ContestSnakeYAMLLoader`. The `packet` object here stores the short name `contestIdentfier` as new contest has not yet been "cloned".

**Review by kkarakas — APPROVED** [review]
LGTM!

**Review by johnbrvc — APPROVED** [review]
Looks good.
